<?php
declare(strict_types=1);
header('Content-Type: text/html; charset=utf-8');
if (session_status() !== PHP_SESSION_ACTIVE) { session_name('RH24_ORGABOARD'); session_start(); }
require_once __DIR__.'/bootstrap.php';
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$checks=[];function chk(string $name,bool $ok,string $detail=''):void{global $checks;$checks[]=[$name,$ok,$detail];}
$root=dirname(__DIR__);$index=@file_get_contents(__DIR__.'/index.php')?:'';$admin=@file_get_contents(__DIR__.'/admin-v9911.js')?:'';$apiPhp=@file_get_contents(__DIR__.'/api.php')?:'';$financeApi=@file_get_contents(__DIR__.'/finance-api.php')?:'';$financePhp=@file_get_contents(__DIR__.'/finance-v91.php')?:'';$customerStatus=@file_get_contents($root.'/order-status.php')?:'';
chk('PHP-Version',version_compare(PHP_VERSION,'8.1','>='),PHP_VERSION);
chk('V99 Bootstrap-Funktionsbibliothek',function_exists('rh24_sales_territories')&&function_exists('rh24_sales_reps')&&function_exists('rh24_territory_book_scope')&&function_exists('rh24_finance_data'),'Vertrieb, Gebietsbücher und Finanzmodul geladen');
chk('Orgaboard V99.1.1 Loader',str_contains($index,'admin-v9911.js')&&str_contains($index,'assets/earnings-v97.css')&&str_contains($index,'assets/pos-v95.css')&&str_contains($index,'assets/labels-v966.css')&&str_contains($index,'assets/appointments-v92.css')&&str_contains($index,'assets/finance-v91.css'),str_contains($index,'admin-v9911.js')?'V99.1.1 Boot-Hotfix + Live-HSN/TSN + Belegcenter aktiv':'Index lädt V99.1.1 nicht vollständig');
chk('V102 Light Professional Design',str_contains($index,'assets/light-pro-v102.css')&&is_file(__DIR__.'/assets/light-pro-v102.css'),'Helles V102-Design ist als letzte Designschicht aktiv');
chk('Admin-JavaScript V99.1.1',is_file(__DIR__.'/admin-v9911.js'),'V98 Fahrzeug-Assistent + V97 Verdienstrechner + V96.6 Etikettenstudio + V95 POS + V92 Termine + V91.1 Finanzen + alle bisherigen Funktionen');
chk('V99.1.1 Start-Wächter',str_contains($index,'__rh24FrontendStarted===true')&&str_contains($index,'__rh24ScriptLoaded!==true')&&str_contains($index,'Daten werden noch geladen'),'Frontend-Start und langsame API werden getrennt behandelt; kein falscher 12-Sekunden-Abbruch mehr');
chk('V97 Verdienstrechner',str_contains($admin,'Komplette Ausfüllhilfe')&&str_contains($admin,'Teamleiter · 3-%-Bonus')&&str_contains($admin,'earnTargetPayout')&&is_file(__DIR__.'/assets/earnings-v97.css'),'Ausfüllhilfe, Zielrückrechnung, Plan-Speicherung und Teamleiterbonus im Frontend vorhanden');
$bootV97=(string)@file_get_contents(__DIR__.'/bootstrap.php');
chk('V97 Teamleiterbonus Backend',str_contains($bootV97,'parent_sales_rep_id=?')&&str_contains($bootV97,'credited_rep_id')&&str_contains($bootV97,'team_leader_bonus_members')&&str_contains($bootV97,"rh24_setting_get('team_leader_bonus_rate','3')"),'3 % Bonus auf bezahlten Nettoumsatz direkt untergeordneter Verkäufer + Mitarbeiteraufschlüsselung geladen');
chk('V98 Fahrzeug-Assistent Frontend',str_contains($admin,'FAHRZEUG-ASSISTENT PRO')&&str_contains($admin,'vehicle_key_lookup')&&str_contains($admin,'HSN / TSN')&&is_file(__DIR__.'/assets/vehicle-v98.css'),'Manuell/HSN-TSN, Fahrzeugarten, Hilfe, Technik- und Verwaltungsdaten vorhanden');
chk('V99.1 Live HSN/TSN Frontend',str_contains($admin,'vehicle_lookup_test')&&str_contains($admin,'Live-Verbindung testen')&&str_contains($admin,'force_live'),'API-Zugang, Verbindungstest und Live-Neuladen vorhanden');
chk('V99.1 Live HSN/TSN Backend',function_exists('rh24_vehicle_lookup_test')&&str_contains($apiPhp,"vehicle_lookup_test")&&str_contains($apiPhp,"force_live"),'Serverseitige Live-Abfrage, verschlüsselte Zugangsdaten und API-Test vorhanden');
chk('V98 Fahrzeug-Assistent Backend',function_exists('rh24_vehicle_schema_health')&&function_exists('rh24_vehicle_lookup')&&function_exists('rh24_vehicle_lookup_config')&&is_file(__DIR__.'/vehicle-v98.php'),'Fahrzeugstammdaten, Katalog-Cache und optionale Live-Schnittstelle geladen');
chk('V99 Fahrtenbuch Belegcenter Frontend',str_contains($admin,'FAHRTENBUCH BELEGCENTER PRO')&&str_contains($admin,'Beleg speichern & buchen')&&is_file(__DIR__.'/assets/trip-receipts-v99.css'),'Foto/PDF, Betrag, Tankdaten, Hilfe und Buchhaltungsstatus vorhanden');
chk('V99 Fahrtenbuch Belegcenter Backend',function_exists('rh24_trip_receipt_schema_health')&&function_exists('rh24_trip_receipt_sync_finance')&&is_file(__DIR__.'/trip-receipts-v99.php')&&is_file(__DIR__.'/trip-receipt.php'),'Dublettenprüfung, sicherer Upload und Finance-Synchronisierung geladen');
$productImagePhp=@file_get_contents(__DIR__.'/product-image.php')?:'';
chk('V83.2 Bildformate',str_contains($admin,'image/avif')&&str_contains($admin,'image/heic')&&str_contains($admin,'image/heif')&&str_contains($productImagePhp,"'image/avif'")&&str_contains($productImagePhp,"'image/heic'"),'JPG/JPEG, PNG, WebP, AVIF, HEIC und HEIF in Browser + Server freigegeben');
chk('V83.2 Browser-Bildoptimierung',str_contains($admin,'prepareProductImage')&&str_contains($admin,"canvas.toBlob(resolve,'image/webp',0.86)")&&str_contains($admin,'const max=2000'),'WebP · Qualität 86 % · max. 2000 px');
chk('V83.2 Server-Bildoptimierung',str_contains($productImagePhp,'rh24_imagick_to_webp')&&str_contains($productImagePhp,'rh24_gd_to_webp'),'adaptive Imagick/GD-Fallbacks vorhanden · HEIC-Serverkonvertierung benötigt Imagick/libheif, falls Browser nicht konvertiert');
chk('V83.3 504-Schutz Branchenimport',str_contains($apiPhp??(@file_get_contents(__DIR__.'/api.php')?:''),'CURLOPT_TIMEOUT=>14')&&str_contains($admin,'territoryDiscoveryRequest')&&str_contains($admin,'TERRITORY_CORE_PACKS'),'kurze Server-Timeouts + Fallback + kleine Branchenpakete + Frontend-Retry');
chk('V83.3 Zielbranchen',str_contains($admin,"'fishing','meat','hardware','spices'")&&str_contains((string)@file_get_contents(__DIR__.'/bootstrap.php'),'spice_producer')&&str_contains((string)@file_get_contents(__DIR__.'/bootstrap.php'),'butcher_supply'),'Angel, Fleisch/Schlachterei, Baumarkt, Gewürze/Manufakturen und Bedarf vorhanden');
chk('V83.4 Gebietsbuch-Automatik',str_contains($admin,'territoryNationalBooksHtml')&&str_contains($admin,'territoryBookCategoryOverviewHtml')&&str_contains($apiPhp,'territory_book_no')&&str_contains($apiPhp,'assigned_sales_rep_id=CASE WHEN'),'16 Gebietsbücher + Branchenindex + automatische Treffer-/Beraterzuordnung');
chk('V84 Lager-Cockpit',str_contains($admin,'function warehousePurchaseOrderModal(')&&str_contains($admin,'function inventoryBookModal(')&&str_contains($apiPhp,'warehouse_stock_book')&&str_contains((string)@file_get_contents(__DIR__.'/bootstrap.php')?:'','rh24_warehouse_data'),'Leitstand, Beschaffung, Lieferanten, Lagerorte, Packmittel und Lagerbewegungen vorhanden');
chk('V85 Chef-Leitstand',str_contains($admin,'function renderExecutiveDashboard(')&&str_contains($admin,'Unternehmensgesundheit')&&str_contains($admin,'Chef-Prioritäten'),'Executive Dashboard mit Management-KPIs und Priorisierung vorhanden');
chk('V85 Lager-Ampel & Analytik',str_contains($admin,'function warehouseAnalyticsHtml(')&&str_contains($admin,'Bestands-Ampel')&&str_contains($admin,'Reichweite / Nachkaufdruck'),'Ampel, 30-Tage-Verbrauch und Reichweitenanalyse vorhanden');
chk('V85 Premium-Vertrieb',str_contains($admin,'function salesExecutiveOverviewHtml(')&&str_contains($admin,'function territoryBookExecutiveSummaryHtml(')&&str_contains($admin,'GEBIETSPERFORMANCE'),'Kundenberater-Managementansicht und Gebietsperformance vorhanden');
chk('V86 Cross-Selling Baukasten',str_contains($admin,'crossSellBuilder')&&str_contains($admin,'crossSuggest')&&str_contains($admin,'cross_sell_reciprocal')&&str_contains($apiPhp,'cross_sell_json')&&str_contains((string)@file_get_contents(__DIR__.'/bootstrap.php')?:'','rh24_ensure_v86_schema'),'Produktsuche, Typ, Priorität, Auto-Fill, gegenseitige Verknüpfung und Persistenz vorhanden');
chk('V89 CRM-Kundenakte',str_contains($admin,'customerMasterTabs')&&str_contains($admin,'payment_terms_days')&&str_contains($apiPhp,'billing_json')&&str_contains($apiPhp,'shipping_json'),'Kundentyp, Status, Rechnung/Lieferung, Steuerdaten, Zahlungswunsch, Zahlungsziel, Rabatt, Tags und Datenschutz vorhanden');
chk('V89 Payment Center',str_contains($admin,'function renderPayments(')&&str_contains($admin,'paymentConfigModal')&&str_contains($apiPhp,'payment_integration_save')&&str_contains((string)@file_get_contents(__DIR__.'/bootstrap.php')?:'','rh24_payment_provider_catalog'),'PayPal, Klarna, Amazon Pay, Sparkasse/S-Payment, Stripe, Google Pay, Apple Pay, Mollie, SEPA und Rechnung vorbereitet');
chk('V90 Deutschland Vollfüllung',str_contains($admin,'territoryNationalFillLoop')&&str_contains($admin,'Alle 16 Gebietsbücher vollständig füllen')&&str_contains($apiPhp,'territory_national_fill_step')&&str_contains($apiPhp,'rh24_territory_full_fill_packs')&&str_contains($apiPhp,'overpass.kumi.systems'),'16 Gebietsbücher · 9 Branchenpakete · serverseitiger Fortschritt · 3 Versuche · 3 Overpass-Endpunkte');
chk('V91 Finanz-Frontend',str_contains($admin,'function renderFinance()')&&str_contains($admin,'function fCsvParse(')&&str_contains($admin,'MONATSABSCHLUSS'),'10 Finanz-Arbeitsbereiche, CSV-Bankimport und Monatsabschluss vorhanden');
chk('V91 Finanz-API',is_file(__DIR__.'/finance-api.php')&&substr_count($financeApi,"if(\$action==='")>=20,'20 Finanzaktionen inkl. Belege, Banking, Kasse, OPOS, Anlagen, Budgets und Abschluss');
chk('V91 Finanz-Exporte',is_file(__DIR__.'/finance-export.php')&&str_contains((string)@file_get_contents(__DIR__.'/finance-export.php'),'datev')&&str_contains((string)@file_get_contents(__DIR__.'/finance-export.php'),'euer'),'CSV, OPOS, Kasse, Anlagen, USt, EÜR und DATEV vorhanden');
chk('V91 Belegschutz',is_file(__DIR__.'/finance-receipt.php')&&is_file(__DIR__.'/finance-uploads/.htaccess')&&str_contains((string)@file_get_contents(__DIR__.'/finance-receipt.php'),'receipt_sha256'),'geschützter Belegabruf, Upload-Prüfung und SHA-256 vorhanden');
chk('V91 Mahnwesen',is_file(__DIR__.'/finance-dunning.php')&&function_exists('rh24_finance_dunning_pdf')&&str_contains($financeApi,'dunning_email'),'PDF-Mahnung, Gebühren/Fristen und E-Mail-Versand verdrahtet');
chk('V92 Termin-Frontend',str_contains($admin,'function renderAppointments()')&&str_contains($admin,'appointmentDayView')&&str_contains($admin,'appointmentParseTasks')&&str_contains($admin,'appointmentDragId'),'Monat/Woche/Tag/Agenda, Filter, Aufgaben und Drag-&-Drop vorhanden');
chk('V92 Termin-API',str_contains($apiPhp,"appointment_move")&&str_contains($apiPhp,"appointment_duplicate")&&str_contains($apiPhp,"appointment_task_toggle")&&str_contains($apiPhp,"appointment_template_save")&&str_contains($apiPhp,"appointment_email_invite"),'Speichern, Verschieben, Duplizieren, Aufgaben, Vorlagen und E-Mail-Einladung vorhanden');
chk('V92 Termin-Dateien',is_file(__DIR__.'/assets/appointments-v92.css')&&is_file(__DIR__.'/termin-diagnose.php')&&is_file(__DIR__.'/termin-ics.php')&&is_file(__DIR__.'/terminplaner-print.php')&&is_file(__DIR__.'/appointment-reminders.php')&&is_file(__DIR__.'/termin-erinnerungen-einrichten.php'),'Termin-CSS, Diagnose, ICS, Druckansicht, Reminder-Engine und Admin-Einrichtung vorhanden');
chk('V95 POS-Frontend',str_contains($admin,'function renderPos()')&&str_contains($admin,'posRenderRegister')&&str_contains($admin,'posPaymentModal')&&str_contains($admin,'posRefundModal'),'Kasse, Scanner-Suche, Zahlungen, Retouren, Schichten und Hardware vorhanden');
chk('V94 POS-API',is_file(__DIR__.'/pos-api.php')&&substr_count((string)@file_get_contents(__DIR__.'/pos-api.php'),"if(\$action==='")>=10,'Schicht, Verkauf, Zahlung, Retoure, Bargeld, Abschluss und Einstellungen vorhanden');
chk('V94 POS-Verknüpfungen',function_exists('rh24_pos_create_order_from_sale')&&function_exists('rh24_pos_finance_cash_entry')&&function_exists('rh24_pos_product_rows'),'Shop/Lager → POS → Orders/Finanzen/Kassenbuch geladen');
chk('V95 POS-Hardware',is_file(__DIR__.'/pos-receipt.php')&&is_file(__DIR__.'/pos-zreport.php')&&str_contains($admin,'navigator.serial')&&str_contains($admin,'BarcodeDetector'),'Bon-/Z-Druck, ESC/POS-WebSerial, Kassenlade, HID/Kamera-Scanner vorbereitet');
chk('V95 Laden-/Demo-Modus',is_file(__DIR__.'/pos-demo.html')&&is_file(__DIR__.'/assets/pos-v95.css')&&str_contains($admin,'posToggleKiosk')&&str_contains($admin,'posUiScale'),'Vollbild, Touch, skalierbare Kassenansicht und buchungsfreie Demo vorhanden');
chk('V96.6 Etikettenstudio Frontend',str_contains($admin,'function renderLabels()')&&str_contains($admin,'labelStudioShellV966')&&str_contains($admin,'labelInspectorTabsV966')&&str_contains($admin,'function labelPrintersView()')&&str_contains($admin,'labelPaperAutomation')&&is_file(__DIR__.'/assets/labels-v966.css'),'Studio, Live-Vorschau, Seriendruck, Vorlagen, Drucker und Historie vorhanden');
chk('V96.6 Etiketten-API',is_file(__DIR__.'/label-api.php')&&substr_count((string)@file_get_contents(__DIR__.'/label-api.php'),"if(\$action==='")>=8,'Vorlagen, Drucker, Jobs, Nachdruck und Einstellungen vorhanden');
chk('V96.6 Barcode/QR & Druck',is_file(__DIR__.'/label-print.php')&&str_contains((string)@file_get_contents(__DIR__.'/label-print.php'),'bwipjs.toCanvas')&&str_contains($index,'bwip-js@4.11.2'),'Code128, EAN-13, QR und exakte mm-Druckseiten vorhanden');
chk('V96.6 Druckerprofile',function_exists('rh24_label_data')&&function_exists('rh24_label_printers')&&function_exists('rh24_label_templates'),'Brother/HP/Normaldrucker/Zebra/TSC/DYMO/Generic Profile, Papierautomation und Vorlagenlogik geladen');
try{$v961tpl=rh24_label_templates();chk('50 Profi-Etikettenvorlagen',count($v961tpl)>=50,count($v961tpl).' Vorlagen geladen');}catch(Throwable $e){chk('50 Profi-Etikettenvorlagen',false,$e->getMessage());}
chk('V86 Cross-Selling Shop',str_contains((string)@file_get_contents($root.'/artikel.php')?:'','crossSellPublic')&&is_file($root.'/cross-selling-v86.css'),'Empfehlungskarten + Warenkorb-Integration auf dynamischer Produktseite vorhanden');
chk('V87 Responsive-Lesbarkeit',str_contains((string)@file_get_contents(__DIR__.'/assets/admin.css')?:'','V87 RESPONSIVE READABILITY')&&str_contains($index,'assets/admin.css'),'Vollbreiten-Shell, adaptive Executive-Raster, lesbare Balken und Panel-Minbreiten aktiv');
chk('V88 Lagerraum-Cockpit',str_contains($admin,'warehouseCockpitHtml')&&str_contains($admin,'warehouseZoneMapHtml')&&str_contains($admin,'warehouseOrderReadiness')&&str_contains($admin,'warehouseStocktakeModal')&&str_contains($admin,'warehouseStockLocationModal'),'Zonen, Lagerplätze, Materialfluss, Auftragsbereitschaft, Prioritäten und Inventur vorhanden');
chk('V88 Warehouse-Persistenz',str_contains((string)@file_get_contents(__DIR__.'/bootstrap.php'),'stock_locations')&&str_contains((string)@file_get_contents(__DIR__.'/bootstrap.php'),'capacity_skus'),'Lagerplatzzuordnung und SKU-Kapazitäten werden persistent gespeichert');
$rendererNames=['renderDashboard','renderOrders','renderProduction','renderProductionStaff','renderPrototypes','renderCustomers','renderSales','renderTerritories','renderSalesReps','renderDealers','renderProducts','renderNatureSpices','renderProductAnalysis','renderInventory','renderShipping','renderDocuments','renderMessages','renderMyStats','renderEarnings','renderLeaderboard','renderSalesCalendar','renderAppointments','renderTerritoryBook','renderProfile','renderMobileApp','renderCalculator','renderCalculatorHelp','renderReviews','renderContent','renderAI','renderAdministration','renderRights','renderNewsletter','renderShopDesign','renderMarketplace','renderSettings'];
$missingRenderers=[];foreach($rendererNames as $rn){if(!str_contains($admin,'function '.$rn.'('))$missingRenderers[]=$rn;}
chk('Renderer-Vollständigkeit',count($missingRenderers)===0,count($missingRenderers)===0?'36/36 Renderer vorhanden':'Fehlen: '.implode(', ',$missingRenderers));
chk('Produktionsrollen-Frontend',str_contains($admin,'Produktions-Logins')&&str_contains($admin,"forcedRole=''")&&str_contains($admin,'Produktion · Fertigung, kein Außendienst'),'Administration und Benutzereditor kennen die eigenständige Produktionsrolle');
chk('Marktplatz-Frontend',is_file($root.'/ankauf-verkauf.php'),'../ankauf-verkauf.php');
chk('Marktplatz-API',is_file($root.'/marketplace-api.php'),'../marketplace-api.php');
chk('Marktplatz-Styles',is_file($root.'/marketplace-v61.css'),'../marketplace-v61.css');
chk('Marktplatz-JavaScript',is_file($root.'/marketplace-v61.js'),'../marketplace-v61.js');
chk('Marktplatz-AGB V61',is_file($root.'/marktplatz-agb.html'),'../marktplatz-agb.html');
chk('Lebensmittel-Sperre API',str_contains(@file_get_contents($root.'/marketplace-api.php')?:'','market_contains_disallowed_food'),'serverseitige Inhaltsprüfung');

chk('E-Mail-Bestätigung',is_file($root.'/marktplatz-verifizieren.php'),'../marktplatz-verifizieren.php');
chk('Nutzungsregeln',is_file($root.'/marktplatz-regeln.html'),'../marktplatz-regeln.html');
chk('Orgaboard Marktplatz',str_contains($admin,'function renderMarketplace('),'Mitglieder, Freigaben und Meldungen');
chk('Produktionsleitstand V69',str_contains($admin,'productionEditModal')&&str_contains($admin,'productionPhaseTabs')&&str_contains($admin,'productionStartWork'),'Kunden, Produktionsteam, Ausgeführt-von-Nachweis und 0–100-%-Fortschritt');
chk('Produktionsteam V69',str_contains($admin,'renderProductionStaff')&&str_contains($admin,'productionExecutionView')&&str_contains($admin,'edit_production'),'eigene Rolle · Mitarbeiterzuweisung · automatischer Ausführungsnachweis');
chk('V72 Kundenberater-Reiter',str_contains($admin,'Regionalmanager')&&str_contains($admin,'Bezirksmanager')&&str_contains($admin,'Kundenberater BE')&&str_contains($admin,'Gebiet vergeben'),'6 Vertriebsreiter inkl. Gebiet vergeben vorhanden');
chk('V74 Deutschland-Verzeichnis',str_contains($admin,'renderTerritoryBook')&&str_contains($admin,'Kundenberater-Plattform')&&str_contains($admin,'Kontaktiert / Kalender'),'Deutschland-Suche · Gebietsbuch · Direktkontakt · Kalender vorhanden');
chk('V73 Print/PDF',is_file(__DIR__.'/territory-book-print.php'),'Druck-/PDF-Ansicht vorhanden');
chk('V74 Deutschland-Suche',str_contains($admin,'territory_directory_search')&&str_contains($admin,'Deutschland synchronisieren')&&str_contains($admin,'Alle Restaurants'),'Bundesweite Suche, Filter und Synchronisierung vorhanden');
chk('V74 Restaurant-Branche',str_contains(@file_get_contents(__DIR__.'/bootstrap.php')?:'',"'restaurant'=>'Restaurant / Gastronomie'")&&str_contains(@file_get_contents(__DIR__.'/api.php')?:'','["amenity"="restaurant"]'),'Restaurants als eigene Branche recherchierbar');
chk('V72 Bundeslandfarben',str_contains($admin,'TERRITORY_COLORS')&&str_contains($admin,"'01':'#14B8A6'")&&str_contains($admin,"'16':'#EC4899'"),'16 feste Bundeslandfarben im Kartenmodul');
chk('Verkaufsherkunft V69',str_contains($admin,'salesOriginTag')&&str_contains($admin,'orderChannelFilter')&&str_contains($admin,'Provisionsgutschrift'),'Online, Kundenberater, Telefonleitung, E-Mail und weitere Kanäle getrennt sichtbar');
$bootstrap=@file_get_contents(__DIR__.'/bootstrap.php')?:'';$shopOrder=@file_get_contents($root.'/shop-order.php')?:'';
chk('Provisionslogik V69',str_contains($bootstrap,'rh24_resolve_sales_attribution')&&str_contains($bootstrap,'online_commission_rotation_next')&&str_contains($bootstrap,'commission_sales_rep_id'),'Bestandsberater-Vorrang + alternierende Hausgutschrift Björn/Jessica');
chk('Online-Auftragszuordnung V69',str_contains($shopOrder,"rh24_resolve_sales_attribution(\$db,\$customerId,'online','')")&&str_contains($shopOrder,'commission_sales_rep_id'),'Shopbestellungen laufen durch die zentrale Zuordnungslogik');

chk('HD Hahne Safe-Footer',is_file($root.'/powered-by-click.php')&&str_contains(@file_get_contents($root.'/index.html')?:'','data-rh701-hd-credit'),'statischer Footer ohne globales neues Website-JavaScript');
chk('Kunden-Bestellfortschritt V77',is_file($root.'/order-status.php')&&is_file($root.'/order-document.php')&&is_file($root.'/customer-order-status-v77.js')&&is_file($root.'/customer-order-status-v77.css'),'Serverstatus + geschützter PDF-Download vorhanden');
chk('Kundenstatus Datenschutz',!str_contains($customerStatus,'production_note')&&!str_contains($customerStatus,'production_assignee')&&!str_contains($customerStatus,'internal_note'),'Interne Produktionsdaten werden nicht ausgegeben');
chk('Produktzentrale V83',str_contains($admin,'PRODUKT-BAUKASTEN · V83')&&str_contains($admin,'renderProductBuilderHub')&&str_contains($admin,'productDeleteModal')&&str_contains($admin,'LIVE-VORSCHAU AKTIV'),'Eigener Baukasten-Menüpunkt, Vorschau und Löschschutz vorhanden');
chk('Produktfunktionen eindeutig',substr_count($admin,'function renderProducts(')===1&&substr_count($admin,'function productModal(')===1,'renderProducts: '.substr_count($admin,'function renderProducts(').' · productModal: '.substr_count($admin,'function productModal('));
chk('Naturgewürze-Funktion',str_contains($admin,'function renderNatureSpices('),'renderNatureSpices vorhanden');
chk('Produkt-Analyse',str_contains($admin,'function renderProductAnalysis('),'Halbjahres-/Bestseller-Auswertung vorhanden');
chk('Smoky KI',is_file($root.'/smoky-berater.js')&&is_file($root.'/smoky-api.php'),'Smoky-Berater Frontend + API');
chk('api.php',is_file(__DIR__.'/api.php'));
chk('bootstrap.php',is_file(__DIR__.'/bootstrap.php'));
chk('Datenbank-Konfiguration',is_file(__DIR__.'/private/db-config.php'),'Zugangsdaten werden nicht angezeigt');
$dbInfo=[];
if(is_file(__DIR__.'/private/db-config.php')){
 try{$cfg=require __DIR__.'/private/db-config.php';$start=microtime(true);$dsn=sprintf('mysql:host=%s;dbname=%s;charset=%s',$cfg['host'],$cfg['database'],$cfg['charset']??'utf8mb4');$db=new PDO($dsn,(string)$cfg['user'],(string)$cfg['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_TIMEOUT=>8]);chk('MariaDB-Verbindung',true,number_format((microtime(true)-$start)*1000,0,',','.').' ms');
 try{$fh=rh24_finance_ensure_ready($db);chk('V91.1 Finanz-Selbstreparatur',(bool)($fh['ok']??false),'Schema '.($fh['schema_version']??'?').' · '.count($fh['available']??[]).' / 12 Finanztabellen bereit');}catch(Throwable $e){chk('V91.1 Finanz-Selbstreparatur',false,$e->getMessage());}
 try{rh24_label_ensure_ready();$lh=rh24_label_schema_health($db);chk('Etikettenschema V96.6',(bool)$lh['ready']&&((int)$lh['version']>=965),'Version '.($lh['version']??0).' · '.count($lh['missing']??[]).' fehlende Tabellen');}catch(Throwable $e){chk('Etikettenschema V96.6',false,$e->getMessage());}
 foreach(['settings','users','orders','customers','products','documents','document_versions','advisor_appointments','advisor_appointment_attendees','advisor_appointment_tasks','advisor_appointment_templates','trip_vehicles','vehicle_key_catalog','trip_log','trip_receipts','market_users','market_listings','market_messages','market_reports','finance_suppliers','finance_cost_centers','finance_accounts','finance_bank_accounts','finance_transactions','finance_expenses','finance_cash_entries','finance_assets','finance_recurring','finance_budgets','finance_dunning','finance_period_closings','label_printers','label_templates','label_jobs','label_job_items'] as $table){try{$st=microtime(true);$n=(int)$db->query('SELECT COUNT(*) FROM `'.$table.'`')->fetchColumn();$dbInfo[]=[$table,$n,(microtime(true)-$st)*1000];chk('Tabelle '.$table,true,$n.' Einträge');}catch(Throwable $e){$dbInfo[]=[$table,'—',0];chk('Tabelle '.$table,false,$e->getMessage());}}
 try{$n=(int)($db->query("SELECT COUNT(*) FROM sales_territories")->fetchColumn()?:0);chk('V71 Festgebiete', $n===16, $n.' / 16 Bundesländer mit Gebietsbuch');}catch(Throwable $e){chk('V71 Festgebiete',false,$e->getMessage());}
 try{$cols=$db->query("SHOW COLUMNS FROM sales_reps")->fetchAll(PDO::FETCH_COLUMN);$needed=['state_code','parent_sales_rep_id','team_leader_since'];$missing=array_values(array_diff($needed,$cols));chk('V71 Teamstruktur',count($missing)===0,count($missing)===0?'Bundesland, Teamleiter und Bonusstart vorhanden':'Fehlen: '.implode(', ',$missing));}catch(Throwable $e){chk('V71 Teamstruktur',false,$e->getMessage());}
try{$cols=$db->query("SHOW COLUMNS FROM sales_reps")->fetchAll(PDO::FETCH_COLUMN);$needed=['sales_role','role_since'];$missing=array_values(array_diff($needed,$cols));chk('V72 Vertriebsrollen',count($missing)===0,count($missing)===0?'Regionalmanager, Bezirksmanager, Teamleiter, Aktiv und BE abbildbar':'Fehlen: '.implode(', ',$missing));}catch(Throwable $e){chk('V72 Vertriebsrollen',false,$e->getMessage());}
 try{$n=(int)($db->query("SELECT COUNT(*) FROM sales_reps WHERE sales_role IN ('regional_manager','district_manager','team_leader','advisor_active','advisor_be','house')")->fetchColumn()?:0);chk('V72 Rollenwerte',true,$n.' Mitarbeiter/Hauskonten mit gültiger Vertriebsrolle');}catch(Throwable $e){chk('V72 Rollenwerte',false,$e->getMessage());}
try{$db->query("SELECT 1 FROM territory_directory LIMIT 1");$db->query("SELECT 1 FROM territory_contact_logs LIMIT 1");chk('V73 Gebietsbuch-Tabellen',true,'territory_directory + territory_contact_logs vorhanden');}catch(Throwable $e){chk('V73 Gebietsbuch-Tabellen',false,$e->getMessage());}
 $schema=(string)($db->query("SELECT setting_value FROM settings WHERE setting_key='schema_version'")->fetchColumn()?:'unbekannt');chk('Datenbankschema V91',((int)$schema)>=91,'Version '.$schema.' · erwartet mindestens 91');
 try{$appointmentSchema=(int)($db->query("SELECT setting_value FROM settings WHERE setting_key='appointment_schema_version'")->fetchColumn()?:0);chk('Terminschema V92',$appointmentSchema>=92,'Version '.$appointmentSchema.' · erwartet mindestens 92');}catch(Throwable $e){chk('Terminschema V92',false,$e->getMessage());}
 try{$vh=rh24_vehicle_schema_health($db);chk('Fahrzeugschema V98',(bool)($vh['ready']??false),'Version '.($vh['version']??0).' · '.count($vh['missing']??[]).' fehlende Fahrzeugfelder');}catch(Throwable $e){chk('Fahrzeugschema V98',false,$e->getMessage());}
 try{$rh=rh24_trip_receipt_schema_health($db);chk('Belegschema V99',(bool)($rh['ready']??false),'Version '.($rh['version']??0).' · '.count($rh['missing']??[]).' fehlende Belegfelder');}catch(Throwable $e){chk('Belegschema V99',false,$e->getMessage());}
 try{$cols=$db->query("SHOW COLUMNS FROM trip_vehicles")->fetchAll(PDO::FETCH_COLUMN);$needed=['vehicle_type','manufacturer','model','hsn','tsn','vin','fuel_type','power_kw','hu_due','service_due','usage_type'];$missing=array_values(array_diff($needed,$cols));chk('V98 Fahrzeugfelder',count($missing)===0,count($missing)===0?'HSN/TSN, VIN, Technik und Termine vorhanden':'Fehlen: '.implode(', ',$missing));}catch(Throwable $e){chk('V98 Fahrzeugfelder',false,$e->getMessage());}
 try{$cols=$db->query("SHOW COLUMNS FROM advisor_appointments")->fetchAll(PDO::FETCH_COLUMN);$needed=['all_day','meeting_url','buffer_before_minutes','buffer_after_minutes','reminder_2_minutes','reminder_channel','series_id','recurrence_rule','recurrence_until','color','tags_json','outcome','next_action','follow_up_at','confirmed_at','confirmation_source','last_reminded_at','reminder_1_sent_at','reminder_2_sent_at'];$missing=array_values(array_diff($needed,$cols));chk('V92 Terminfelder',count($missing)===0,count($missing)===0?'Serien, Puffer, Erinnerungen, Ergebnis und Wiedervorlage vorhanden':'Fehlen: '.implode(', ',$missing));}catch(Throwable $e){chk('V92 Terminfelder',false,$e->getMessage());}
 try{$cols=$db->query("SHOW COLUMNS FROM products")->fetchAll(PDO::FETCH_COLUMN);$needed=['short_description','features_json','seo_title','seo_description','is_new','new_until','published_at'];$missing=array_values(array_diff($needed,$cols));chk('V83 Produktfelder',count($missing)===0,count($missing)===0?'Baukasten-, SEO- und Neu-im-Sortiment-Felder vorhanden':'Fehlen: '.implode(', ',$missing));}catch(Throwable $e){chk('V83 Produktfelder',false,$e->getMessage());}
 try{$cols=$db->query("SHOW COLUMNS FROM documents")->fetchAll(PDO::FETCH_COLUMN);$needed=['pdf_sha256','pdf_generated_at','emailed_at','email_status','locked_at','cancelled_at','cancel_reason'];$missing=array_values(array_diff($needed,$cols));chk('V77 Dokumentfelder',count($missing)===0,count($missing)===0?'PDF-Hash, E-Mail, Sperr- und Stornofelder vorhanden':'Fehlen: '.implode(', ',$missing));}catch(Throwable $e){chk('V77 Dokumentfelder',false,$e->getMessage());}
 try{$cols=$db->query("SHOW COLUMNS FROM orders")->fetchAll(PDO::FETCH_COLUMN);$needed=['sales_channel','commission_sales_rep_id','commission_attribution','commission_note','commission_assigned_at'];$missing=array_values(array_diff($needed,$cols));chk('V69 Auftragsfelder',count($missing)===0,count($missing)===0?'Herkunft + Provisionsfelder vorhanden':'Fehlen: '.implode(', ',$missing));}catch(Throwable $e){chk('V69 Auftragsfelder',false,$e->getMessage());}
 try{$cols=$db->query("SHOW COLUMNS FROM customers")->fetchAll(PDO::FETCH_COLUMN);$needed=['sales_rep_id','advisor_assigned_at','advisor_assignment_source'];$missing=array_values(array_diff($needed,$cols));chk('V69 Kundenberaterfelder',count($missing)===0,count($missing)===0?'feste Kundenberaterbindung vorhanden':'Fehlen: '.implode(', ',$missing));}catch(Throwable $e){chk('V69 Kundenberaterfelder',false,$e->getMessage());}

 }catch(Throwable $e){chk('MariaDB-Verbindung',false,$e->getMessage());}
}

chk('Rechnungstool V77',function_exists('rh24_invoice_profile')&&function_exists('rh24_document_pdf_content')&&function_exists('rh24_email_order_documents'),'Rechnungsprofil + Server-PDF + PDF-E-Mail geladen');
chk('Rechnungs-PDF-Endpunkt',is_file(__DIR__.'/document-pdf.php'),'document-pdf.php geschützt im Orgaboard');
chk('Kunden-PDF-Endpunkt',is_file($root.'/order-document.php'),'order-document.php mit Bestellung + E-Mail-Prüfung');
chk('Shop-Rechnungsautomatik',str_contains($shopOrder,'rh24_email_order_documents')&&str_contains($shopOrder,'documents_sent'),'Online-Bestellung erzeugt Rechnung/Lieferschein und versucht PDF-Versand');
chk('Rechnungstool Frontend',str_contains($admin,'function renderDocuments()')&&str_contains($admin,'invoiceProfileModalV77')&&str_contains($admin,'docCancelV77'),'Rechnungsübersicht, Einrichtung, PDF/E-Mail und Storno-Funktionen vorhanden');

$logged=!empty($_SESSION['rh24_user']['id']);chk('Orgaboard-Sitzung',$logged,$logged?'Angemeldet als '.($_SESSION['rh24_user']['display_name']??$_SESSION['rh24_user']['username']??'Benutzer'):'Keine aktive Anmeldung');
chk('Terminmanagement-Schema V92',function_exists('rh24_appointment_data')&&function_exists('rh24_appointment_expand_series')&&function_exists('rh24_appointment_save_related')&&function_exists('rh24_appointment_send_due_reminders'),'Termin-, Serien-, Teilnehmer-, Aufgaben- und Reminderlogik geladen');
chk('Terminplaner Kundenstamm-Suche',function_exists('rh24_appointment_customer_search'),'serverseitige Kundensuche '.(function_exists('rh24_appointment_customer_search')?'geladen':'FEHLT'));
chk('Terminplaner Druck',is_file(__DIR__.'/terminplaner-print.php'),'terminplaner-print.php');
chk('Terminplaner ICS',is_file(__DIR__.'/termin-ics.php'),'termin-ics.php');
chk('Fahrtenbuch-Schema V75',function_exists('rh24_triplog_data'),'rh24_triplog_data '.(function_exists('rh24_triplog_data')?'geladen':'FEHLT'));
chk('Google-Routenfunktion',function_exists('rh24_google_routes_compute'),'serverseitige Google Routes API');
$okCount=count(array_filter($checks,fn($x)=>$x[1]));$all=count($checks);
?><!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RH24 V98 Systemdiagnose</title><style>body{font-family:system-ui,-apple-system,sans-serif;background:#f5f2ed;color:#22160f;margin:0;padding:24px}.wrap{max-width:980px;margin:auto}.card{background:#fff;border:1px solid #ddd3c8;border-radius:18px;padding:22px;margin:14px 0;box-shadow:0 8px 30px #0001}h1{margin:0 0 8px}.ok{color:#137333}.bad{color:#b3261e}.row{display:grid;grid-template-columns:1.3fr .55fr 2.1fr;gap:16px;padding:12px 0;border-bottom:1px solid #eee}.row:last-child{border:0}code{background:#f3eee8;padding:2px 6px;border-radius:6px}a{display:inline-block;background:#4c2412;color:white;padding:12px 16px;border-radius:10px;text-decoration:none;margin:5px 8px 5px 0}.score{font-size:28px;font-weight:900}.score.good{color:#137333}.score.bad{color:#b3261e}@media(max-width:700px){.row{grid-template-columns:1fr}.row span{display:block}}</style></head><body><div class="wrap"><div class="card"><small>RÄUCHERHAKEN24 · V98</small><h1>Systemdiagnose</h1><p>Prüft Orgaboard V98 inklusive Fahrzeug-Assistent Pro und Verdienst- & Provisionsrechner Pro mit 3-%-Teamleiterbonus, Print & Media Studio Pro, POS & Kasse Pro, Terminmanagement, Finanz-/Buchhaltungsmodul, Gebietsbücher, CRM, Produktzentrale, Rechnungstool, Shop-Automation, Fahrtenbuch und MariaDB, ohne Passwörter anzuzeigen.</p><div class="score <?=$okCount===$all?'good':'bad'?>"><?=$okCount?> / <?=$all?> Prüfungen OK</div></div><div class="card"><?php foreach($checks as [$name,$ok,$detail]):?><div class="row"><b><?=h($name)?></b><strong class="<?=$ok?'ok':'bad'?>"><?=$ok?'OK':'FEHLER'?></strong><span><?=h($detail)?></span></div><?php endforeach;?></div><?php if($dbInfo):?><div class="card"><h2>Datenbank-Abfragen</h2><?php foreach($dbInfo as [$table,$count,$ms]):?><div class="row"><code><?=h($table)?></code><strong><?=h($count)?></strong><span><?=number_format((float)$ms,0,',','.')?> ms</span></div><?php endforeach;?></div><?php endif;?><div class="card"><a href="./">Orgaboard öffnen</a><a href="../ankauf-verkauf.php" target="_blank" rel="noopener">An- & Verkaufen öffnen</a><a href="../shop.html" target="_blank" rel="noopener">Shop öffnen</a><a href="diagnose.php?<?=time()?>">Neu prüfen</a></div></div>
</body></html>
