<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';rh24_require_login();
if(!rh24_can('view_finance')){http_response_code(403);exit('Keine Berechtigung.');}
$db=rh24_db();$id=trim((string)($_GET['id']??$_POST['expense_id']??''));if($id===''){http_response_code(400);exit('Beleg-ID fehlt.');}
$q=$db->prepare('SELECT id,voucher_no,receipt_path,receipt_name,source_module,source_ref FROM finance_expenses WHERE id=?');$q->execute([$id]);$e=$q->fetch();if(!$e){http_response_code(404);exit('Beleg nicht gefunden.');}
if($_SERVER['REQUEST_METHOD']==='POST'){
  if((string)($e['source_module']??'')==='triplog'){http_response_code(409);header('Content-Type: application/json');echo json_encode(['ok'=>false,'error'=>'Dieser Originalbeleg stammt aus dem Fahrtenbuch-Belegcenter. Bitte dort stornieren bzw. neu erfassen, damit Fahrzeugakte und Buchhaltung synchron bleiben.']);exit;}
  if(!rh24_can('edit_finance')){http_response_code(403);header('Content-Type: application/json');echo json_encode(['ok'=>false,'error'=>'Keine Bearbeitungsberechtigung.']);exit;}
  rh24_verify_csrf($_SERVER['HTTP_X_CSRF_TOKEN']??($_POST['csrf']??null));if(!isset($_FILES['receipt'])||!is_uploaded_file($_FILES['receipt']['tmp_name'])){http_response_code(422);header('Content-Type: application/json');echo json_encode(['ok'=>false,'error'=>'Keine Belegdatei empfangen.']);exit;}
  $f=$_FILES['receipt'];if((int)$f['size']<=0||(int)$f['size']>15*1024*1024){http_response_code(422);header('Content-Type: application/json');echo json_encode(['ok'=>false,'error'=>'Belegdatei muss zwischen 1 Byte und 15 MB groß sein.']);exit;}
  $orig=basename((string)$f['name']);$ext=strtolower(pathinfo($orig,PATHINFO_EXTENSION));$allowed=['pdf','jpg','jpeg','png','webp','xml'];if(!in_array($ext,$allowed,true)){http_response_code(422);header('Content-Type: application/json');echo json_encode(['ok'=>false,'error'=>'Erlaubt: PDF, JPG, PNG, WEBP oder XML.']);exit;}
  $mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name'])?:'';$mimeOk=['application/pdf','image/jpeg','image/png','image/webp','application/xml','text/xml','text/plain'];if(!in_array($mime,$mimeOk,true)){http_response_code(422);header('Content-Type: application/json');echo json_encode(['ok'=>false,'error'=>'Dateityp wurde nicht als zulässiger Beleg erkannt.']);exit;}
  $name=$id.'-'.bin2hex(random_bytes(8)).'.'.$ext;$dir=__DIR__.'/finance-uploads';if(!is_dir($dir))mkdir($dir,0700,true);$path=$dir.'/'.$name;if(!move_uploaded_file($f['tmp_name'],$path)){http_response_code(500);header('Content-Type: application/json');echo json_encode(['ok'=>false,'error'=>'Beleg konnte nicht gespeichert werden.']);exit;}
  $old=trim((string)$e['receipt_path']);if($old!==''&&is_file(__DIR__.'/'.$old))@unlink(__DIR__.'/'.$old);$rel='finance-uploads/'.$name;$sha=hash_file('sha256',$path);$db->prepare('UPDATE finance_expenses SET receipt_path=?,receipt_name=?,receipt_sha256=?,updated_at=NOW() WHERE id=?')->execute([$rel,$orig,$sha,$id]);rh24_audit('finance_receipt_upload','finance_expense',$id,['name'=>$orig,'sha256'=>$sha]);header('Content-Type: application/json; charset=utf-8');echo json_encode(['ok'=>true,'name'=>$orig,'sha256'=>$sha,'finance'=>rh24_finance_data()],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;
}
$rel=trim((string)$e['receipt_path']);if($rel===''||!is_file(__DIR__.'/'.$rel)){http_response_code(404);exit('Kein Beleg hinterlegt.');}$path=__DIR__.'/'.$rel;$ext=strtolower(pathinfo($path,PATHINFO_EXTENSION));$map=['pdf'=>'application/pdf','jpg'=>'image/jpeg','jpeg'=>'image/jpeg','png'=>'image/png','webp'=>'image/webp','xml'=>'application/xml'];header('Content-Type: '.$map[$ext]);header('Content-Length: '.filesize($path));header('Content-Disposition: inline; filename="'.preg_replace('/[\r\n"]+/','',(string)$e['receipt_name']).'"');header('Cache-Control: private, no-store');readfile($path);
