<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
rh24_require_login();
header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');
function fout(array $d,int $s=200): never {http_response_code($s);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function fbody(): array {$d=json_decode(file_get_contents('php://input')?:'{}',true);return is_array($d)?$d:[];}
function fdate(string $v,bool $required=true): ?string {$v=trim($v);if($v===''){if($required)throw new InvalidArgumentException('Datum ist erforderlich.');return null;}$t=strtotime($v);if(!$t)throw new InvalidArgumentException('Datum ist ungültig.');return date('Y-m-d',$t);}
function fstr(mixed $v,int $max=500): string {$s=trim((string)$v);return function_exists('mb_substr')?mb_substr($s,0,$max):substr($s,0,$max);}
function fmoney(mixed $v): float {return round((float)str_replace(',','.',(string)$v),2);}
function fbool(mixed $v): int {return filter_var($v,FILTER_VALIDATE_BOOL)?1:0;}
function fassert_edit(): void {if(!rh24_can('edit_finance'))fout(['ok'=>false,'error'=>'Keine Berechtigung zum Bearbeiten der Buchhaltung.'],403);}
function frefresh(array $extra=[]): never {fout(['ok'=>true,'finance'=>rh24_finance_data()]+$extra);}

try{
  if(!rh24_can('view_finance'))fout(['ok'=>false,'error'=>'Keine Berechtigung für Finanzen & Buchhaltung.'],403);
  $db=rh24_db();
  $health=rh24_finance_ensure_ready($db);
  if($_SERVER['REQUEST_METHOD']==='GET')fout(['ok'=>true,'finance'=>rh24_finance_data(),'finance_health'=>$health,'csrf'=>rh24_csrf(),'server_time'=>date('c'),'release'=>'91.1']);
  if($_SERVER['REQUEST_METHOD']!=='POST')fout(['ok'=>false,'error'=>'Methode nicht erlaubt.'],405);
  $data=fbody();rh24_verify_csrf($_SERVER['HTTP_X_CSRF_TOKEN']??($data['csrf']??null));$action=(string)($data['action']??'');
}catch(Throwable $e){
  error_log('RH24 Finance API V91.1 startup failed: '.$e->getMessage());
  fout(['ok'=>false,'error'=>$e->getMessage(),'code'=>'FINANCE_INIT_FAILED','release'=>'91.1'],500);
}

try{
  if($action==='supplier_save'){
    fassert_edit();$id=fstr($data['id']??'',50);$name=fstr($data['name']??'',220);if($name==='')throw new InvalidArgumentException('Lieferantenname ist erforderlich.');$isNew=$id==='';if($isNew)$id=rh24_random_id('SUP-');
    $no=fstr($data['supplier_no']??'',40);if($no==='')$no=rh24_finance_next_no('finance_next_supplier_no','K');$email=strtolower(fstr($data['email']??'',190));if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))throw new InvalidArgumentException('E-Mail-Adresse ist ungültig.');
    $vals=[$no,$name,fstr($data['contact_name']??'',180),$email,fstr($data['phone']??'',80),fstr($data['street']??'',190),fstr($data['zip']??'',20),fstr($data['city']??'',120),fstr($data['country']??'Deutschland',80),fstr($data['iban']??'',64),fstr($data['bic']??'',32),fstr($data['vat_id']??'',60),fstr($data['tax_no']??'',80),max(0,min(365,(int)($data['payment_terms_days']??14))),fstr($data['notes']??'',2000),fbool($data['active']??true)];
    if($isNew)$db->prepare("INSERT INTO finance_suppliers(id,supplier_no,name,contact_name,email,phone,street,zip,city,country,iban,bic,vat_id,tax_no,payment_terms_days,notes,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())")->execute([$id,...$vals]);
    else{$q=$db->prepare('SELECT id FROM finance_suppliers WHERE id=?');$q->execute([$id]);if(!$q->fetchColumn())throw new RuntimeException('Lieferant nicht gefunden.');$db->prepare("UPDATE finance_suppliers SET supplier_no=?,name=?,contact_name=?,email=?,phone=?,street=?,zip=?,city=?,country=?,iban=?,bic=?,vat_id=?,tax_no=?,payment_terms_days=?,notes=?,active=?,updated_at=NOW() WHERE id=?")->execute([...$vals,$id]);}
    rh24_audit('finance_supplier_save','finance_supplier',$id,['supplier_no'=>$no,'name'=>$name]);frefresh();
  }

  if($action==='expense_save'){
    fassert_edit();$id=fstr($data['id']??'',60);$existing=null;if($id!==''){$q=$db->prepare('SELECT * FROM finance_expenses WHERE id=?');$q->execute([$id]);$existing=$q->fetch();if(!$existing)throw new RuntimeException('Beleg nicht gefunden.');rh24_finance_assert_period_open((string)$existing['invoice_date']);}
    $invoiceDate=fdate((string)($data['invoice_date']??''));rh24_finance_assert_period_open($invoiceDate);$supplier=fstr($data['supplier_id']??'',50);$terms=(int)rh24_setting_get('finance_default_payment_days','14');if($supplier!==''){$q=$db->prepare('SELECT payment_terms_days FROM finance_suppliers WHERE id=?');$q->execute([$supplier]);$x=$q->fetchColumn();if($x!==false)$terms=(int)$x;}
    $due=fdate((string)($data['due_date']??''),false)?:date('Y-m-d',strtotime($invoiceDate.' +'.$terms.' days'));$gross=fmoney($data['gross_amount']??0);if($gross<=0)throw new InvalidArgumentException('Bruttobetrag muss größer als 0 sein.');$rate=max(0,min(100,(float)str_replace(',','.',(string)($data['tax_rate']??19))));$net=isset($data['net_amount'])&&fmoney($data['net_amount'])>0?fmoney($data['net_amount']):round($gross/(1+$rate/100),2);$tax=round($gross-$net,2);if(abs(($net+$tax)-$gross)>0.02)throw new InvalidArgumentException('Netto, Steuer und Brutto sind nicht plausibel.');
    $status=in_array((string)($data['payment_status']??'open'),['open','paid','partial'],true)?(string)$data['payment_status']:'open';$paid=$status==='paid'?(fdate((string)($data['paid_at']??date('Y-m-d')),false)?:date('Y-m-d')):null;$voucher=$existing?(string)$existing['voucher_no']:rh24_finance_next_no('finance_next_voucher_no','BE');if($id==='')$id=rh24_random_id('EXP-');
    $vals=[$supplier!==''?$supplier:null,fstr($data['invoice_no']??'',100),$invoiceDate,$due,$gross,$net,$tax,$rate,fstr($data['account_code']??'',30),fstr($data['category']??'',120),(($cc=fstr($data['cost_center_id']??'',50))!==''?$cc:null),fstr($data['project']??'',160),$status,$paid,fstr($data['payment_method']??'',60),fstr($data['notes']??'',3000)];
    if(!$existing)$db->prepare("INSERT INTO finance_expenses(id,voucher_no,supplier_id,invoice_no,invoice_date,due_date,gross_amount,net_amount,tax_amount,tax_rate,account_code,category,cost_center_id,project,payment_status,paid_at,payment_method,notes,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())")->execute([$id,$voucher,...$vals,rh24_user_id()]);
    else$db->prepare("UPDATE finance_expenses SET supplier_id=?,invoice_no=?,invoice_date=?,due_date=?,gross_amount=?,net_amount=?,tax_amount=?,tax_rate=?,account_code=?,category=?,cost_center_id=?,project=?,payment_status=?,paid_at=?,payment_method=?,notes=?,updated_at=NOW() WHERE id=? AND record_status='active'")->execute([...$vals,$id]);
    rh24_audit('finance_expense_save','finance_expense',$id,['voucher_no'=>$voucher,'gross'=>$gross,'status'=>$status]);frefresh(['expense_id'=>$id]);
  }

  if($action==='expense_mark_paid'){
    fassert_edit();$id=fstr($data['id']??'',60);$q=$db->prepare("SELECT * FROM finance_expenses WHERE id=? AND record_status='active'");$q->execute([$id]);$e=$q->fetch();if(!$e)throw new RuntimeException('Beleg nicht gefunden.');rh24_finance_assert_period_open((string)$e['invoice_date']);$paid=fdate((string)($data['paid_at']??date('Y-m-d')));$db->prepare("UPDATE finance_expenses SET payment_status='paid',paid_at=?,payment_method=?,updated_at=NOW() WHERE id=?")->execute([$paid,fstr($data['payment_method']??'Bank',60),$id]);rh24_audit('finance_expense_paid','finance_expense',$id,['paid_at'=>$paid]);frefresh();
  }

  if($action==='expense_cancel'){
    fassert_edit();$id=fstr($data['id']??'',60);$reason=fstr($data['reason']??'',500);if((function_exists('mb_strlen')?mb_strlen($reason):strlen($reason))<5)throw new InvalidArgumentException('Ein nachvollziehbarer Stornogrund ist erforderlich.');$q=$db->prepare("SELECT * FROM finance_expenses WHERE id=? AND record_status='active'");$q->execute([$id]);$e=$q->fetch();if(!$e)throw new RuntimeException('Beleg nicht gefunden oder bereits storniert.');rh24_finance_assert_period_open((string)$e['invoice_date']);$db->prepare("UPDATE finance_expenses SET record_status='cancelled',cancelled_at=NOW(),cancelled_by=?,cancel_reason=?,updated_at=NOW() WHERE id=?")->execute([rh24_user_id(),$reason,$id]);if((string)($e['source_module']??'')==='triplog'&&!empty($e['source_ref'])){try{$db->prepare("UPDATE trip_receipts SET finance_status='cancelled',finance_error='Buchhaltungsbeleg wurde in Finanzen storniert.',updated_at=NOW() WHERE id=?")->execute([(string)$e['source_ref']]);}catch(Throwable $x){}}rh24_audit('finance_expense_cancel','finance_expense',$id,['reason'=>$reason]);frefresh();
  }

  if($action==='bank_account_save'){
    fassert_edit();$id=fstr($data['id']??'',50);$name=fstr($data['name']??'',180);if($name==='')throw new InvalidArgumentException('Kontobezeichnung ist erforderlich.');if($id==='')$id=rh24_random_id('BANK-');$q=$db->prepare('SELECT id FROM finance_bank_accounts WHERE id=?');$q->execute([$id]);$exists=(bool)$q->fetchColumn();$vals=[$name,fstr($data['bank_name']??'',180),fstr($data['iban']??'',64),fstr($data['bic']??'',32),fstr($data['account_type']??'bank',30),fmoney($data['opening_balance']??0),fbool($data['active']??true)];if($exists)$db->prepare("UPDATE finance_bank_accounts SET name=?,bank_name=?,iban=?,bic=?,account_type=?,opening_balance=?,active=?,updated_at=NOW() WHERE id=?")->execute([...$vals,$id]);else$db->prepare("INSERT INTO finance_bank_accounts(id,name,bank_name,iban,bic,account_type,opening_balance,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,NOW(),NOW())")->execute([$id,...$vals]);rh24_audit('finance_bank_account_save','finance_bank_account',$id,['name'=>$name]);frefresh();
  }

  if($action==='transaction_save'){
    fassert_edit();$id=fstr($data['id']??'',60);$existing=null;if($id!==''){$q=$db->prepare('SELECT * FROM finance_transactions WHERE id=?');$q->execute([$id]);$existing=$q->fetch();if(!$existing)throw new RuntimeException('Kontoumsatz nicht gefunden.');rh24_finance_assert_period_open((string)$existing['booking_date']);}
    $date=fdate((string)($data['booking_date']??''));rh24_finance_assert_period_open($date);$amount=fmoney($data['amount']??0);if(abs($amount)<0.01)throw new InvalidArgumentException('Betrag darf nicht 0 sein.');$rate=max(0,min(100,(float)str_replace(',','.',(string)($data['tax_rate']??0))));$gross=abs($amount);$net=$rate>0?round($gross/(1+$rate/100),2):$gross;$tax=round($gross-$net,2);if($id==='')$id=rh24_random_id('TX-');
    $vals=[(($b=fstr($data['bank_account_id']??'',50))!==''?$b:null),$date,fdate((string)($data['value_date']??''),false),$amount,fstr($data['currency']??'EUR',3),fstr($data['transaction_type']??'bank',30),fstr($data['counterparty']??'',220),fstr($data['iban']??'',64),fstr($data['purpose']??'',700),fstr($data['reference']??'',180),fstr($data['status']??'unassigned',30),(($o=fstr($data['order_no']??'',80))!==''?$o:null),(($doc=fstr($data['document_id']??'',80))!==''?$doc:null),(($sup=fstr($data['supplier_id']??'',50))!==''?$sup:null),fstr($data['category']??'',120),fstr($data['ledger_account']??'',30),$rate,$net,$tax,(($cc=fstr($data['cost_center_id']??'',50))!==''?$cc:null),fstr($data['project']??'',160),fstr($data['notes']??'',700),fstr($data['source']??'manual',30)];
    if($existing)$db->prepare("UPDATE finance_transactions SET bank_account_id=?,booking_date=?,value_date=?,amount=?,currency=?,transaction_type=?,counterparty=?,iban=?,purpose=?,reference=?,status=?,order_no=?,document_id=?,supplier_id=?,category=?,ledger_account=?,tax_rate=?,net_amount=?,tax_amount=?,cost_center_id=?,project=?,notes=?,source=?,updated_at=NOW() WHERE id=?")->execute([...$vals,$id]);
    else$db->prepare("INSERT INTO finance_transactions(id,bank_account_id,booking_date,value_date,amount,currency,transaction_type,counterparty,iban,purpose,reference,status,order_no,document_id,supplier_id,category,ledger_account,tax_rate,net_amount,tax_amount,cost_center_id,project,notes,source,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())")->execute([$id,...$vals,rh24_user_id()]);
    rh24_audit('finance_transaction_save','finance_transaction',$id,['amount'=>$amount,'booking_date'=>$date]);frefresh();
  }

  if($action==='bank_import'){
    fassert_edit();$account=fstr($data['bank_account_id']??'',50);if($account==='')throw new InvalidArgumentException('Bankkonto auswählen.');$rows=is_array($data['rows']??null)?$data['rows']:[];if(!$rows)throw new InvalidArgumentException('Keine Importzeilen erhalten.');if(count($rows)>1000)throw new InvalidArgumentException('Maximal 1.000 Buchungen pro Import.');$ins=$db->prepare("INSERT IGNORE INTO finance_transactions(id,bank_account_id,booking_date,value_date,amount,currency,transaction_type,counterparty,iban,purpose,reference,external_ref,status,source,created_by,created_at,updated_at) VALUES(?,?,?,?,?,'EUR','bank',?,?,?,?,?,'unassigned','csv',?,NOW(),NOW())");$added=0;$skipped=0;
    foreach($rows as $idx=>$r){if(!is_array($r))continue;$date=fdate((string)($r['booking_date']??''),false);$amount=fmoney($r['amount']??0);if(!$date||abs($amount)<0.01){$skipped++;continue;}rh24_finance_assert_period_open($date);$counter=fstr($r['counterparty']??'',220);$iban=fstr($r['iban']??'',64);$purpose=fstr($r['purpose']??'',700);$ref=fstr($r['reference']??'',180);$external=fstr($r['external_ref']??'',100);if($external==='')$external=hash('sha256',implode('|',[$account,$date,number_format($amount,2,'.',''),$counter,$iban,$purpose,$ref]));$before=$db->query('SELECT ROW_COUNT()')->fetchColumn();$ins->execute([rh24_random_id('TX-'),$account,$date,fdate((string)($r['value_date']??''),false),$amount,$counter,$iban,$purpose,$ref,$external,rh24_user_id()]);if($ins->rowCount())$added++;else$skipped++;}
    rh24_audit('finance_bank_import','finance_transaction','',['added'=>$added,'skipped'=>$skipped,'account'=>$account]);frefresh(['imported'=>$added,'skipped'=>$skipped]);
  }

  if($action==='transaction_match'){
    fassert_edit();$id=fstr($data['id']??'',60);$order=fstr($data['order_no']??'',80);if($order==='')throw new InvalidArgumentException('Bestellung auswählen.');$q=$db->prepare('SELECT * FROM finance_transactions WHERE id=?');$q->execute([$id]);$tx=$q->fetch();if(!$tx)throw new RuntimeException('Kontoumsatz nicht gefunden.');if((float)$tx['amount']<=0)throw new InvalidArgumentException('Nur Zahlungseingänge können Kundenforderungen ausgleichen.');rh24_finance_assert_period_open((string)$tx['booking_date']);$oq=$db->prepare("SELECT totals_json,payment_status,status FROM orders WHERE order_no=?");$oq->execute([$order]);$o=$oq->fetch();if(!$o)throw new RuntimeException('Bestellung nicht gefunden.');$tot=rh24_json_decode($o['totals_json']??'{}',[]);$gross=(float)($tot['gross']??0);$mq=$db->prepare('SELECT fees FROM finance_dunning WHERE order_no=?');$mq->execute([$order]);$gross+=(float)($mq->fetchColumn()?:0);if(abs($gross-(float)$tx['amount'])>0.02&&!fbool($data['force']??false))throw new InvalidArgumentException('Betrag passt nicht exakt zur offenen Forderung. Manuelle Zuordnung kann mit Freigabe erzwungen werden.');$dq=$db->prepare("SELECT id FROM documents WHERE order_no=? AND document_type='invoice' ORDER BY created_at DESC LIMIT 1");$dq->execute([$order]);$doc=$dq->fetchColumn()?:null;$db->beginTransaction();try{$db->prepare("UPDATE finance_transactions SET status='matched',order_no=?,document_id=?,updated_at=NOW() WHERE id=?")->execute([$order,$doc,$id]);$newStatus=$o['status']==='payment_pending'?'paid':$o['status'];$db->prepare("UPDATE orders SET payment_status='paid',status=?,status_label=?,updated_at=NOW() WHERE order_no=?")->execute([$newStatus,rh24_order_statuses()[$newStatus]??$newStatus,$order]);$db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}rh24_audit('finance_transaction_match','finance_transaction',$id,['order_no'=>$order,'amount'=>(float)$tx['amount']]);frefresh();
  }

  if($action==='auto_match'){
    fassert_edit();$sales=rh24_finance_open_receivables(rh24_finance_sales_rows());$byAmount=[];foreach($sales as $s)$byAmount[number_format((float)$s['gross']+(float)($s['dunning_fees']??0),2,'.','')][]=$s;$txs=$db->query("SELECT * FROM finance_transactions WHERE status='unassigned' AND amount>0 ORDER BY booking_date")->fetchAll();$matched=0;
    foreach($txs as $tx){$target=null;$purpose=(string)$tx['purpose'];foreach($sales as $s){if(str_contains($purpose,(string)$s['order_no'])){$target=$s;break;}}if(!$target){$list=$byAmount[number_format((float)$tx['amount'],2,'.','')]??[];if(count($list)===1)$target=$list[0];}if(!$target)continue;$order=(string)$target['order_no'];$dq=$db->prepare("SELECT id FROM documents WHERE order_no=? AND document_type='invoice' ORDER BY created_at DESC LIMIT 1");$dq->execute([$order]);$doc=$dq->fetchColumn()?:null;$db->beginTransaction();try{$db->prepare("UPDATE finance_transactions SET status='matched',order_no=?,document_id=?,updated_at=NOW() WHERE id=? AND status='unassigned'")->execute([$order,$doc,$tx['id']]);$db->prepare("UPDATE orders SET payment_status='paid',status=CASE WHEN status='payment_pending' THEN 'paid' ELSE status END,status_label=CASE WHEN status='payment_pending' THEN 'Bezahlt' ELSE status_label END,updated_at=NOW() WHERE order_no=?")->execute([$order]);$db->commit();$matched++;}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}}
    rh24_audit('finance_auto_match','finance_transaction','',['matched'=>$matched]);frefresh(['matched'=>$matched]);
  }

  if($action==='cash_save'){
    fassert_edit();$date=fdate((string)($data['entry_date']??''));rh24_finance_assert_period_open($date);$type=(string)($data['entry_type']??'expense');if(!in_array($type,['income','expense','deposit','withdrawal'],true))throw new InvalidArgumentException('Ungültige Kassenbewegung.');$amount=abs(fmoney($data['amount']??0));if($amount<=0)throw new InvalidArgumentException('Kassenbetrag muss größer als 0 sein.');$desc=fstr($data['description']??'',500);if($desc==='')throw new InvalidArgumentException('Buchungstext ist erforderlich.');$rate=max(0,min(100,(float)str_replace(',','.',(string)($data['tax_rate']??0))));$tax=$rate>0?round($amount-$amount/(1+$rate/100),2):0.0;$id=rh24_random_id('CASH-');$no=rh24_finance_next_no('finance_next_cash_no','KA');$db->prepare("INSERT INTO finance_cash_entries(id,entry_no,entry_date,entry_type,amount,description,receipt_no,account_code,tax_rate,tax_amount,cost_center_id,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,NOW())")->execute([$id,$no,$date,$type,$amount,$desc,fstr($data['receipt_no']??'',100),fstr($data['account_code']??'',30),$rate,$tax,(($cc=fstr($data['cost_center_id']??'',50))!==''?$cc:null),rh24_user_id()]);rh24_audit('finance_cash_save','finance_cash',$id,['entry_no'=>$no,'type'=>$type,'amount'=>$amount]);frefresh();
  }

  if($action==='cost_center_save'){
    fassert_edit();$id=fstr($data['id']??'',50);$code=fstr($data['code']??'',30);$name=fstr($data['name']??'',180);if($code===''||$name==='')throw new InvalidArgumentException('Kostenstellencode und Name sind erforderlich.');if($id==='')$id=rh24_random_id('CC-');$q=$db->prepare('SELECT id FROM finance_cost_centers WHERE id=?');$q->execute([$id]);$exists=(bool)$q->fetchColumn();$vals=[$code,$name,fstr($data['description']??'',500),fbool($data['active']??true)];if($exists)$db->prepare("UPDATE finance_cost_centers SET code=?,name=?,description=?,active=?,updated_at=NOW() WHERE id=?")->execute([...$vals,$id]);else$db->prepare("INSERT INTO finance_cost_centers(id,code,name,description,active,created_at,updated_at) VALUES(?,?,?,?,?,NOW(),NOW())")->execute([$id,...$vals]);rh24_audit('finance_cost_center_save','finance_cost_center',$id,['code'=>$code,'name'=>$name]);frefresh();
  }

  if($action==='account_save'){
    fassert_edit();$framework=in_array((string)($data['framework']??'SKR03'),['SKR03','SKR04','EIGEN'],true)?(string)$data['framework']:'EIGEN';$code=fstr($data['code']??'',20);$name=fstr($data['name']??'',220);if($code===''||$name==='')throw new InvalidArgumentException('Kontonummer und Bezeichnung sind erforderlich.');$id=fstr($data['id']??'',60);if($id==='')$id='ACC-'.strtoupper(bin2hex(random_bytes(5)));$q=$db->prepare('SELECT id FROM finance_accounts WHERE id=?');$q->execute([$id]);$exists=(bool)$q->fetchColumn();$vals=[$framework,$code,$name,fstr($data['account_type']??'expense',40),max(0,min(100,(float)($data['tax_rate']??0))),fbool($data['active']??true)];if($exists)$db->prepare("UPDATE finance_accounts SET framework=?,code=?,name=?,account_type=?,tax_rate=?,active=?,updated_at=NOW() WHERE id=?")->execute([...$vals,$id]);else$db->prepare("INSERT INTO finance_accounts(id,framework,code,name,account_type,tax_rate,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,NOW(),NOW())")->execute([$id,...$vals]);rh24_audit('finance_account_save','finance_account',$id,['framework'=>$framework,'code'=>$code]);frefresh();
  }

  if($action==='asset_save'){
    fassert_edit();$id=fstr($data['id']??'',60);$existing=null;if($id!==''){$q=$db->prepare('SELECT * FROM finance_assets WHERE id=?');$q->execute([$id]);$existing=$q->fetch();if(!$existing)throw new RuntimeException('Anlagegut nicht gefunden.');rh24_finance_assert_period_open((string)$existing['acquisition_date']);}$date=fdate((string)($data['acquisition_date']??''));rh24_finance_assert_period_open($date);$name=fstr($data['name']??'',220);if($name==='')throw new InvalidArgumentException('Bezeichnung des Anlageguts ist erforderlich.');$price=abs(fmoney($data['purchase_price']??0));if($price<=0)throw new InvalidArgumentException('Anschaffungswert muss größer als 0 sein.');$life=max(1,min(600,(int)($data['useful_life_months']??36)));$res=max(0,min($price,fmoney($data['residual_value']??0)));$assetNo=$existing?(string)$existing['asset_no']:rh24_finance_next_no('finance_next_asset_no','AN');if($id==='')$id=rh24_random_id('ASSET-');$vals=[$name,fstr($data['category']??'',120),$date,$price,$life,'linear',$res,fstr($data['account_code']??'',30),(($cc=fstr($data['cost_center_id']??'',50))!==''?$cc:null),fdate((string)($data['disposed_at']??''),false),abs(fmoney($data['disposal_value']??0)),fstr($data['notes']??'',2000),fbool($data['active']??true)];if($existing)$db->prepare("UPDATE finance_assets SET name=?,category=?,acquisition_date=?,purchase_price=?,useful_life_months=?,depreciation_method=?,residual_value=?,account_code=?,cost_center_id=?,disposed_at=?,disposal_value=?,notes=?,active=?,updated_at=NOW() WHERE id=?")->execute([...$vals,$id]);else$db->prepare("INSERT INTO finance_assets(id,asset_no,name,category,acquisition_date,purchase_price,useful_life_months,depreciation_method,residual_value,account_code,cost_center_id,disposed_at,disposal_value,notes,active,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())")->execute([$id,$assetNo,...$vals,rh24_user_id()]);rh24_audit('finance_asset_save','finance_asset',$id,['asset_no'=>$assetNo,'price'=>$price]);frefresh();
  }

  if($action==='recurring_save'){
    fassert_edit();$id=fstr($data['id']??'',60);$title=fstr($data['title']??'',220);if($title==='')throw new InvalidArgumentException('Bezeichnung ist erforderlich.');$direction=in_array((string)($data['direction']??'expense'),['expense','income'],true)?(string)$data['direction']:'expense';$amount=abs(fmoney($data['amount']??0));if($amount<=0)throw new InvalidArgumentException('Betrag muss größer als 0 sein.');$interval=in_array((string)($data['interval_type']??'monthly'),['monthly','quarterly','yearly'],true)?(string)$data['interval_type']:'monthly';$next=fdate((string)($data['next_due_date']??''));if($id==='')$id=rh24_random_id('REC-');$q=$db->prepare('SELECT id FROM finance_recurring WHERE id=?');$q->execute([$id]);$exists=(bool)$q->fetchColumn();$vals=[$title,$direction,$amount,max(0,min(100,(float)($data['tax_rate']??19))),$interval,$next,(($sup=fstr($data['supplier_id']??'',50))!==''?$sup:null),fstr($data['category']??'',120),fstr($data['account_code']??'',30),(($cc=fstr($data['cost_center_id']??'',50))!==''?$cc:null),fstr($data['notes']??'',500),fbool($data['active']??true)];if($exists)$db->prepare("UPDATE finance_recurring SET title=?,direction=?,amount=?,tax_rate=?,interval_type=?,next_due_date=?,supplier_id=?,category=?,account_code=?,cost_center_id=?,notes=?,active=?,updated_at=NOW() WHERE id=?")->execute([...$vals,$id]);else$db->prepare("INSERT INTO finance_recurring(id,title,direction,amount,tax_rate,interval_type,next_due_date,supplier_id,category,account_code,cost_center_id,notes,active,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())")->execute([$id,...$vals,rh24_user_id()]);rh24_audit('finance_recurring_save','finance_recurring',$id,['title'=>$title,'amount'=>$amount]);frefresh();
  }

  if($action==='budget_save'){
    fassert_edit();$id=fstr($data['id']??'',60);$period=fstr($data['period']??date('Y-m'),7);if(!preg_match('/^20\d{2}-(0[1-9]|1[0-2])$/',$period))throw new InvalidArgumentException('Budgetperiode ist ungültig.');$amount=abs(fmoney($data['amount']??0));if($amount<=0)throw new InvalidArgumentException('Budget muss größer als 0 sein.');if($id==='')$id=rh24_random_id('BUD-');$q=$db->prepare('SELECT id FROM finance_budgets WHERE id=?');$q->execute([$id]);$exists=(bool)$q->fetchColumn();$vals=[$period,(($cc=fstr($data['cost_center_id']??'',50))!==''?$cc:null),fstr($data['category']??'',120),$amount,fstr($data['notes']??'',500)];if($exists)$db->prepare("UPDATE finance_budgets SET period=?,cost_center_id=?,category=?,amount=?,notes=?,updated_at=NOW() WHERE id=?")->execute([...$vals,$id]);else$db->prepare("INSERT INTO finance_budgets(id,period,cost_center_id,category,amount,notes,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,NOW(),NOW())")->execute([$id,...$vals,rh24_user_id()]);rh24_audit('finance_budget_save','finance_budget',$id,['period'=>$period,'amount'=>$amount]);frefresh();
  }

  if($action==='dunning_update'){
    fassert_edit();$order=fstr($data['order_no']??'',80);if($order==='')throw new InvalidArgumentException('Bestellung fehlt.');$level=max(0,min(3,(int)($data['dunning_level']??0)));$due=fdate((string)($data['next_due_date']??''),false);$fees=max(0,fmoney($data['fees']??0));$interest=max(0,min(100,(float)str_replace(',','.',(string)($data['interest_rate']??0))));$blocked=fbool($data['blocked']??false);$notes=fstr($data['notes']??'',500);$db->prepare("INSERT INTO finance_dunning(order_no,dunning_level,last_dunned_at,next_due_date,fees,interest_rate,blocked,notes,updated_by,updated_at) VALUES(?,?,CASE WHEN ?>0 THEN NOW() ELSE NULL END,?,?,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE last_dunned_at=CASE WHEN VALUES(dunning_level)>0 AND VALUES(dunning_level)<>dunning_level THEN NOW() ELSE last_dunned_at END,dunning_level=VALUES(dunning_level),next_due_date=VALUES(next_due_date),fees=VALUES(fees),interest_rate=VALUES(interest_rate),blocked=VALUES(blocked),notes=VALUES(notes),updated_by=VALUES(updated_by),updated_at=NOW()")->execute([$order,$level,$level,$due,$fees,$interest,$blocked,$notes,rh24_user_id()]);rh24_audit('finance_dunning_update','finance_dunning',$order,['level'=>$level,'fees'=>$fees,'due'=>$due]);frefresh();
  }

  if($action==='dunning_email'){
    fassert_edit();$order=fstr($data['order_no']??'',80);if($order==='')throw new InvalidArgumentException('Bestellung fehlt.');$r=rh24_finance_dunning_record($order);$email=(string)($r['order']['customer']['email']??'');if(!filter_var($email,FILTER_VALIDATE_EMAIL))throw new InvalidArgumentException('Beim Kunden ist keine gültige E-Mail-Adresse hinterlegt.');$level=max(1,(int)($r['dunning']['dunning_level']??1));$title=rh24_finance_dunning_title($level);$pdf=rh24_finance_dunning_pdf($order);$name=htmlspecialchars((string)($r['order']['customer']['name']??'Kunde'),ENT_QUOTES,'UTF-8');$due=(string)($r['dunning']['next_due_date']??$r['open']['due_date']);$amount=(float)$r['open']['gross']+(float)($r['dunning']['fees']??0);$html='<p>Guten Tag '.$name.',</p><p>im Anhang erhalten Sie unsere <b>'.htmlspecialchars($title,ENT_QUOTES,'UTF-8').'</b> zur offenen Forderung <b>'.htmlspecialchars((string)($r['open']['document_no']?:$order),ENT_QUOTES,'UTF-8').'</b>.</p><p>Offener Gesamtbetrag: <b>'.number_format($amount,2,',','.').' €</b><br>Zahlungsfrist: <b>'.date('d.m.Y',strtotime($due)).'</b></p><p>Sollten Sie zwischenzeitlich gezahlt haben, betrachten Sie diese Nachricht bitte als gegenstandslos.</p><p>Räucherhaken24</p>';$ok=rh24_send_mail_attachments($email,$title.' · '.($r['open']['document_no']?:$order),$html,[['name'=>preg_replace('/[^A-Za-z0-9._-]+/','-',$title.'-'.$order).'.pdf','data'=>$pdf,'mime'=>'application/pdf']],'finance_dunning');if(!$ok)throw new RuntimeException('E-Mail konnte vom Server nicht versendet werden. Mail-Konfiguration prüfen.');$db->prepare('UPDATE finance_dunning SET last_dunned_at=NOW(),updated_by=?,updated_at=NOW() WHERE order_no=?')->execute([rh24_user_id(),$order]);rh24_audit('finance_dunning_email','finance_dunning',$order,['level'=>$level,'recipient'=>$email]);frefresh(['sent'=>true]);
  }

  if($action==='period_close'){
    fassert_edit();$period=fstr($data['period']??date('Y-m'),7);if(!preg_match('/^20\d{2}-(0[1-9]|1[0-2])$/',$period))throw new InvalidArgumentException('Periode ist ungültig.');$note=fstr($data['note']??'',500);$db->prepare("INSERT INTO finance_period_closings(period,status,note,closed_by,closed_at,updated_at) VALUES(?,'closed',?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE status='closed',note=VALUES(note),closed_by=VALUES(closed_by),closed_at=NOW(),updated_at=NOW()")->execute([$period,$note,rh24_user_id()]);$db->prepare("UPDATE finance_cash_entries SET locked_at=COALESCE(locked_at,NOW()) WHERE DATE_FORMAT(entry_date,'%Y-%m')=?")->execute([$period]);rh24_audit('finance_period_close','finance_period',$period,['note'=>$note]);frefresh();
  }

  if($action==='period_reopen'){
    if(!rh24_is_admin())fout(['ok'=>false,'error'=>'Nur Administratoren dürfen abgeschlossene Perioden wieder öffnen.'],403);$period=fstr($data['period']??'',7);$reason=fstr($data['reason']??'',500);if((function_exists('mb_strlen')?mb_strlen($reason):strlen($reason))<5)throw new InvalidArgumentException('Für das Wiederöffnen ist ein nachvollziehbarer Grund erforderlich.');$q=$db->prepare("SELECT status FROM finance_period_closings WHERE period=?");$q->execute([$period]);if((string)$q->fetchColumn()!=='closed')throw new RuntimeException('Periode ist nicht abgeschlossen.');$db->prepare("UPDATE finance_period_closings SET status='open',note=CONCAT(note,' | Wieder geöffnet: ',?),reopened_by=?,reopened_at=NOW(),updated_at=NOW() WHERE period=?")->execute([$reason,rh24_user_id(),$period]);rh24_audit('finance_period_reopen','finance_period',$period,['reason'=>$reason]);frefresh();
  }

  if($action==='settings_save'){
    if(!rh24_is_admin())fout(['ok'=>false,'error'=>'Nur Administratoren dürfen Buchhaltungseinstellungen ändern.'],403);$map=['finance_framework'=>['SKR03','SKR04','EIGEN'],'finance_accounting_method'=>['EÜR','Bilanz'],'finance_vat_mode'=>['Soll','Ist']];foreach($map as $k=>$allowed){$v=(string)($data[$k]??'');if(in_array($v,$allowed,true))rh24_setting_set($k,$v);}foreach(['finance_default_payment_days','finance_cash_opening_balance','finance_datev_consultant_no','finance_datev_client_no','finance_datev_account_length','finance_datev_dictation_code','finance_alert_liquidity_min'] as $k)if(array_key_exists($k,$data))rh24_setting_set($k,fstr($data[$k],80));rh24_audit('finance_settings_save','finance_settings','',['framework'=>$data['finance_framework']??null]);frefresh();
  }

  fout(['ok'=>false,'error'=>'Unbekannte Finanzaktion.'],400);
}catch(InvalidArgumentException $e){fout(['ok'=>false,'error'=>$e->getMessage()],422);}catch(Throwable $e){if($db->inTransaction())$db->rollBack();fout(['ok'=>false,'error'=>$e->getMessage()],500);}
