<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';rh24_require_permission('view_finance');
$type=strtolower(trim((string)($_GET['type']??'transactions')));$period=trim((string)($_GET['period']??date('Y-m')));if(!preg_match('/^20\d{2}-(0[1-9]|1[0-2])$/',$period))$period=date('Y-m');
$filename='RH24-'.$type.'-'.$period.'.csv';header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$filename.'"');header('Cache-Control: no-store');echo "\xEF\xBB\xBF";
$out=fopen('php://output','w');
function fc(array $row): void {global $out;fputcsv($out,$row,';', '"', '\\');}
function fde(float $v): string {return number_format($v,2,',','');}
function fperiod(string $date,string $p): bool {return substr($date,0,7)===$p;}
function fsale_payment_date(array $sale,array $transactions): string {$fallback=substr((string)($sale['updated_at']??$sale['created_at']??''),0,10);foreach($transactions as $tx){if(($tx['order_no']??'')===($sale['order_no']??'')&&($tx['status']??'')==='matched'&&(float)($tx['amount']??0)>0)return (string)$tx['booking_date'];}return $fallback;}
$data=rh24_finance_data();
if($type==='transactions'){fc(['Buchungsdatum','Valuta','Bankkonto','Betrag','Währung','Gegenpartei','IBAN','Verwendungszweck','Referenz','Status','Bestellung','Kategorie','Sachkonto','Kostenstelle','Projekt','Quelle']);foreach($data['transactions'] as $r)if(fperiod($r['booking_date'],$period))fc([$r['booking_date'],$r['value_date'],$r['bank_account_name']??'',fde($r['amount']),$r['currency'],$r['counterparty'],$r['iban'],$r['purpose'],$r['reference'],$r['status'],$r['order_no'],$r['category'],$r['ledger_account'],$r['cost_center_code']??'',$r['project'],$r['source']]);exit;}
if($type==='expenses'){fc(['Belegnr.','Lieferant','Lieferanten-Rechnungsnr.','Rechnungsdatum','Fällig','Brutto','Netto','Steuer','Steuersatz','Status','Bezahlt am','Kategorie','Sachkonto','Kostenstelle','Projekt','Belegdatei']);foreach($data['expenses'] as $r)if(fperiod($r['invoice_date'],$period))fc([$r['voucher_no'],$r['supplier_name']??'',$r['invoice_no'],$r['invoice_date'],$r['due_date'],fde($r['gross_amount']),fde($r['net_amount']),fde($r['tax_amount']),fde($r['tax_rate']),$r['record_status']==='cancelled'?'storniert':$r['payment_status'],$r['paid_at'],$r['category'],$r['account_code'],$r['cost_center_code']??'',$r['project'],$r['receipt_name']]);exit;}
if($type==='open-items'){fc(['Art','Beleg/Bestellung','Geschäftspartner','Datum','Fällig','Betrag','Überfällig Tage','Mahnstufe','Status']);foreach($data['open_receivables'] as $r)fc(['Forderung',$r['document_no']?:$r['order_no'],$r['customer_name'],$r['created_at'],$r['due_date'],fde($r['gross']+$r['dunning_fees']),$r['days_overdue'],$r['dunning_level'],'offen']);foreach($data['expenses'] as $r)if($r['payment_status']!=='paid'&&$r['record_status']==='active')fc(['Verbindlichkeit',$r['voucher_no'],$r['supplier_name']??'',$r['invoice_date'],$r['due_date'],fde($r['gross_amount']),'','',$r['payment_status']]);exit;}
if($type==='cashbook'){fc(['Kassen-Nr.','Datum','Art','Buchungstext','Belegnr.','Einnahme','Ausgabe','Steuer','Sachkonto','Kostenstelle','Erfasst von','Gesperrt']);$balance=(float)$data['config']['cash_opening_balance'];foreach(array_reverse($data['cash_entries']) as $r){if(!fperiod($r['entry_date'],$period))continue;$income=in_array($r['entry_type'],['income','deposit'],true)?$r['amount']:0;$expense=$income?0:$r['amount'];$balance+=$income-$expense;fc([$r['entry_no'],$r['entry_date'],$r['entry_type'],$r['description'],$r['receipt_no'],$income?fde($income):'',$expense?fde($expense):'',fde($r['tax_amount']),$r['account_code'],$r['cost_center_code']??'',$r['created_by_name']??'',$r['locked_at']?'ja':'nein']);}fc(['','','','','','Endbestand',fde($balance),'','','','','']);exit;}
if($type==='assets'){fc(['Anlagennr.','Bezeichnung','Kategorie','Anschaffungsdatum','Anschaffungswert','Nutzungsdauer Monate','Monats-AfA','kumulierte AfA','Restbuchwert','Sachkonto','Kostenstelle','Abgang']);foreach($data['assets'] as $r)fc([$r['asset_no'],$r['name'],$r['category'],$r['acquisition_date'],fde($r['purchase_price']),$r['useful_life_months'],fde($r['monthly_depreciation']),fde($r['accumulated_depreciation']),fde($r['book_value']),$r['account_code'],$r['cost_center_code']??'',$r['disposed_at']]);exit;}
if($type==='vat'){fc(['USt-Vorschau',$period]);fc(['Kennzahl','Beschreibung','Betrag']);$salesGross=$salesNet=$salesTax=$expGross=$expNet=$expTax=0.0;$vatMode=(string)($data['config']['vat_mode']??'Soll');foreach($data['sales'] as $r){if(($r['status']??'')==='cancelled')continue;$taxDate=$vatMode==='Ist'?fsale_payment_date($r,$data['transactions']):(string)$r['created_at'];if($vatMode==='Ist'&&($r['payment_status']??'')!=='paid')continue;if(!fperiod($taxDate,$period))continue;$salesGross+=$r['gross'];$salesNet+=$r['net'];$salesTax+=$r['tax'];}foreach($data['expenses'] as $r)if(fperiod($r['invoice_date'],$period)&&$r['record_status']==='active'){$expGross+=$r['gross_amount'];$expNet+=$r['net_amount'];$expTax+=$r['tax_amount'];}fc(['Umsatz netto','Aus erfassten Verkäufen',fde($salesNet)]);fc(['Umsatzsteuer','Aus erfassten Verkäufen',fde($salesTax)]);fc(['Vorsteuer','Aus erfassten Eingangsbelegen',fde($expTax)]);fc(['Zahllast-Vorschau','Umsatzsteuer minus Vorsteuer',fde($salesTax-$expTax)]);fc(['Hinweis','Arbeits-/Plausibilitätsauswertung; keine ERiC-Übermittlung','']);exit;}
if($type==='euer'){fc(['EÜR-Arbeitsauswertung',$period]);fc(['Art','Datum','Beleg','Geschäftspartner/Kategorie','Netto','Steuer','Brutto']);$income=0.0;$expense=0.0;foreach($data['sales'] as $r){if($r['payment_status']!=='paid')continue;$payDate=fsale_payment_date($r,$data['transactions']);if(!fperiod($payDate,$period))continue;$income+=$r['gross'];fc(['Einnahme',$payDate,$r['order_no'],$r['customer_name'],fde($r['net']),fde($r['tax']),fde($r['gross'])]);}foreach($data['expenses'] as $r){if($r['record_status']!=='active'||$r['payment_status']!=='paid'||empty($r['paid_at'])||!fperiod((string)$r['paid_at'],$period))continue;$expense+=$r['gross_amount'];fc(['Ausgabe',$r['paid_at'],$r['voucher_no'],$r['supplier_name']?:$r['category'],fde($r['net_amount']),fde($r['tax_amount']),fde($r['gross_amount'])]);}fc([]);fc(['Summe Einnahmen','','','','','',fde($income)]);fc(['Summe Ausgaben','','','','','',fde($expense)]);fc(['Überschuss','','','','','',fde($income-$expense)]);exit;}
if($type==='datev'){
  $cfg=$data['config'];$berater=preg_replace('/\D/','',(string)$cfg['datev_consultant_no']);$mandant=preg_replace('/\D/','',(string)$cfg['datev_client_no']);if($berater===''||$mandant===''){http_response_code(422);fclose($out);header('Content-Type: text/plain; charset=UTF-8');echo "DATEV-Export nicht möglich: Berater- und Mandantennummer zuerst in den Buchhaltungseinstellungen hinterlegen.";exit;}
  $framework=$cfg['framework']==='SKR04'?'04':'03';$accountLen=max(4,min(8,(int)$cfg['datev_account_length']));$from=str_replace('-','',$period.'-01');$to=str_replace('-','',date('Y-m-t',strtotime($period.'-01')));$fy=substr($period,0,4).'0101';$ts=date('YmdHis').'000';$dik=preg_replace('/[^A-Z]/','',strtoupper((string)$cfg['datev_dictation_code']));$dik=substr($dik?:'BH',0,2);
  fc(['EXTF',700,21,'Buchungsstapel',13,$ts,'','RE','','',$berater,$mandant,$fy,$accountLen,$from,$to,'RH24 '.$period,$dik,1,0,0,'EUR','','','','',$framework,'','','','RH24-V91']);
  fc(['Umsatz','Soll/Haben-Kennzeichen','WKZ Umsatz','Kurs','Basis-Umsatz','WKZ Basis-Umsatz','Konto','Gegenkonto (ohne BU-Schlüssel)','BU-Schlüssel','Belegdatum','Belegfeld 1','Belegfeld 2','Skonto','Buchungstext']);
  $receivable=$cfg['framework']==='SKR04'?'1200':'1400';$revenue=$cfg['framework']==='SKR04'?'4400':'8400';$payable=$cfg['framework']==='SKR04'?'3300':'1600';
  foreach($data['sales'] as $r)if(fperiod($r['created_at'],$period)&&($r['status']??'')!=='cancelled')fc([fde(abs($r['gross'])),'S','','','','',$receivable,$revenue,'',date('dm',strtotime($r['created_at'])),$r['order_no'],'','','Ausgangsrechnung '.mb_substr($r['customer_name'],0,40)]);
  foreach($data['expenses'] as $r)if(fperiod($r['invoice_date'],$period)&&$r['record_status']==='active'){$konto=preg_replace('/\D/','',(string)$r['account_code']);if($konto==='')$konto=$cfg['framework']==='SKR04'?'6800':'4900';fc([fde(abs($r['gross_amount'])),'S','','','','',$konto,$payable,'',date('dm',strtotime($r['invoice_date'])),$r['voucher_no'],$r['invoice_no'],'','Eingangsrechnung '.mb_substr((string)($r['supplier_name']?:$r['category']),0,40)]);}
  exit;
}
http_response_code(400);fc(['Fehler','Unbekannter Exporttyp']);
