<?php
declare(strict_types=1);

/* Räucherhaken24 Orgaboard V96.5 · Print & Media Studio Pro · 100 Vorlagen · Druckerkatalog · Medien/Vorrat */

function rh24_label_required_tables(): array {return ['label_printers','label_templates','label_jobs','label_job_items','label_media'];}
function rh24_label_schema_health(PDO $db): array {
    $missing=[];foreach(rh24_label_required_tables() as $t){try{$q=$db->prepare('SHOW TABLES LIKE ?');$q->execute([$t]);if(!$q->fetchColumn())$missing[]=$t;}catch(Throwable){$missing[]=$t;}}
    return ['ready'=>!$missing,'missing'=>$missing,'version'=>(int)rh24_setting_get('label_schema_version','0')];
}
function rh24_label_system_templates_v961(): array {
    return [
        ['id'=>'LT-PROD','name'=>'Produkt Standard 62 × 29','category'=>'product','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>1,'layout'=>['theme'=>'classic','accent'=>'#9b3e1c','show_name'=>true,'font_scale'=>1.0,'group'=>'Produkt & Shop','purpose'=>'Universelles Produktetikett mit Preis und Barcode.','show_logo'=>true,'show_price'=>true,'show_sku'=>true,'show_unit'=>true,'barcode'=>'code128','barcode_field'=>'barcode']],
        ['id'=>'LT-PROD-MIN','name'=>'Produkt Minimal 62 × 29','category'=>'product','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>1,'layout'=>['theme'=>'minimal','accent'=>'#2c2c2c','show_name'=>true,'font_scale'=>0.95,'group'=>'Produkt & Shop','purpose'=>'Reduziertes Etikett für klare Produktkennzeichnung.','show_logo'=>false,'show_price'=>true,'show_sku'=>true,'barcode'=>'code128','barcode_field'=>'sku']],
        ['id'=>'LT-PROD-PREM','name'=>'Produkt Premium 62 × 29','category'=>'product','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>1,'layout'=>['theme'=>'premium','accent'=>'#7a4a16','show_name'=>true,'font_scale'=>1.0,'group'=>'Produkt & Shop','purpose'=>'Hochwertige Präsentation für Premiumprodukte.','show_logo'=>true,'show_price'=>true,'show_sku'=>false,'show_unit'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'PREMIUM']],
        ['id'=>'LT-PROD-BC','name'=>'Produkt Barcode XL 62 × 29','category'=>'product','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'barcode','accent'=>'#111111','show_name'=>true,'font_scale'=>0.9,'group'=>'Produkt & Shop','purpose'=>'Großer scanfreundlicher Barcode mit Artikelname.','show_logo'=>false,'show_price'=>false,'show_sku'=>true,'barcode'=>'code128','barcode_field'=>'barcode','barcode_emphasis'=>true]],
        ['id'=>'LT-PROD-QR','name'=>'Produkt QR-Info 62 × 29','category'=>'product','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'qr','accent'=>'#215b55','show_name'=>true,'font_scale'=>1.0,'group'=>'Produkt & Shop','purpose'=>'QR-Code für digitale Informationen oder Produktseite.','show_logo'=>true,'show_price'=>true,'show_sku'=>false,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'QR INFO']],
        ['id'=>'LT-PROD-LONG','name'=>'Produkt Lang 62 × 40','category'=>'product','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'classic','accent'=>'#9b3e1c','show_name'=>true,'font_scale'=>1.05,'group'=>'Produkt & Shop','purpose'=>'Mehr Platz für längere Produktnamen und Zusatzinfos.','show_logo'=>true,'show_price'=>true,'show_sku'=>true,'show_unit'=>true,'show_category'=>true,'barcode'=>'code128','barcode_field'=>'barcode']],
        ['id'=>'LT-PROD-SQUARE','name'=>'Produkt Quadrat 62 × 62','category'=>'product','width_mm'=>62,'height_mm'=>62,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'premium','accent'=>'#4a3b2b','show_name'=>true,'font_scale'=>1.15,'group'=>'Produkt & Shop','purpose'=>'Großes quadratisches Produktetikett mit QR-Code.','show_logo'=>true,'show_price'=>true,'show_sku'=>true,'show_category'=>true,'barcode'=>'qrcode','barcode_field'=>'sku']],
        ['id'=>'LT-SMALL','name'=>'Produkt Mini 29 × 90','category'=>'product','width_mm'=>29,'height_mm'=>90,'orientation'=>'portrait','favorite'=>0,'layout'=>['theme'=>'vertical','accent'=>'#9b3e1c','show_name'=>true,'font_scale'=>0.88,'group'=>'Produkt & Shop','purpose'=>'Schmales Hochformat für kleine Verpackungen.','show_logo'=>false,'show_price'=>true,'show_sku'=>true,'barcode'=>'code128','barcode_field'=>'sku']],
        ['id'=>'LT-PROD-38','name'=>'Produkt 38 × 90','category'=>'product','width_mm'=>38,'height_mm'=>90,'orientation'=>'portrait','favorite'=>0,'layout'=>['theme'=>'vertical','accent'=>'#254665','show_name'=>true,'font_scale'=>0.9,'group'=>'Produkt & Shop','purpose'=>'Hochformat für Flaschen, Beutel und schmale Packungen.','show_logo'=>true,'show_price'=>true,'show_sku'=>true,'barcode'=>'code128','barcode_field'=>'barcode']],
        ['id'=>'LT-PROD-SHELF','name'=>'Regal Produktkarte 62 × 29','category'=>'product','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'shelf','accent'=>'#365a36','show_name'=>true,'font_scale'=>1.0,'group'=>'Produkt & Shop','purpose'=>'Produktname und Preis schnell am Regal erfassbar.','show_logo'=>false,'show_price'=>true,'show_sku'=>true,'barcode'=>'none','price_emphasis'=>true,'badge'=>'REGAL']],
        ['id'=>'LT-PROD-SKU','name'=>'Artikelnummer Fokus 62 × 29','category'=>'product','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'technical','accent'=>'#3e4b57','show_name'=>true,'font_scale'=>1.0,'group'=>'Produkt & Shop','purpose'=>'Artikelnummer und Code stehen im Vordergrund.','show_logo'=>false,'show_price'=>false,'show_sku'=>true,'barcode'=>'code128','barcode_field'=>'sku','badge'=>'ARTIKEL']],
        ['id'=>'LT-PROD-NOPRICE','name'=>'Produkt ohne Preis 62 × 29','category'=>'product','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'clean','accent'=>'#5b5149','show_name'=>true,'font_scale'=>1.0,'group'=>'Produkt & Shop','purpose'=>'Neutral für Ware ohne sichtbaren Verkaufspreis.','show_logo'=>true,'show_price'=>false,'show_sku'=>true,'show_unit'=>true,'barcode'=>'code128','barcode_field'=>'barcode']],
        ['id'=>'LT-PRICE','name'=>'Preis Standard 62 × 29','category'=>'price','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>1,'layout'=>['theme'=>'price','accent'=>'#b8441b','show_name'=>true,'font_scale'=>1.0,'group'=>'Preis & Verkauf','purpose'=>'Standard-Preisetikett mit EAN.','show_logo'=>true,'show_price'=>true,'show_sku'=>false,'price_emphasis'=>true,'barcode'=>'ean13','barcode_field'=>'barcode','show_vat'=>true]],
        ['id'=>'LT-PRICE-XXL','name'=>'Preis XXL 62 × 29','category'=>'price','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>1,'layout'=>['theme'=>'price_xl','accent'=>'#a32a16','show_name'=>true,'font_scale'=>1.18,'group'=>'Preis & Verkauf','purpose'=>'Sehr großer Preis für schnelle Lesbarkeit am Verkaufsplatz.','show_logo'=>false,'show_price'=>true,'show_sku'=>false,'price_emphasis'=>true,'barcode'=>'none','badge'=>'PREIS']],
        ['id'=>'LT-SALE','name'=>'Angebot SALE 62 × 29','category'=>'price','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>1,'layout'=>['theme'=>'sale','accent'=>'#c92219','show_name'=>true,'font_scale'=>1.0,'group'=>'Preis & Verkauf','purpose'=>'Auffälliges Aktionsetikett für Angebote.','show_logo'=>false,'show_price'=>true,'show_sku'=>false,'price_emphasis'=>true,'barcode'=>'code128','barcode_field'=>'barcode','badge'=>'ANGEBOT','show_vat'=>true]],
        ['id'=>'LT-ACTION','name'=>'Aktionspreis 62 × 29','category'=>'price','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'sale_outline','accent'=>'#d34b18','show_name'=>true,'font_scale'=>1.0,'group'=>'Preis & Verkauf','purpose'=>'Aktionskennzeichnung mit Preis und Artikelnummer.','show_logo'=>true,'show_price'=>true,'show_sku'=>true,'price_emphasis'=>true,'barcode'=>'none','badge'=>'AKTION']],
        ['id'=>'LT-B2B-PRICE','name'=>'Händlerpreis 62 × 29','category'=>'price','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'business','accent'=>'#2c4864','show_name'=>true,'font_scale'=>1.0,'group'=>'Preis & Verkauf','purpose'=>'Sachliches Preisetikett für B2B/Händlerware.','show_logo'=>true,'show_price'=>true,'show_sku'=>true,'barcode'=>'code128','barcode_field'=>'sku','badge'=>'B2B']],
        ['id'=>'LT-TIERPRICE','name'=>'Staffelpreis 62 × 40','category'=>'price','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'business','accent'=>'#4d5f73','show_name'=>true,'font_scale'=>1.0,'group'=>'Preis & Verkauf','purpose'=>'Größeres Format für Staffel- und Mengenpreise.','show_logo'=>true,'show_price'=>true,'show_sku'=>true,'show_note'=>true,'barcode'=>'code128','barcode_field'=>'sku','badge'=>'MENGE']],
        ['id'=>'LT-SHELF-PRICE','name'=>'Regalpreis kompakt 38 × 29','category'=>'price','width_mm'=>38,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'shelf','accent'=>'#2f5b38','show_name'=>true,'font_scale'=>0.82,'group'=>'Preis & Verkauf','purpose'=>'Kompakt für Regalschienen und kleine Preishalter.','show_logo'=>false,'show_price'=>true,'show_sku'=>false,'barcode'=>'none']],
        ['id'=>'LT-PRICE-QR','name'=>'Preis + QR 62 × 29','category'=>'price','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'qr','accent'=>'#285c5d','show_name'=>true,'font_scale'=>1.0,'group'=>'Preis & Verkauf','purpose'=>'Preis und QR-Code für Zusatzinformationen.','show_logo'=>false,'show_price'=>true,'show_sku'=>false,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'SCAN']],
        ['id'=>'LT-PRICE-EAN','name'=>'Preis + EAN 62 × 29','category'=>'price','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'barcode','accent'=>'#222222','show_name'=>true,'font_scale'=>1.0,'group'=>'Preis & Verkauf','purpose'=>'Preis kombiniert mit besonders gut scanbarem EAN.','show_logo'=>false,'show_price'=>true,'show_sku'=>false,'barcode'=>'ean13','barcode_field'=>'barcode','barcode_emphasis'=>true]],
        ['id'=>'LT-PRICE-ONLY','name'=>'Nur Preis 62 × 29','category'=>'price','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'price_only','accent'=>'#b52e1a','show_name'=>false,'font_scale'=>1.35,'group'=>'Preis & Verkauf','purpose'=>'Maximale Preiswirkung ohne weitere Informationen.','show_logo'=>false,'show_price'=>true,'barcode'=>'none','badge'=>'PREIS']],
        ['id'=>'LT-WARE','name'=>'Lagerplatz 62 × 29','category'=>'warehouse','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>1,'layout'=>['theme'=>'warehouse','accent'=>'#385847','show_name'=>true,'font_scale'=>1.05,'group'=>'Lager & Logistik','purpose'=>'Standardlageretikett mit Lagerplatz und Bestand.','show_logo'=>false,'show_stock'=>true,'show_location'=>true,'show_sku'=>true,'barcode'=>'code128','barcode_field'=>'sku','badge'=>'LAGER']],
        ['id'=>'LT-WARE-XL','name'=>'Lagerplatz XXL 62 × 40','category'=>'warehouse','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>1,'layout'=>['theme'=>'warehouse_xl','accent'=>'#2f5140','show_name'=>true,'font_scale'=>1.18,'group'=>'Lager & Logistik','purpose'=>'Großer Lagerplatz für Regale und Entfernung.','show_logo'=>false,'show_stock'=>true,'show_location'=>true,'show_sku'=>true,'barcode'=>'code128','barcode_field'=>'sku','badge'=>'LAGERPLATZ']],
        ['id'=>'LT-STOCK-MIN','name'=>'Bestand & Mindestbestand 62 × 29','category'=>'warehouse','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'stock','accent'=>'#6a4c2d','show_name'=>true,'font_scale'=>1.0,'group'=>'Lager & Logistik','purpose'=>'Aktueller Bestand plus Mindestbestand.','show_logo'=>false,'show_stock'=>true,'show_minimum'=>true,'show_location'=>true,'show_sku'=>true,'barcode'=>'code128','barcode_field'=>'sku','badge'=>'BESTAND']],
        ['id'=>'LT-INVENTORY','name'=>'Inventur 62 × 29','category'=>'warehouse','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'technical','accent'=>'#4c5661','show_name'=>true,'font_scale'=>1.0,'group'=>'Lager & Logistik','purpose'=>'Inventurkennzeichnung mit SKU, Bestand und Datum.','show_logo'=>false,'show_stock'=>true,'show_location'=>true,'show_sku'=>true,'show_date'=>true,'barcode'=>'code128','barcode_field'=>'sku','badge'=>'INVENTUR']],
        ['id'=>'LT-GOODS-IN','name'=>'Wareneingang 62 × 40','category'=>'warehouse','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'incoming','accent'=>'#315c75','show_name'=>true,'font_scale'=>1.0,'group'=>'Lager & Logistik','purpose'=>'Kennzeichnung neuer Wareneingänge.','show_logo'=>false,'show_stock'=>true,'show_location'=>true,'show_sku'=>true,'show_date'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'WARENEINGANG']],
        ['id'=>'LT-PICKING','name'=>'Kommissionierung 62 × 29','category'=>'warehouse','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'picking','accent'=>'#6b4f7d','show_name'=>true,'font_scale'=>1.0,'group'=>'Lager & Logistik','purpose'=>'Schnelle Pick-Information für Lagerabläufe.','show_logo'=>false,'show_location'=>true,'show_sku'=>true,'barcode'=>'code128','barcode_field'=>'sku','badge'=>'PICK']],
        ['id'=>'LT-RACK-BC','name'=>'Regal Barcode 62 × 29','category'=>'warehouse','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'barcode','accent'=>'#161616','show_name'=>false,'font_scale'=>1.0,'group'=>'Lager & Logistik','purpose'=>'Großer Barcode für Regal- und Scannerprozesse.','show_logo'=>false,'show_location'=>true,'show_sku'=>true,'barcode'=>'code128','barcode_field'=>'sku','barcode_emphasis'=>true,'badge'=>'REGAL']],
        ['id'=>'LT-BOX','name'=>'Kiste / Behälter 62 × 40','category'=>'warehouse','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'container','accent'=>'#725527','show_name'=>true,'font_scale'=>1.0,'group'=>'Lager & Logistik','purpose'=>'Behälterkennzeichnung mit Inhalt und Lagerplatz.','show_logo'=>false,'show_stock'=>true,'show_location'=>true,'show_sku'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'BEHÄLTER']],
        ['id'=>'LT-BATCH-WH','name'=>'Charge Lager 62 × 29','category'=>'warehouse','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'batch','accent'=>'#5a4f74','show_name'=>true,'font_scale'=>1.0,'group'=>'Lager & Logistik','purpose'=>'Lageretikett für Charge/Lot und Artikel.','show_logo'=>false,'show_sku'=>true,'show_batch'=>true,'show_location'=>true,'barcode'=>'code128','barcode_field'=>'sku','badge'=>'CHARGE']],
        ['id'=>'LT-QA','name'=>'Qualitätsprüfung 62 × 40','category'=>'warehouse','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'quality','accent'=>'#28635b','show_name'=>true,'font_scale'=>1.0,'group'=>'Lager & Logistik','purpose'=>'Ware zur Qualitätskontrolle eindeutig kennzeichnen.','show_logo'=>false,'show_sku'=>true,'show_date'=>true,'show_note'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'QS']],
        ['id'=>'LT-SHIP','name'=>'Adressetikett 62 × 100','category'=>'shipping','width_mm'=>62,'height_mm'=>100,'orientation'=>'landscape','favorite'=>1,'layout'=>['theme'=>'shipping','accent'=>'#2c4e68','show_name'=>true,'font_scale'=>1,'group'=>'Versand & Kunde','purpose'=>'Standard-Versandadresse mit Auftrag und QR-Code.','show_logo'=>true,'show_customer'=>true,'show_address'=>true,'show_order'=>true,'barcode'=>'qrcode','barcode_field'=>'order_no']],
        ['id'=>'LT-SHIP-COMPACT','name'=>'Versand kompakt 62 × 90','category'=>'shipping','width_mm'=>62,'height_mm'=>90,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'shipping_min','accent'=>'#405c70','show_name'=>true,'font_scale'=>0.92,'group'=>'Versand & Kunde','purpose'=>'Kompakter Adressaufkleber für kleinere Pakete.','show_logo'=>false,'show_customer'=>true,'show_address'=>true,'show_order'=>true,'barcode'=>'code128','barcode_field'=>'order_no']],
        ['id'=>'LT-SHIP-QR','name'=>'Versand QR Auftrag 62 × 100','category'=>'shipping','width_mm'=>62,'height_mm'=>100,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'qr','accent'=>'#1f5c58','show_name'=>true,'font_scale'=>1.0,'group'=>'Versand & Kunde','purpose'=>'Adresse mit großem QR-Code zur Auftragszuordnung.','show_logo'=>true,'show_customer'=>true,'show_address'=>true,'show_order'=>true,'barcode'=>'qrcode','barcode_field'=>'order_no','barcode_emphasis'=>true,'badge'=>'AUFTRAG']],
        ['id'=>'LT-TRACK','name'=>'Versand Tracking 62 × 100','category'=>'shipping','width_mm'=>62,'height_mm'=>100,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'shipping','accent'=>'#31567a','show_name'=>true,'font_scale'=>1.0,'group'=>'Versand & Kunde','purpose'=>'Versandetikett mit Carrier- und Trackinginformation.','show_logo'=>true,'show_customer'=>true,'show_address'=>true,'show_order'=>true,'show_tracking'=>true,'barcode'=>'code128','barcode_field'=>'tracking','badge'=>'TRACKING']],
        ['id'=>'LT-PACK-CONTENT','name'=>'Paketinhalt 62 × 62','category'=>'shipping','width_mm'=>62,'height_mm'=>62,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'package','accent'=>'#6a4a2f','show_name'=>true,'font_scale'=>1.0,'group'=>'Versand & Kunde','purpose'=>'Interne Paketkennzeichnung mit Auftrag und Hinweis.','show_logo'=>true,'show_customer'=>true,'show_order'=>true,'show_note'=>true,'barcode'=>'qrcode','barcode_field'=>'order_no','badge'=>'PAKET']],
        ['id'=>'LT-RETURN-INTERNAL','name'=>'Retoure intern 62 × 62','category'=>'shipping','width_mm'=>62,'height_mm'=>62,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'return','accent'=>'#8a3f3f','show_name'=>true,'font_scale'=>1.0,'group'=>'Versand & Kunde','purpose'=>'Interne Retourenkennzeichnung, nicht als Carrier-Retourenlabel.','show_logo'=>false,'show_customer'=>true,'show_order'=>true,'show_note'=>true,'barcode'=>'qrcode','barcode_field'=>'order_no','badge'=>'RETOURE']],
        ['id'=>'LT-ADDRESS','name'=>'Kundenadresse 62 × 100','category'=>'address','width_mm'=>62,'height_mm'=>100,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'address','accent'=>'#384c5d','show_name'=>true,'font_scale'=>1.06,'group'=>'Versand & Kunde','purpose'=>'Reines Adressetikett ohne Verkaufsinformationen.','show_logo'=>true,'show_customer'=>true,'show_address'=>true,'barcode'=>'none']],
        ['id'=>'LT-PICKUP','name'=>'Abholung / Click & Collect 62 × 62','category'=>'shipping','width_mm'=>62,'height_mm'=>62,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'pickup','accent'=>'#2f6549','show_name'=>true,'font_scale'=>1.0,'group'=>'Versand & Kunde','purpose'=>'Kennzeichnung vorbereiteter Abholbestellungen.','show_logo'=>true,'show_customer'=>true,'show_order'=>true,'show_date'=>true,'barcode'=>'qrcode','barcode_field'=>'order_no','badge'=>'ABHOLUNG']],
        ['id'=>'LT-PROD-BATCH','name'=>'Produktionscharge 62 × 40','category'=>'batch','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>1,'layout'=>['theme'=>'batch','accent'=>'#5a4d76','show_name'=>true,'font_scale'=>1.0,'group'=>'Produktion & Spezial','purpose'=>'Charge/Lot, Artikel und Datum für Produktionslose.','show_logo'=>true,'show_sku'=>true,'show_batch'=>true,'show_date'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'CHARGE']],
        ['id'=>'LT-MHD','name'=>'MHD / Haltbarkeit 62 × 40','category'=>'batch','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>1,'layout'=>['theme'=>'food','accent'=>'#7b5b2d','show_name'=>true,'font_scale'=>1.0,'group'=>'Produktion & Spezial','purpose'=>'Mindesthaltbarkeit und Charge klar kennzeichnen.','show_logo'=>true,'show_sku'=>true,'show_best_before'=>true,'show_batch'=>true,'barcode'=>'code128','barcode_field'=>'sku','badge'=>'MHD']],
        ['id'=>'LT-FOOD-INFO','name'=>'Lebensmittel Info 62 × 62','category'=>'batch','width_mm'=>62,'height_mm'=>62,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'food','accent'=>'#655331','show_name'=>true,'font_scale'=>1.0,'group'=>'Produktion & Spezial','purpose'=>'Zusatzangaben wie Herkunft, Gewicht, Charge und Hinweis.','show_logo'=>true,'show_unit'=>true,'show_weight'=>true,'show_origin'=>true,'show_batch'=>true,'show_best_before'=>true,'show_note'=>true,'barcode'=>'qrcode','barcode_field'=>'sku']],
        ['id'=>'LT-WARNING','name'=>'Warnhinweis 62 × 40','category'=>'custom','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'warning','accent'=>'#c5392c','show_name'=>true,'font_scale'=>1.08,'group'=>'Produktion & Spezial','purpose'=>'Deutliche Warn- und Sicherheitshinweise.','show_logo'=>false,'show_note'=>true,'barcode'=>'none','badge'=>'ACHTUNG']],
        ['id'=>'LT-THANKS','name'=>'Danke / Geschenk 62 × 40','category'=>'custom','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'gift','accent'=>'#9a5270','show_name'=>true,'font_scale'=>1.0,'group'=>'Marketing & Service','purpose'=>'Persönlicher Beileger für Geschenk- und Kundenpakete.','show_logo'=>true,'show_note'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'DANKE']],
        ['id'=>'LT-B2B','name'=>'Händler / B2B 62 × 40','category'=>'custom','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'business','accent'=>'#304f6c','show_name'=>true,'font_scale'=>1.0,'group'=>'Marketing & Service','purpose'=>'B2B-Kennzeichnung mit Artikelnummer und QR-Code.','show_logo'=>true,'show_sku'=>true,'show_price'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'HÄNDLER']],
        ['id'=>'LT-PROTOTYPE','name'=>'Prototyp 62 × 40','category'=>'custom','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'prototype','accent'=>'#5b4470','show_name'=>true,'font_scale'=>1.0,'group'=>'Marketing & Service','purpose'=>'Prototypen und Sonderanfertigungen eindeutig markieren.','show_logo'=>true,'show_sku'=>true,'show_note'=>true,'show_date'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'PROTOTYP']],
        ['id'=>'LT-SERVICE','name'=>'Reparatur / Service 62 × 62','category'=>'custom','width_mm'=>62,'height_mm'=>62,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'service','accent'=>'#3b6072','show_name'=>true,'font_scale'=>1.0,'group'=>'Marketing & Service','purpose'=>'Service- und Bearbeitungsvorgänge mit QR-Code.','show_logo'=>true,'show_customer'=>true,'show_order'=>true,'show_note'=>true,'show_date'=>true,'barcode'=>'qrcode','barcode_field'=>'order_no','badge'=>'SERVICE']],
        ['id'=>'LT-QR-GUIDE','name'=>'QR Anleitung 62 × 29','category'=>'custom','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'qr','accent'=>'#276157','show_name'=>true,'font_scale'=>1.0,'group'=>'Marketing & Service','purpose'=>'QR-Code für Anleitung, Rezept oder digitale Hilfe.','show_logo'=>true,'show_price'=>false,'show_sku'=>false,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'ANLEITUNG']],
        ['id'=>'LT-UNIVERSAL','name'=>'Universal frei 62 × 40','category'=>'custom','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'clean','accent'=>'#524b45','show_name'=>true,'font_scale'=>1.0,'group'=>'Marketing & Service','purpose'=>'Flexible neutrale Vorlage für freie Eingaben.','show_logo'=>true,'show_price'=>false,'show_sku'=>true,'show_note'=>true,'barcode'=>'code128','barcode_field'=>'barcode']]
    ];
}

function rh24_label_system_templates_v964(): array {
    $base=rh24_label_system_templates_v961();
    $extra=[
        ['id'=>'LT-RH-PREM','name'=>'Räucherhaken Premium 62 × 29','category'=>'product','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>1,'layout'=>['theme'=>'premium','accent'=>'#8a3c1f','show_name'=>true,'font_scale'=>1.0,'group'=>'Produkt & Shop','purpose'=>'Premiumetikett für Räucherhaken mit Preis, Artikelnummer und QR-Code.','show_logo'=>true,'show_price'=>true,'show_sku'=>true,'show_unit'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'RÄUCHERHAKEN']],
        ['id'=>'LT-LAUGE','name'=>'Räucherlauge 62 × 40','category'=>'product','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>1,'layout'=>['theme'=>'food','accent'=>'#6b4d2b','show_name'=>true,'font_scale'=>1.0,'group'=>'Produkt & Shop','purpose'=>'Produktetikett für Räucherlaugen mit Gewicht, Herkunft und Artikelnummer.','show_logo'=>true,'show_price'=>true,'show_sku'=>true,'show_weight'=>true,'show_origin'=>true,'barcode'=>'code128','barcode_field'=>'sku','badge'=>'RÄUCHERLAUGE']],
        ['id'=>'LT-MEHL','name'=>'Räuchermehl 62 × 40','category'=>'product','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'food','accent'=>'#59472f','show_name'=>true,'font_scale'=>1.0,'group'=>'Produkt & Shop','purpose'=>'Etikett für Räuchermehl mit Sorte, Gewicht und Barcode.','show_logo'=>true,'show_price'=>true,'show_sku'=>true,'show_weight'=>true,'barcode'=>'code128','barcode_field'=>'barcode','badge'=>'RÄUCHERMEHL']],
        ['id'=>'LT-SPICE','name'=>'Gewürz / Mischung 62 × 40','category'=>'product','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'food','accent'=>'#7a5530','show_name'=>true,'font_scale'=>1.0,'group'=>'Produkt & Shop','purpose'=>'Gewürzetikett mit Produktname, Gewicht und QR-Code.','show_logo'=>true,'show_price'=>true,'show_weight'=>true,'show_origin'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'GEWÜRZ']],
        ['id'=>'LT-FISH','name'=>'Fischprodukt 62 × 29','category'=>'product','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'clean','accent'=>'#2f627b','show_name'=>true,'font_scale'=>1.0,'group'=>'Produkt & Shop','purpose'=>'Klares Produktetikett für Fisch- und Räucherfischartikel.','show_logo'=>true,'show_price'=>true,'show_sku'=>true,'barcode'=>'code128','barcode_field'=>'barcode','badge'=>'FISCH']],
        ['id'=>'LT-MEAT','name'=>'Fleischprodukt 62 × 29','category'=>'product','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'clean','accent'=>'#7b3c37','show_name'=>true,'font_scale'=>1.0,'group'=>'Produkt & Shop','purpose'=>'Klares Produktetikett für Fleisch- und Schinkenprodukte.','show_logo'=>true,'show_price'=>true,'show_sku'=>true,'barcode'=>'code128','barcode_field'=>'barcode','badge'=>'FLEISCH']],
        ['id'=>'LT-SMOKER','name'=>'Smoker & Zubehör 62 × 40','category'=>'product','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'technical','accent'=>'#343434','show_name'=>true,'font_scale'=>1.0,'group'=>'Produkt & Shop','purpose'=>'Technisches Produktetikett für Smoker, Thermometer und Zubehör.','show_logo'=>true,'show_price'=>true,'show_sku'=>true,'show_note'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'ZUBEHÖR']],
        ['id'=>'LT-BUNDLE','name'=>'Bundle / Set 62 × 40','category'=>'product','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'premium','accent'=>'#6b4a2e','show_name'=>true,'font_scale'=>1.0,'group'=>'Produkt & Shop','purpose'=>'Set- und Bundle-Etikett mit Preis und QR-Code.','show_logo'=>true,'show_price'=>true,'show_sku'=>true,'show_note'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'SET']],
        ['id'=>'LT-NEW','name'=>'Neuheit 62 × 29','category'=>'product','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'sale_outline','accent'=>'#bd4e1b','show_name'=>true,'font_scale'=>1.0,'group'=>'Produkt & Shop','purpose'=>'Auffälliges Kennzeichen für neue Produkte.','show_logo'=>true,'show_price'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'NEU']],
        ['id'=>'LT-BEST','name'=>'Bestseller 62 × 29','category'=>'product','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'premium','accent'=>'#906317','show_name'=>true,'font_scale'=>1.0,'group'=>'Produkt & Shop','purpose'=>'Bestseller-Etikett für besonders gefragte Artikel.','show_logo'=>true,'show_price'=>true,'barcode'=>'code128','barcode_field'=>'barcode','badge'=>'BESTSELLER']],
        ['id'=>'LT-MADE-DE','name'=>'Made in Germany 62 × 29','category'=>'product','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'clean','accent'=>'#333333','show_name'=>true,'font_scale'=>1.0,'group'=>'Produkt & Shop','purpose'=>'Produktkennzeichnung mit Herkunfts- und Qualitätsfokus.','show_logo'=>true,'show_sku'=>true,'show_origin'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'MADE IN GERMANY']],
        ['id'=>'LT-HANDMADE','name'=>'Handarbeit 62 × 29','category'=>'product','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'premium','accent'=>'#7b512f','show_name'=>true,'font_scale'=>1.0,'group'=>'Produkt & Shop','purpose'=>'Etikett für handgefertigte Artikel und Sonderanfertigungen.','show_logo'=>true,'show_price'=>true,'show_note'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'HANDARBEIT']],
        ['id'=>'LT-PRICE-UVP','name'=>'UVP / Verkaufspreis 62 × 29','category'=>'price','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'price','accent'=>'#b8441b','show_name'=>true,'font_scale'=>1.0,'group'=>'Preis & Verkauf','purpose'=>'Preiskennzeichnung mit UVP-Hinweis und Verkaufspreis.','show_logo'=>false,'show_price'=>true,'show_note'=>true,'price_emphasis'=>true,'barcode'=>'ean13','barcode_field'=>'barcode','badge'=>'UVP']],
        ['id'=>'LT-PRICE-OLDNEW','name'=>'Alt / Neu Preis 62 × 40','category'=>'price','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'sale','accent'=>'#c42d1f','show_name'=>true,'font_scale'=>1.0,'group'=>'Preis & Verkauf','purpose'=>'Aktionsetikett für alten und neuen Preis über den Hinweistext.','show_price'=>true,'show_note'=>true,'price_emphasis'=>true,'barcode'=>'code128','barcode_field'=>'barcode','badge'=>'JETZT']],
        ['id'=>'LT-PRICE-WEEK','name'=>'Wochenaktion 62 × 29','category'=>'price','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'sale_outline','accent'=>'#cf4f17','show_name'=>true,'font_scale'=>1.0,'group'=>'Preis & Verkauf','purpose'=>'Schnell sichtbare Wochenaktion für Laden und Regal.','show_price'=>true,'barcode'=>'none','badge'=>'WOCHENAKTION']],
        ['id'=>'LT-PRICE-PERCENT','name'=>'Rabatt % 62 × 29','category'=>'price','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'sale','accent'=>'#bd2319','show_name'=>true,'font_scale'=>1.0,'group'=>'Preis & Verkauf','purpose'=>'Rabattetikett mit frei eintragbarem Prozent-Hinweis.','show_price'=>true,'show_note'=>true,'barcode'=>'none','badge'=>'RABATT']],
        ['id'=>'LT-PRICE-NET','name'=>'Händler Netto 62 × 29','category'=>'price','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'business','accent'=>'#2e536f','show_name'=>true,'font_scale'=>1.0,'group'=>'Preis & Verkauf','purpose'=>'Sachliche B2B-Netto-Preisauszeichnung.','show_logo'=>true,'show_price'=>true,'show_sku'=>true,'show_note'=>true,'barcode'=>'code128','barcode_field'=>'sku','badge'=>'NETTO / B2B']],
        ['id'=>'LT-PRICE-POS','name'=>'Kassenpreis 38 × 29','category'=>'price','width_mm'=>38,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'price_xl','accent'=>'#9c3419','show_name'=>true,'font_scale'=>1.0,'group'=>'Preis & Verkauf','purpose'=>'Kompakte Preiskennzeichnung direkt am POS.','show_price'=>true,'price_emphasis'=>true,'barcode'=>'none','badge'=>'KASSE']],
        ['id'=>'LT-PRICE-2FOR','name'=>'2-für / Mehrfachaktion 62 × 29','category'=>'price','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'sale_outline','accent'=>'#b43b1f','show_name'=>true,'font_scale'=>1.0,'group'=>'Preis & Verkauf','purpose'=>'Mehrfachaktionsetikett für 2-für- oder Bundle-Angebote.','show_price'=>true,'show_note'=>true,'barcode'=>'none','badge'=>'2-FÜR']],
        ['id'=>'LT-PRICE-BULK','name'=>'Mengenrabatt 62 × 40','category'=>'price','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'business','accent'=>'#425c70','show_name'=>true,'font_scale'=>1.0,'group'=>'Preis & Verkauf','purpose'=>'Mengenrabatte und Staffelpreise verständlich auszeichnen.','show_price'=>true,'show_sku'=>true,'show_note'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'MENGENRABATT']],
        ['id'=>'LT-WH-BLOCK','name'=>'Sperrlager 62 × 40','category'=>'warehouse','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>1,'layout'=>['theme'=>'warning','accent'=>'#bd2f26','show_name'=>true,'font_scale'=>1.0,'group'=>'Lager & Logistik','purpose'=>'Deutliche Kennzeichnung gesperrter Ware.','show_sku'=>true,'show_location'=>true,'show_note'=>true,'barcode'=>'code128','barcode_field'=>'sku','badge'=>'GESPERRT']],
        ['id'=>'LT-WH-RELEASE','name'=>'Freigegeben 62 × 40','category'=>'warehouse','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'clean','accent'=>'#2f7049','show_name'=>true,'font_scale'=>1.0,'group'=>'Lager & Logistik','purpose'=>'Freigabeetikett nach Wareneingangs- oder Qualitätsprüfung.','show_sku'=>true,'show_date'=>true,'show_note'=>true,'barcode'=>'code128','barcode_field'=>'sku','badge'=>'FREIGEGEBEN']],
        ['id'=>'LT-WH-QC','name'=>'QS geprüft 62 × 40','category'=>'warehouse','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'technical','accent'=>'#356074','show_name'=>true,'font_scale'=>1.0,'group'=>'Lager & Logistik','purpose'=>'Qualitätssicherungs-Etikett mit Datum und Charge.','show_sku'=>true,'show_batch'=>true,'show_date'=>true,'show_note'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'QS GEPRÜFT']],
        ['id'=>'LT-WH-RECHECK','name'=>'Nachprüfung 62 × 40','category'=>'warehouse','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'warning','accent'=>'#a56a19','show_name'=>true,'font_scale'=>1.0,'group'=>'Lager & Logistik','purpose'=>'Kennzeichnung für Ware mit ausstehender Nachprüfung.','show_sku'=>true,'show_date'=>true,'show_note'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'NACHPRÜFUNG']],
        ['id'=>'LT-WH-DAMAGE','name'=>'Mangel / Beschädigt 62 × 40','category'=>'warehouse','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'warning','accent'=>'#b5342a','show_name'=>true,'font_scale'=>1.0,'group'=>'Lager & Logistik','purpose'=>'Interne Kennzeichnung beschädigter oder mangelhafter Ware.','show_sku'=>true,'show_location'=>true,'show_note'=>true,'barcode'=>'code128','barcode_field'=>'sku','badge'=>'MANGEL']],
        ['id'=>'LT-WH-PALLET','name'=>'Palette / Stellplatz 100 × 62','category'=>'warehouse','width_mm'=>100,'height_mm'=>62,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'warehouse','accent'=>'#3e5566','show_name'=>true,'font_scale'=>1.0,'group'=>'Lager & Logistik','purpose'=>'Großes Paletten- und Stellplatzetikett mit QR-Code.','show_location'=>true,'show_stock'=>true,'show_note'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','barcode_emphasis'=>true,'badge'=>'PALETTE']],
        ['id'=>'LT-WH-BOX','name'=>'Behälter / Kiste 62 × 62','category'=>'warehouse','width_mm'=>62,'height_mm'=>62,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'warehouse','accent'=>'#465d55','show_name'=>true,'font_scale'=>1.0,'group'=>'Lager & Logistik','purpose'=>'Mehrfach verwendbares Behälter- und Kistenetikett.','show_sku'=>true,'show_location'=>true,'show_note'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'BEHÄLTER']],
        ['id'=>'LT-WH-FIFO','name'=>'FIFO 62 × 29','category'=>'warehouse','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'technical','accent'=>'#4f6470','show_name'=>true,'font_scale'=>1.0,'group'=>'Lager & Logistik','purpose'=>'Kennzeichnung für First-In-First-Out-Lagerführung.','show_batch'=>true,'show_date'=>true,'barcode'=>'code128','barcode_field'=>'sku','badge'=>'FIFO']],
        ['id'=>'LT-WH-FEFO','name'=>'FEFO / MHD 62 × 40','category'=>'warehouse','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'food','accent'=>'#77612e','show_name'=>true,'font_scale'=>1.0,'group'=>'Lager & Logistik','purpose'=>'Lageretikett für First-Expire-First-Out mit MHD.','show_batch'=>true,'show_best_before'=>true,'show_location'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'FEFO']],
        ['id'=>'LT-WH-RESTOCK','name'=>'Nachfüllen 62 × 29','category'=>'warehouse','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'warning','accent'=>'#a4691c','show_name'=>true,'font_scale'=>1.0,'group'=>'Lager & Logistik','purpose'=>'Schnellhinweis für Regal- oder Lager-Nachfüllung.','show_stock'=>true,'show_minimum'=>true,'show_location'=>true,'barcode'=>'code128','barcode_field'=>'sku','badge'=>'NACHFÜLLEN']],
        ['id'=>'LT-WH-OOS','name'=>'Nicht verfügbar 62 × 29','category'=>'warehouse','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'warning','accent'=>'#9d3028','show_name'=>true,'font_scale'=>1.0,'group'=>'Lager & Logistik','purpose'=>'Kennzeichnung für aktuell nicht verfügbare Artikel.','show_sku'=>true,'show_note'=>true,'barcode'=>'none','badge'=>'NICHT VERFÜGBAR']],
        ['id'=>'LT-WH-RESERVED','name'=>'Reserviert 62 × 40','category'=>'warehouse','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'pickup','accent'=>'#2f5f72','show_name'=>true,'font_scale'=>1.0,'group'=>'Lager & Logistik','purpose'=>'Reservierte Ware einem Auftrag oder Kunden zuordnen.','show_customer'=>true,'show_order'=>true,'show_location'=>true,'barcode'=>'qrcode','barcode_field'=>'order_no','badge'=>'RESERVIERT']],
        ['id'=>'LT-SHIP-DHL','name'=>'DHL intern 100 × 62','category'=>'shipping','width_mm'=>100,'height_mm'=>62,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'shipping','accent'=>'#d0a500','show_name'=>true,'font_scale'=>1.0,'group'=>'Versand & Kunde','purpose'=>'Interne Versandvorbereitung für DHL; kein offizielles Carrierlabel.','show_customer'=>true,'show_address'=>true,'show_order'=>true,'show_tracking'=>true,'barcode'=>'qrcode','barcode_field'=>'order_no','badge'=>'DHL INTERN']],
        ['id'=>'LT-SHIP-DPD','name'=>'DPD intern 100 × 62','category'=>'shipping','width_mm'=>100,'height_mm'=>62,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'shipping','accent'=>'#9b271d','show_name'=>true,'font_scale'=>1.0,'group'=>'Versand & Kunde','purpose'=>'Interne Versandvorbereitung für DPD; kein offizielles Carrierlabel.','show_customer'=>true,'show_address'=>true,'show_order'=>true,'show_tracking'=>true,'barcode'=>'qrcode','barcode_field'=>'order_no','badge'=>'DPD INTERN']],
        ['id'=>'LT-SHIP-FRAGILE','name'=>'Vorsicht zerbrechlich 100 × 62','category'=>'shipping','width_mm'=>100,'height_mm'=>62,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'warning','accent'=>'#c33125','show_name'=>true,'font_scale'=>1.0,'group'=>'Versand & Kunde','purpose'=>'Großer Hinweis für empfindliche Sendungen.','show_note'=>true,'barcode'=>'none','badge'=>'ZERBRECHLICH']],
        ['id'=>'LT-SHIP-DRY','name'=>'Vor Nässe schützen 100 × 62','category'=>'shipping','width_mm'=>100,'height_mm'=>62,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'warning','accent'=>'#2b6580','show_name'=>true,'font_scale'=>1.0,'group'=>'Versand & Kunde','purpose'=>'Großer Versandhinweis für feuchtigkeitsempfindliche Ware.','show_note'=>true,'barcode'=>'none','badge'=>'TROCKEN HALTEN']],
        ['id'=>'LT-SHIP-UP','name'=>'Diese Seite oben 100 × 62','category'=>'shipping','width_mm'=>100,'height_mm'=>62,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'warning','accent'=>'#444444','show_name'=>true,'font_scale'=>1.0,'group'=>'Versand & Kunde','purpose'=>'Orientierungshinweis für Pakete und Behälter.','show_note'=>true,'barcode'=>'none','badge'=>'DIESE SEITE OBEN']],
        ['id'=>'LT-SHIP-EXPRESS','name'=>'Express intern 62 × 62','category'=>'shipping','width_mm'=>62,'height_mm'=>62,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'sale_outline','accent'=>'#c4451d','show_name'=>true,'font_scale'=>1.0,'group'=>'Versand & Kunde','purpose'=>'Interne Prioritätskennzeichnung für Expressbearbeitung.','show_customer'=>true,'show_order'=>true,'show_date'=>true,'barcode'=>'qrcode','barcode_field'=>'order_no','badge'=>'EXPRESS']],
        ['id'=>'LT-SHIP-PICK','name'=>'Kommissionierung 62 × 40','category'=>'shipping','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'warehouse','accent'=>'#3c5f52','show_name'=>true,'font_scale'=>1.0,'group'=>'Versand & Kunde','purpose'=>'Picketikett für Auftragskommissionierung im Lager.','show_order'=>true,'show_location'=>true,'show_note'=>true,'barcode'=>'code128','barcode_field'=>'order_no','badge'=>'PICK']],
        ['id'=>'LT-RETURN-QC','name'=>'Retoure prüfen 62 × 62','category'=>'shipping','width_mm'=>62,'height_mm'=>62,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'return','accent'=>'#8c3e39','show_name'=>true,'font_scale'=>1.0,'group'=>'Versand & Kunde','purpose'=>'Interne Retourenprüfung mit Auftrag und Notiz.','show_customer'=>true,'show_order'=>true,'show_note'=>true,'show_date'=>true,'barcode'=>'qrcode','barcode_field'=>'order_no','badge'=>'RETOURE PRÜFEN']],
        ['id'=>'LT-ALLERGEN','name'=>'Allergen-Hinweis 62 × 40','category'=>'batch','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'warning','accent'=>'#b44a22','show_name'=>true,'font_scale'=>1.0,'group'=>'Produktion & Spezial','purpose'=>'Freier Allergen-/Hinweisaufkleber; Inhalte fachlich selbst pflegen.','show_note'=>true,'show_batch'=>true,'barcode'=>'none','badge'=>'HINWEIS']],
        ['id'=>'LT-INGREDIENT','name'=>'Zutaten / Info 62 × 62','category'=>'batch','width_mm'=>62,'height_mm'=>62,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'food','accent'=>'#6c5832','show_name'=>true,'font_scale'=>1.0,'group'=>'Produktion & Spezial','purpose'=>'Mehr Platz für Zutaten- oder Produktinformationen im Hinweisfeld.','show_weight'=>true,'show_origin'=>true,'show_note'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'PRODUKTINFO']],
        ['id'=>'LT-PACK-DATE','name'=>'Verpackt am 62 × 29','category'=>'batch','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'food','accent'=>'#4f6841','show_name'=>true,'font_scale'=>1.0,'group'=>'Produktion & Spezial','purpose'=>'Datums- und Chargenkennzeichnung für verpackte Ware.','show_batch'=>true,'show_date'=>true,'barcode'=>'code128','barcode_field'=>'sku','badge'=>'VERPACKT AM']],
        ['id'=>'LT-SMOKE-DATE','name'=>'Geräuchert am 62 × 29','category'=>'batch','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'food','accent'=>'#74503b','show_name'=>true,'font_scale'=>1.0,'group'=>'Produktion & Spezial','purpose'=>'Datums- und Chargenkennzeichnung für Räucherprodukte.','show_batch'=>true,'show_date'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'GERÄUCHERT AM']],
        ['id'=>'LT-FREEZE','name'=>'Tiefkühlhinweis 62 × 40','category'=>'batch','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'food','accent'=>'#2f6787','show_name'=>true,'font_scale'=>1.0,'group'=>'Produktion & Spezial','purpose'=>'Freier Tiefkühl- und Lagerhinweis mit MHD und Charge.','show_best_before'=>true,'show_batch'=>true,'show_note'=>true,'barcode'=>'code128','barcode_field'=>'sku','badge'=>'TIEFKÜHL']],
        ['id'=>'LT-LOT-XL','name'=>'Charge / Lot XL 100 × 62','category'=>'batch','width_mm'=>100,'height_mm'=>62,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'batch','accent'=>'#5c4b74','show_name'=>true,'font_scale'=>1.0,'group'=>'Produktion & Spezial','purpose'=>'Große Chargenkennzeichnung für Produktion und Gebinde.','show_sku'=>true,'show_batch'=>true,'show_date'=>true,'show_note'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','barcode_emphasis'=>true,'badge'=>'LOT / CHARGE']],
        ['id'=>'LT-QR-RECIPE','name'=>'QR Rezept 62 × 29','category'=>'custom','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'qr','accent'=>'#2b6959','show_name'=>true,'font_scale'=>1.0,'group'=>'Marketing & Service','purpose'=>'QR-Etikett für Rezept, Zubereitung oder Räucheranleitung.','show_logo'=>true,'show_note'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'REZEPT']],
        ['id'=>'LT-QR-SOCIAL','name'=>'QR Social 62 × 29','category'=>'custom','width_mm'=>62,'height_mm'=>29,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'qr','accent'=>'#4a4b73','show_name'=>true,'font_scale'=>1.0,'group'=>'Marketing & Service','purpose'=>'QR-Etikett für Social-Media-, Bewertungs- oder Community-Link.','show_logo'=>true,'show_note'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'SCAN & FOLGE']],
        ['id'=>'LT-GIFT','name'=>'Geschenk 62 × 62','category'=>'custom','width_mm'=>62,'height_mm'=>62,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'gift','accent'=>'#99526f','show_name'=>true,'font_scale'=>1.0,'group'=>'Marketing & Service','purpose'=>'Geschenketikett mit persönlichem Hinweis und QR-Code.','show_logo'=>true,'show_note'=>true,'barcode'=>'qrcode','barcode_field'=>'sku','badge'=>'GESCHENK']],
        ['id'=>'LT-WARRANTY','name'=>'Garantie / Service 62 × 40','category'=>'custom','width_mm'=>62,'height_mm'=>40,'orientation'=>'landscape','favorite'=>0,'layout'=>['theme'=>'service','accent'=>'#3e6170','show_name'=>true,'font_scale'=>1.0,'group'=>'Marketing & Service','purpose'=>'Servicekennzeichnung mit Auftrag, Datum und QR-Code.','show_logo'=>true,'show_customer'=>true,'show_order'=>true,'show_date'=>true,'show_note'=>true,'barcode'=>'qrcode','barcode_field'=>'order_no','badge'=>'SERVICE']],
    ];
    return array_merge($base,$extra);
}

function rh24_seed_v965_printer_profiles(PDO $db): void {
    $profiles=[
      // id, name, maker, model, conn, mode, dpi, w, h, media, orientation, status, settings, notes
      ['LP-QL800','Brother QL-800','Brother','QL-800','usb/system','system_print',300,62,29,'Brother DK','landscape','active',['printer_class'=>'label','technology'=>'direct_thermal','interfaces'=>['USB 2.0'],'interface_note'=>'USB 2.0 Full Speed; Systemtreiber unter macOS/Windows.','media_family'=>'Brother DK bis 62 mm','max_print_width_mm'=>58,'recommended_mode'=>'system_print','source_verified'=>'Brother'],'Brother QL-800: USB-Systemdruck ist der robuste Standardweg.'],
      ['LP-QL810W','Brother QL-810W','Brother','QL-810W','usb/system','system_print',300,62,29,'Brother DK','landscape','inactive',['printer_class'=>'label','technology'=>'direct_thermal','interfaces'=>['USB 2.0','WLAN','Wireless Direct'],'interface_note'=>'USB 2.0 oder WLAN/Wireless Direct.','media_family'=>'Brother DK bis 62 mm','max_print_width_mm'=>58,'recommended_mode'=>'system_print','source_verified'=>'Brother'],'QL-810W Profil mit USB/WLAN.'],
      ['LP-QL820NWB','Brother QL-820NWB','Brother','QL-820NWB','network','system_print',300,62,29,'Brother DK','landscape','inactive',['printer_class'=>'label','technology'=>'direct_thermal','interfaces'=>['USB 2.0','WLAN','LAN 10/100','Bluetooth Classic','USB Host'],'interface_note'=>'USB, WLAN, LAN und Bluetooth Classic.','media_family'=>'Brother DK bis 62 mm','max_print_width_mm'=>58,'recommended_mode'=>'system_print','source_verified'=>'Brother'],'Netzwerkfähiges Brother-Profil mit USB/WLAN/LAN/Bluetooth.'],
      ['LP-QL1110NWB','Brother QL-1110NWB','Brother','QL-1110NWB','network','system_print',300,103,62,'Brother DK Wide','landscape','inactive',['printer_class'=>'label','technology'=>'direct_thermal','interfaces'=>['USB 2.0','WLAN','LAN 10/100','Bluetooth','USB Host'],'interface_note'=>'Breitformat; USB, WLAN, LAN und Bluetooth.','media_family'=>'Brother DK Wide','max_print_width_mm'=>101.6,'recommended_mode'=>'system_print','source_verified'=>'Brother'],'Brother Breitformat für Versand-/Großetiketten.'],
      ['LP-ZD421','Zebra ZD421','Zebra','ZD421','usb/system','system_print',203,100,50,'Rolle / ZPL','landscape','inactive',['printer_class'=>'label','technology'=>'thermal','interfaces'=>['USB 2.0','USB Host','Ethernet optional','WLAN/Bluetooth optional','RS-232 optional'],'interface_note'=>'USB serienmäßig; Ethernet/seriell/WLAN/Bluetooth je nach Ausstattung.','direct_protocol'=>'ZPL','recommended_mode'=>'system_print','optional_bridge'=>'bridge_zpl','source_verified'=>'Zebra'],'Systemdruck oder optionale lokale ZPL-Bridge.'],
      ['LP-ZD621','Zebra ZD621','Zebra','ZD621','network','system_print',203,100,50,'Rolle / ZPL','landscape','inactive',['printer_class'=>'label','technology'=>'thermal','interfaces'=>['USB 2.0','Ethernet/LAN','RS-232','WLAN/Bluetooth optional'],'interface_note'=>'USB und je nach Variante LAN/seriell/WLAN/Bluetooth.','direct_protocol'=>'ZPL','recommended_mode'=>'system_print','optional_bridge'=>'bridge_zpl','source_verified'=>'Zebra'],'Leistungsfähiges Zebra-Profil mit ZPL-Option.'],
      ['LP-DYMO550','DYMO LabelWriter 550','DYMO','LabelWriter 550','usb/system','system_print',300,54,25,'DYMO Originaletiketten','landscape','inactive',['printer_class'=>'label','technology'=>'direct_thermal','interfaces'=>['USB 2.0'],'interface_note'=>'USB 2.0 Printer Class.','max_print_width_mm'=>56,'recommended_mode'=>'system_print','source_verified'=>'DYMO'],'DYMO 550 über USB-Systemtreiber.'],
      ['LP-DYMO550T','DYMO LabelWriter 550 Turbo','DYMO','LabelWriter 550 Turbo','network','system_print',300,54,25,'DYMO Originaletiketten','landscape','inactive',['printer_class'=>'label','technology'=>'direct_thermal','interfaces'=>['USB 2.0','Ethernet 10/100'],'interface_note'=>'USB 2.0 oder Ethernet/LAN.','max_print_width_mm'=>56,'recommended_mode'=>'system_print','source_verified'=>'DYMO'],'DYMO 550 Turbo über USB oder LAN.'],
      ['LP-DYMO5XL','DYMO LabelWriter 5XL','DYMO','LabelWriter 5XL','network','system_print',300,104,159,'DYMO 5XL','portrait','inactive',['printer_class'=>'label','technology'=>'direct_thermal','interfaces'=>['USB 2.0','Ethernet 10/100'],'interface_note'=>'USB 2.0 oder Ethernet/LAN.','max_print_width_mm'=>105.7,'recommended_mode'=>'system_print','source_verified'=>'DYMO'],'Breites DYMO-Profil für Versandetiketten.'],
      ['LP-EPSON-C4000','Epson ColorWorks C4000e','Epson','ColorWorks C4000e','network','system_print',600,100,50,'Rolle / Endlos','landscape','inactive',['printer_class'=>'color_label','technology'=>'inkjet_label','interfaces'=>['USB','Ethernet','WLAN optional'],'interface_note'=>'USB/Ethernet, optionales WLAN; macOS-Treiber verfügbar.','direct_protocol'=>'ESC/Label · ZPL II Emulation','max_print_width_mm'=>108,'recommended_mode'=>'system_print','source_verified'=>'Epson'],'Professioneller Farbetikettendrucker; Systemdruck empfohlen.'],
      ['LP-CITIZEN-CLE300','Citizen CL-E300','Citizen','CL-E300','network','system_print',203,100,50,'Thermorolle','landscape','inactive',['printer_class'=>'label','technology'=>'direct_thermal','interfaces'=>['USB 2.0','Ethernet 10/100','RS-232','Bluetooth/WLAN je nach Variante'],'interface_note'=>'Standardmodell mit USB/LAN/seriell; Funkoptionen modellabhängig.','max_print_width_mm'=>104,'recommended_mode'=>'system_print','optional_bridge'=>'bridge_raw','source_verified'=>'Citizen'],'Lager-/Logistikprofil; Systemtreiber oder optionale RAW-Bridge.'],
      ['LP-TD4420DN','Brother TD-4420DN','Brother','TD-4420DN','network','system_print',203,104,76,'Brother BDE/BDL','landscape','inactive',['printer_class'=>'label','technology'=>'direct_thermal','interfaces'=>['USB 2.0','LAN 10/100','RS-232 seriell'],'interface_note'=>'USB 2.0 Full Speed, LAN 10/100 BASE-TX und serielle Schnittstelle.','direct_protocol'=>'ZPL II / CPCL / ESC-P / EPL2 / DPL emulation','media_family'=>'Brother BDE/BDL bis 118 mm','max_print_width_mm'=>104,'recommended_mode'=>'system_print','optional_bridge'=>'bridge_raw','source_verified'=>'Brother'],'TD-4420DN: USB/LAN/seriell; Systemdruck empfohlen, direkte Emulation optional.'],
      ['LP-TD4550DNWB','Brother TD-4550DNWB','Brother','TD-4550DNWB','network','system_print',300,104,76,'Brother BDE/BDL','landscape','inactive',['printer_class'=>'label','technology'=>'direct_thermal','interfaces'=>['USB','LAN','WLAN','Bluetooth','RS-232 seriell','USB Host'],'interface_note'=>'USB, LAN, WLAN, Bluetooth und seriell inklusive USB Host.','media_family'=>'Brother BDE/BDL','max_print_width_mm'=>104,'recommended_mode'=>'system_print','optional_bridge'=>'bridge_raw','source_verified'=>'Brother'],'TD-4550DNWB: professionelles Netzwerk-/Funkprofil.'],
      ['LP-EPSON-TML90','Epson TM-L90','Epson','TM-L90','network','system_print',203,80,50,'Thermorolle 38–80 mm','landscape','inactive',['printer_class'=>'label','technology'=>'direct_thermal','interfaces'=>['USB 2.0','Ethernet 10/100'],'interface_note'=>'Diese Variante nutzt integriertes USB 2.0 und Ethernet 10/100.','media_family'=>'Rolle 38–80 mm','max_print_width_mm'=>80,'recommended_mode'=>'system_print','source_verified'=>'Epson'],'POS-/Barcode-Etikettendrucker über USB/Ethernet.'],
      ['LP-EPSON-TML90LF','Epson TM-L90LF','Epson','TM-L90LF','network','system_print',203,80,50,'Liner-free Rolle','landscape','inactive',['printer_class'=>'label','technology'=>'direct_thermal','interfaces'=>['USB 2.0','Ethernet 10/100','Kassenschubladenanschluss'],'interface_note'=>'USB 2.0 und Ethernet 10/100; zusätzlich Kassenschubladenanschluss.','media_family'=>'Liner-free Rolle','max_print_width_mm'=>80,'recommended_mode'=>'system_print','source_verified'=>'Epson'],'Liner-free Etikettendrucker für selbstklebende Medien.'],
      ['LP-BIXOLON-XD540D','BIXOLON XD5-40d','Bixolon','XD5-40d','usb/system','system_print',203,104,100,'4-Zoll Thermorolle','landscape','inactive',['printer_class'=>'label','technology'=>'direct_thermal','interfaces'=>['USB','USB Host','RS-232 optional','Ethernet optional','WLAN optional','Bluetooth optional'],'interface_note'=>'Standard USB + USB Host; seriell/Ethernet bzw. WLAN/Bluetooth je nach Ausstattungsvariante.','direct_protocol'=>'SLCS / ZPL II emulation / EPL / DPL optional','max_print_width_mm'=>104,'recommended_mode'=>'system_print','optional_bridge'=>'bridge_raw','source_verified'=>'BIXOLON'],'BIXOLON 4-Zoll Desktopprofil mit kabelgebundenen und optionalen Funkvarianten.'],
      ['LP-TSC-TSPL','TSC Desktop · TSPL','TSC','DA/TE/TDP Familie','usb/system','system_print',203,100,50,'Thermorolle / TSPL','landscape','inactive',['printer_class'=>'label','technology'=>'thermal','interfaces'=>['USB','LAN/WLAN/Bluetooth modellabhängig'],'interface_note'=>'Schnittstellen hängen vom konkreten TSC-Modell ab.','direct_protocol'=>'TSPL','recommended_mode'=>'system_print','optional_bridge'=>'bridge_tspl'],'Generisches TSC-Profil; konkretes Modell und Schnittstelle in der Konfiguration wählen.'],
      ['LP-GODEX-RAW','Godex Desktop Label','Godex','RT/G500 Familie','usb/system','system_print',203,100,50,'Thermorolle','landscape','inactive',['printer_class'=>'label','technology'=>'thermal','interfaces'=>['USB','LAN/seriell modellabhängig'],'interface_note'=>'Konkrete Anschlüsse modellabhängig.','recommended_mode'=>'system_print','optional_bridge'=>'bridge_raw'],'Godex Systemdruckprofil mit optionaler RAW-Bridge.'],
      ['LP-BIXOLON','Bixolon Desktop Label','Bixolon','XD/XQ Familie','usb/system','system_print',203,100,50,'Thermorolle','landscape','inactive',['printer_class'=>'label','technology'=>'thermal','interfaces'=>['USB','LAN/WLAN/Bluetooth modellabhängig'],'interface_note'=>'Konkrete Anschlüsse modellabhängig.','recommended_mode'=>'system_print','optional_bridge'=>'bridge_raw'],'Bixolon Profil für installierte Systemtreiber.'],
      ['LP-SYSTEM-A4','Normaldrucker · universell','Generic','A4/A5/A6 Systemdrucker','system','system_print',300,62,29,'A4/A5/A6/Letter','portrait','active',['printer_class'=>'office','technology'=>'universal','interfaces'=>['macOS/Windows Systemdruck','AirPrint sofern vom Drucker unterstützt','USB/WLAN/LAN über Betriebssystem'],'interface_note'=>'Das Orgaboard nutzt den installierten Betriebssystemdrucker.','media_kind'=>'sheet','paper_size'=>'A4','page_orientation'=>'portrait','paper_width_mm'=>210,'paper_height_mm'=>297,'margin_mm'=>8,'gap_x_mm'=>3,'gap_y_mm'=>3,'fit_mode'=>'auto','auto_rotate'=>true,'center_on_page'=>true,'recommended_mode'=>'system_print'],'Universelles Profil für haushaltsübliche Tintenstrahl- und Laserdrucker.'],
      ['LP-HP-INKJET','HP Tintenstrahl · OfficeJet / ENVY / Smart Tank','HP','OfficeJet · ENVY · Smart Tank','system','system_print',600,62,29,'A4/A5/A6 Etikettenbogen','portrait','inactive',['printer_class'=>'office_inkjet','technology'=>'inkjet','interfaces'=>['Systemdruck/AirPrint','USB/WLAN je nach Modell','LAN je nach Modell'],'interface_note'=>'Die konkrete Verbindung wird vom installierten HP-Modell/Treiber bereitgestellt.','media_kind'=>'sheet','paper_size'=>'A4','page_orientation'=>'portrait','margin_mm'=>8,'gap_x_mm'=>2,'gap_y_mm'=>2,'fit_mode'=>'auto','auto_rotate'=>true,'center_on_page'=>true,'recommended_mode'=>'system_print'],'Haushalts-/Office-Tintenstrahlprofil für HP.'],
      ['LP-HP-LASER','HP LaserJet · Laserdrucker','HP','LaserJet Familie','system','system_print',600,62,29,'A4/A5 Etikettenbogen','portrait','inactive',['printer_class'=>'office_laser','technology'=>'laser','interfaces'=>['Systemdruck/AirPrint','USB/WLAN/LAN je nach Modell'],'interface_note'=>'Verbindung modellabhängig; Ausgabe über Betriebssystemtreiber.','media_kind'=>'sheet','paper_size'=>'A4','page_orientation'=>'portrait','margin_mm'=>8,'gap_x_mm'=>2,'gap_y_mm'=>2,'fit_mode'=>'auto','auto_rotate'=>true,'center_on_page'=>true,'recommended_mode'=>'system_print'],'HP-Laserprofil für lasergeeignete Etikettenbögen.'],
      ['LP-CANON-INKJET','Canon Tintenstrahl · PIXMA / MAXIFY','Canon','PIXMA · MAXIFY','system','system_print',600,62,29,'A4/A5/A6 Etikettenbogen','portrait','inactive',['printer_class'=>'office_inkjet','technology'=>'inkjet','interfaces'=>['Systemdruck/AirPrint','USB/WLAN je nach Modell','LAN je nach Modell'],'interface_note'=>'Konkrete Schnittstellen hängen vom Modell ab.','media_kind'=>'sheet','paper_size'=>'A4','page_orientation'=>'portrait','margin_mm'=>8,'gap_x_mm'=>2,'gap_y_mm'=>2,'fit_mode'=>'auto','auto_rotate'=>true,'center_on_page'=>true],'Canon-Tintenstrahlprofil über Systemdruck.'],
      ['LP-CANON-LASER','Canon Laser · i-SENSYS','Canon','i-SENSYS Familie','system','system_print',600,62,29,'A4/A5 Etikettenbogen','portrait','inactive',['printer_class'=>'office_laser','technology'=>'laser','interfaces'=>['Systemdruck/AirPrint','USB/WLAN/LAN modellabhängig'],'interface_note'=>'Konkrete Schnittstellen hängen vom Modell ab.','media_kind'=>'sheet','paper_size'=>'A4','page_orientation'=>'portrait','margin_mm'=>8,'gap_x_mm'=>2,'gap_y_mm'=>2,'fit_mode'=>'auto','auto_rotate'=>true,'center_on_page'=>true],'Canon-Laserprofil für lasergeeignete Medien.'],
      ['LP-EPSON-INKJET','Epson Tintenstrahl · EcoTank / WorkForce / Expression','Epson','EcoTank · WorkForce · Expression','system','system_print',600,62,29,'A4/A5/A6 Etikettenbogen','portrait','inactive',['printer_class'=>'office_inkjet','technology'=>'inkjet','interfaces'=>['Systemdruck/AirPrint','USB/WLAN je nach Modell','LAN je nach Modell'],'interface_note'=>'Konkrete Schnittstellen hängen vom Modell ab.','media_kind'=>'sheet','paper_size'=>'A4','page_orientation'=>'portrait','margin_mm'=>8,'gap_x_mm'=>2,'gap_y_mm'=>2,'fit_mode'=>'auto','auto_rotate'=>true,'center_on_page'=>true],'Epson-Tintenstrahlprofil über Systemdruck.'],
      ['LP-BROTHER-INKJET','Brother Tintenstrahl · DCP/MFC','Brother','DCP/MFC Inkjet Familie','system','system_print',600,62,29,'A4/A5/A6 Etikettenbogen','portrait','inactive',['printer_class'=>'office_inkjet','technology'=>'inkjet','interfaces'=>['Systemdruck/AirPrint','USB/WLAN/LAN modellabhängig'],'interface_note'=>'Nicht QL/TD: normales Papier-/Bogenprofil über Systemdruck.','media_kind'=>'sheet','paper_size'=>'A4','page_orientation'=>'portrait','margin_mm'=>8,'gap_x_mm'=>2,'gap_y_mm'=>2,'fit_mode'=>'auto','auto_rotate'=>true,'center_on_page'=>true],'Brother-Multifunktions-/Tintenstrahldrucker.'],
      ['LP-BROTHER-LASER','Brother Laser · HL/DCP/MFC','Brother','HL/DCP/MFC Laser Familie','system','system_print',600,62,29,'A4/A5 Etikettenbogen','portrait','inactive',['printer_class'=>'office_laser','technology'=>'laser','interfaces'=>['Systemdruck/AirPrint','USB/WLAN/LAN modellabhängig'],'interface_note'=>'Nicht QL/TD: lasergeeignete Etikettenbögen über Systemdruck.','media_kind'=>'sheet','paper_size'=>'A4','page_orientation'=>'portrait','margin_mm'=>8,'gap_x_mm'=>2,'gap_y_mm'=>2,'fit_mode'=>'auto','auto_rotate'=>true,'center_on_page'=>true],'Brother-Laserdruckerprofil.'],
      ['LP-LEXMARK-LASER','Lexmark Laser','Lexmark','Laser / MFP Familie','system','system_print',600,62,29,'A4/A5 Etikettenbogen','portrait','inactive',['printer_class'=>'office_laser','technology'=>'laser','interfaces'=>['Systemdruck','USB/LAN/WLAN modellabhängig'],'interface_note'=>'Ausgabe über installierten Systemtreiber.','media_kind'=>'sheet','paper_size'=>'A4','page_orientation'=>'portrait','margin_mm'=>8,'gap_x_mm'=>2,'gap_y_mm'=>2,'fit_mode'=>'auto','auto_rotate'=>true,'center_on_page'=>true],'Lexmark Laserprofil.'],
      ['LP-XEROX-LASER','Xerox Laser / MFP','Xerox','Laser / MFP Familie','system','system_print',600,62,29,'A4/A5 Etikettenbogen','portrait','inactive',['printer_class'=>'office_laser','technology'=>'laser','interfaces'=>['Systemdruck','USB/LAN/WLAN modellabhängig'],'interface_note'=>'Ausgabe über installierten Systemtreiber.','media_kind'=>'sheet','paper_size'=>'A4','page_orientation'=>'portrait','margin_mm'=>8,'gap_x_mm'=>2,'gap_y_mm'=>2,'fit_mode'=>'auto','auto_rotate'=>true,'center_on_page'=>true],'Xerox Laser-/MFP-Profil.']
    ];
    $st=$db->prepare("INSERT IGNORE INTO label_printers(id,name,manufacturer,model,connection_type,output_mode,dpi,default_width_mm,default_height_mm,media_code,orientation,copies,status,is_default,settings_json,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,1,?,0,?,?,NOW(),NOW())");
    foreach($profiles as $x){$settings=$x[12];$row=[$x[0],$x[1],$x[2],$x[3],$x[4],$x[5],$x[6],$x[7],$x[8],$x[9],$x[10],$x[11],rh24_json_encode($settings),$x[13]];try{$st->execute($row);}catch(Throwable){}}
    // Bekannte Systemprofile auf den fachlich korrekten V96.5-Stand heben, ohne Benutzerstatus/Default zu überschreiben.
    $up=$db->prepare("UPDATE label_printers SET manufacturer=?,model=?,connection_type=?,output_mode=?,dpi=?,default_width_mm=?,default_height_mm=?,media_code=?,orientation=?,settings_json=?,notes=?,updated_at=NOW() WHERE id=?");
    foreach($profiles as $x){try{$up->execute([$x[2],$x[3],$x[4],$x[5],$x[6],$x[7],$x[8],$x[9],$x[10],rh24_json_encode($x[12]),$x[13],$x[0]]);}catch(Throwable){}}
}

function rh24_label_media_seed(): array {
    return [
      // id,name,maker,code,kind,w,h,paper,cols,rows,technology,unit,stock,min,settings
      ['LM-DK11209','Brother DK-11209 · klein','Brother','DK-11209','diecut_roll',62,29,'',1,1,'thermal','Rollen',1,1,['compatible_manufacturers'=>['Brother'],'compatible_models'=>['QL-800','QL-810W','QL-820NWB'],'purpose'=>'Produkt/Preis/Adresse','verified_size'=>true]],
      ['LM-DK11201','Brother DK-11201 · Standardadresse','Brother','DK-11201','diecut_roll',29,90,'',1,1,'thermal','Rollen',0,1,['compatible_manufacturers'=>['Brother'],'purpose'=>'Adressetikett','verified_size'=>true]],
      ['LM-DK11202','Brother DK-11202 · Versand','Brother','DK-11202','diecut_roll',62,100,'',1,1,'thermal','Rollen',0,1,['compatible_manufacturers'=>['Brother'],'purpose'=>'Versandetikett','verified_size'=>true]],
      ['LM-DK11203','Brother DK-11203 · Ordner','Brother','DK-11203','diecut_roll',17,87,'',1,1,'thermal','Rollen',0,1,['compatible_manufacturers'=>['Brother'],'purpose'=>'Ordner/Schmal','verified_size'=>true]],
      ['LM-DK11204','Brother DK-11204 · Mehrzweck','Brother','DK-11204','diecut_roll',17,54,'',1,1,'thermal','Rollen',0,1,['compatible_manufacturers'=>['Brother'],'purpose'=>'Klein/Mehrzweck','verified_size'=>true]],
      ['LM-DK11207','Brother DK-11207 · Quadrat','Brother','DK-11207','diecut_roll',58,58,'',1,1,'thermal','Rollen',0,1,['compatible_manufacturers'=>['Brother'],'purpose'=>'Quadrat/CD','verified_size'=>true]],
      ['LM-DK11208','Brother DK-11208 · große Adresse','Brother','DK-11208','diecut_roll',38,90,'',1,1,'thermal','Rollen',0,1,['compatible_manufacturers'=>['Brother'],'purpose'=>'Adresse hoch','verified_size'=>true]],
      ['LM-DK11218','Brother DK-11218 · rund 24 mm','Brother','DK-11218','diecut_roll',24,24,'',1,1,'thermal','Rollen',0,1,['compatible_manufacturers'=>['Brother'],'shape'=>'round','purpose'=>'Rund/Kennzeichnung','verified_size'=>true]],
      ['LM-DK22205','Brother DK-22205 · Endlos 62 mm','Brother','DK-22205','continuous_roll',62,29,'',1,1,'thermal','Rollen',0,1,['compatible_manufacturers'=>['Brother'],'continuous_width_mm'=>62,'length_mode'=>'auto','purpose'=>'Endlos/Banner','verified_size'=>true]],
      ['LM-DK2251','Brother DK-2251 · Schwarz/Rot Endlos','Brother','DK-2251','continuous_roll',62,29,'',1,1,'thermal_2color','Rollen',0,1,['compatible_models'=>['QL-800','QL-810W','QL-820NWB'],'continuous_width_mm'=>62,'length_mode'=>'auto','two_color'=>true,'purpose'=>'Warnung/Aktion','verified_size'=>true]],
      ['LM-BDE-76X44','Brother BDE · 76 × 44','Brother','BDE-1J044076-066','diecut_roll',76,44,'',1,1,'thermal','Rollen',0,1,['compatible_models'=>['TD-4420DN','TD-4550DNWB'],'purpose'=>'Produkt/Lager','verified_size'=>true]],
      ['LM-BDE-102X152','Brother BDE · 102 × 152','Brother','BDE-1J152102-102','diecut_roll',102,152,'',1,1,'thermal','Rollen',0,1,['compatible_models'=>['TD-4420DN','TD-4550DNWB'],'purpose'=>'Versand/Großetikett','verified_size'=>true]],
      ['LM-BDE-CONT102','Brother BDE · Endlos 102 mm','Brother','BDE-1J000102-102','continuous_roll',102,56,'',1,1,'thermal','Rollen',0,1,['compatible_models'=>['TD-4420DN','TD-4550DNWB'],'continuous_width_mm'=>102,'length_mode'=>'auto','purpose'=>'Endlos/Breit','verified_size'=>true]],
      ['LM-AV-L7159','Avery Zweckform L7159 · 63,5 × 33,9','Avery Zweckform','L7159','diecut_sheet',63.5,33.9,'A4',3,8,'laser','Bögen',0,5,['labels_per_sheet'=>24,'compatible_technologies'=>['laser'],'center_grid'=>true,'purpose'=>'Adresse','verified_size'=>true]],
      ['LM-AV-L7160','Avery Zweckform L7160 · 63,5 × 38,1','Avery Zweckform','L7160','diecut_sheet',63.5,38.1,'A4',3,7,'universal_sheet','Bögen',0,5,['labels_per_sheet'=>21,'compatible_technologies'=>['inkjet','laser'],'center_grid'=>true,'purpose'=>'Adresse/Produkt','verified_size'=>true]],
      ['LM-AV-L7163','Avery Zweckform L7163 · 99,1 × 38,1','Avery Zweckform','L7163','diecut_sheet',99.1,38.1,'A4',2,7,'universal_sheet','Bögen',0,5,['labels_per_sheet'=>14,'compatible_technologies'=>['inkjet','laser'],'center_grid'=>true,'purpose'=>'Adresse','verified_size'=>true]],
      ['LM-AV-L7165','Avery Zweckform L7165 · 99,1 × 67,7','Avery Zweckform','L7165','diecut_sheet',99.1,67.7,'A4',2,4,'universal_sheet','Bögen',0,5,['labels_per_sheet'=>8,'compatible_technologies'=>['inkjet','laser'],'center_grid'=>true,'purpose'=>'Versand','verified_size'=>true]],
      ['LM-AV-L7167','Avery Zweckform L7167 · 199,6 × 289,1','Avery Zweckform','L7167','diecut_sheet',199.6,289.1,'A4',1,1,'universal_sheet','Bögen',0,5,['labels_per_sheet'=>1,'compatible_technologies'=>['inkjet','laser'],'center_grid'=>true,'purpose'=>'Großversand','verified_size'=>true]],
      ['LM-AV-3652','Avery Zweckform 3652 · 70 × 42,3','Avery Zweckform','3652','diecut_sheet',70,42.3,'A4',3,7,'universal_sheet','Bögen',0,5,['labels_per_sheet'=>21,'compatible_technologies'=>['inkjet','laser'],'center_grid'=>true,'purpose'=>'Universal/Produkt','verified_size'=>true]],
      ['LM-GEN-A4','A4 Normalpapier','Generic','A4','plain_sheet',62,29,'A4',0,0,'universal','Blatt',100,20,['compatible_technologies'=>['inkjet','laser','universal'],'auto_grid'=>true,'margin_mm'=>8,'gap_x_mm'=>3,'gap_y_mm'=>3,'purpose'=>'Test/Normaldruck']],
      ['LM-GEN-A5','A5 Normalpapier','Generic','A5','plain_sheet',62,29,'A5',0,0,'universal','Blatt',20,10,['compatible_technologies'=>['inkjet','laser','universal'],'auto_grid'=>true,'margin_mm'=>6,'gap_x_mm'=>3,'gap_y_mm'=>3,'purpose'=>'Test/Normaldruck']],
      ['LM-GEN-A6','A6 Normalpapier','Generic','A6','plain_sheet',62,29,'A6',0,0,'universal','Blatt',20,10,['compatible_technologies'=>['inkjet','laser','universal'],'auto_grid'=>true,'margin_mm'=>5,'gap_x_mm'=>2,'gap_y_mm'=>2,'purpose'=>'Karte/Test']],
      ['LM-GEN-50X30','Universalrolle 50 × 30','Generic','50x30','diecut_roll',50,30,'',1,1,'thermal','Rollen',0,1,['compatible_technologies'=>['thermal','direct_thermal'],'purpose'=>'Produkt/Preis']],
      ['LM-GEN-60X40','Universalrolle 60 × 40','Generic','60x40','diecut_roll',60,40,'',1,1,'thermal','Rollen',0,1,['compatible_technologies'=>['thermal','direct_thermal'],'purpose'=>'Produkt/Lager']],
      ['LM-GEN-100X50','Universalrolle 100 × 50','Generic','100x50','diecut_roll',100,50,'',1,1,'thermal','Rollen',0,1,['compatible_technologies'=>['thermal','direct_thermal','inkjet_label'],'purpose'=>'Produkt/Lager']],
      ['LM-GEN-100X150','Versandrolle 100 × 150','Generic','100x150','diecut_roll',100,150,'',1,1,'thermal','Rollen',0,1,['compatible_technologies'=>['thermal','direct_thermal','inkjet_label'],'purpose'=>'Versand']],
      ['LM-GEN-CONT62','Endlosrolle 62 mm','Generic','CONT-62','continuous_roll',62,29,'',1,1,'thermal','Rollen',0,1,['compatible_technologies'=>['thermal','direct_thermal'],'continuous_width_mm'=>62,'length_mode'=>'auto','purpose'=>'Endlos']],
      ['LM-GEN-CONT100','Endlosrolle 100 mm','Generic','CONT-100','continuous_roll',100,50,'',1,1,'thermal','Rollen',0,1,['compatible_technologies'=>['thermal','direct_thermal','inkjet_label'],'continuous_width_mm'=>100,'length_mode'=>'auto','purpose'=>'Endlos/Breit']]
    ];
}
function rh24_seed_v965_media(PDO $db): void {
    $st=$db->prepare("INSERT INTO label_media(id,name,manufacturer,media_code,media_kind,width_mm,height_mm,paper_size,`cols`,`rows`,technology,unit_name,stock_units,min_stock_units,settings_json,is_system,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,'active',NOW(),NOW()) ON DUPLICATE KEY UPDATE name=VALUES(name),manufacturer=VALUES(manufacturer),media_code=VALUES(media_code),media_kind=VALUES(media_kind),width_mm=VALUES(width_mm),height_mm=VALUES(height_mm),paper_size=VALUES(paper_size),`cols`=VALUES(`cols`),`rows`=VALUES(`rows`),technology=VALUES(technology),unit_name=VALUES(unit_name),settings_json=VALUES(settings_json),is_system=1,status='active',updated_at=NOW()");
    foreach(rh24_label_media_seed() as $m){try{$st->execute([$m[0],$m[1],$m[2],$m[3],$m[4],$m[5],$m[6],$m[7],$m[8],$m[9],$m[10],$m[11],$m[12],$m[13],rh24_json_encode($m[14])]);}catch(Throwable){}}
}
function rh24_label_media_compatible(array $media,array $printer): bool {
    if(($media['status']??'')!=='active'||($printer['status']??'')!=='active')return false;
    $ms=is_array($media['settings']??null)?$media['settings']:rh24_json_decode((string)($media['settings_json']??''),[]);
    $ps=is_array($printer['settings']??null)?$printer['settings']:rh24_json_decode((string)($printer['settings_json']??''),[]);
    $pc=strtolower((string)($ps['printer_class']??''));$pt=strtolower((string)($ps['technology']??'universal'));$pm=strtolower((string)($printer['manufacturer']??''));$mm=strtolower((string)($media['manufacturer']??''));$model=strtolower((string)($printer['model']??''));
    if($mm==='brother'&&str_starts_with((string)($media['media_code']??''),'DK-')&&!str_contains($pc,'label'))return false;
    $models=array_map(fn($v)=>strtolower((string)$v),is_array($ms['compatible_models']??null)?$ms['compatible_models']:[]);if($models)return in_array($model,$models,true);
    $makers=array_map(fn($v)=>strtolower((string)$v),is_array($ms['compatible_manufacturers']??null)?$ms['compatible_manufacturers']:[]);
    $tech=array_map(fn($v)=>strtolower((string)$v),is_array($ms['compatible_technologies']??null)?$ms['compatible_technologies']:[]);
    $kind=(string)($media['media_kind']??'');
    if(in_array($kind,['diecut_sheet','plain_sheet'],true)){
        $office=str_starts_with($pc,'office')||$pc==='office'||$pc===''||in_array($pt,['universal','inkjet','laser'],true);if(!$office)return false;
        if($tech&&!in_array('universal',$tech,true)){ $ok=false;foreach($tech as $t){if(str_contains($pt,$t)||str_contains($t,$pt)||$pt==='universal'){$ok=true;break;}}if(!$ok)return false; }
        if($makers&&!in_array($pm,$makers,true))return false;return true;
    }
    if(str_starts_with($pc,'office'))return false;if($makers)return in_array($pm,$makers,true);
    if($tech){foreach($tech as $t)if(str_contains($pt,$t)||str_contains($t,$pt))return true;return false;}
    return $mm==='generic'||$mm===$pm;
}

function rh24_label_media(): array {
    $rows=rh24_db()->query("SELECT * FROM label_media WHERE status<>'deleted' ORDER BY manufacturer,name")->fetchAll();
    foreach($rows as &$r){$r['width_mm']=(float)$r['width_mm'];$r['height_mm']=(float)$r['height_mm'];$r['cols']=(int)$r['cols'];$r['rows']=(int)$r['rows'];$r['stock_units']=(float)$r['stock_units'];$r['min_stock_units']=(float)$r['min_stock_units'];$r['is_system']=(bool)$r['is_system'];$r['settings']=rh24_json_decode((string)($r['settings_json']??''),[]);unset($r['settings_json']);}unset($r);return $rows;
}
function rh24_ensure_v96_label_schema(PDO $db): void {
    $db->exec("CREATE TABLE IF NOT EXISTS label_printers (
      id VARCHAR(60) NOT NULL PRIMARY KEY, name VARCHAR(160) NOT NULL, manufacturer VARCHAR(80) NOT NULL DEFAULT 'Generic', model VARCHAR(160) NOT NULL DEFAULT '', connection_type VARCHAR(30) NOT NULL DEFAULT 'system', output_mode VARCHAR(30) NOT NULL DEFAULT 'system_print', bridge_url VARCHAR(500) NOT NULL DEFAULT '', bridge_token VARCHAR(500) NOT NULL DEFAULT '', dpi SMALLINT UNSIGNED NOT NULL DEFAULT 300, default_width_mm DECIMAL(7,2) NOT NULL DEFAULT 62.00, default_height_mm DECIMAL(7,2) NOT NULL DEFAULT 29.00, media_code VARCHAR(80) NOT NULL DEFAULT '', orientation VARCHAR(20) NOT NULL DEFAULT 'landscape', copies SMALLINT UNSIGNED NOT NULL DEFAULT 1, darkness SMALLINT NOT NULL DEFAULT 0, speed SMALLINT NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL DEFAULT 'active', is_default TINYINT(1) NOT NULL DEFAULT 0, settings_json LONGTEXT NULL, notes VARCHAR(500) NOT NULL DEFAULT '', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, KEY idx_label_printer_status(status,is_default)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    $db->exec("CREATE TABLE IF NOT EXISTS label_media (
      id VARCHAR(60) NOT NULL PRIMARY KEY, name VARCHAR(180) NOT NULL, manufacturer VARCHAR(80) NOT NULL DEFAULT 'Generic', media_code VARCHAR(80) NOT NULL DEFAULT '', media_kind VARCHAR(30) NOT NULL DEFAULT 'diecut_roll', width_mm DECIMAL(7,2) NOT NULL DEFAULT 62.00, height_mm DECIMAL(7,2) NOT NULL DEFAULT 29.00, paper_size VARCHAR(30) NOT NULL DEFAULT '', `cols` SMALLINT UNSIGNED NOT NULL DEFAULT 0, `rows` SMALLINT UNSIGNED NOT NULL DEFAULT 0, technology VARCHAR(40) NOT NULL DEFAULT 'universal', unit_name VARCHAR(30) NOT NULL DEFAULT 'Stück', stock_units DECIMAL(10,2) NOT NULL DEFAULT 0.00, min_stock_units DECIMAL(10,2) NOT NULL DEFAULT 0.00, settings_json LONGTEXT NULL, is_system TINYINT(1) NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, KEY idx_label_media_kind(media_kind,status), KEY idx_label_media_stock(stock_units,min_stock_units)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    $db->exec("CREATE TABLE IF NOT EXISTS label_templates (
      id VARCHAR(60) NOT NULL PRIMARY KEY, name VARCHAR(160) NOT NULL, category VARCHAR(50) NOT NULL DEFAULT 'product', width_mm DECIMAL(7,2) NOT NULL DEFAULT 62.00, height_mm DECIMAL(7,2) NOT NULL DEFAULT 29.00, orientation VARCHAR(20) NOT NULL DEFAULT 'landscape', layout_json LONGTEXT NOT NULL, is_system TINYINT(1) NOT NULL DEFAULT 0, is_favorite TINYINT(1) NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL DEFAULT 'active', created_by VARCHAR(60) NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, KEY idx_label_template_cat(category,status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    $db->exec("CREATE TABLE IF NOT EXISTS label_jobs (
      id VARCHAR(60) NOT NULL PRIMARY KEY, job_no VARCHAR(80) NOT NULL, template_id VARCHAR(60) NULL, printer_id VARCHAR(60) NULL, job_type VARCHAR(40) NOT NULL DEFAULT 'single', status VARCHAR(30) NOT NULL DEFAULT 'draft', source_type VARCHAR(40) NOT NULL DEFAULT 'manual', source_ref VARCHAR(100) NOT NULL DEFAULT '', label_count INT UNSIGNED NOT NULL DEFAULT 0, copy_count SMALLINT UNSIGNED NOT NULL DEFAULT 1, payload_json LONGTEXT NULL, error_message VARCHAR(700) NOT NULL DEFAULT '', printed_by VARCHAR(60) NULL, printed_at DATETIME NULL, created_by VARCHAR(60) NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE KEY uq_label_job_no(job_no), KEY idx_label_job_status(status,created_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    $db->exec("CREATE TABLE IF NOT EXISTS label_job_items (
      id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, job_id VARCHAR(60) NOT NULL, line_no INT UNSIGNED NOT NULL, copies SMALLINT UNSIGNED NOT NULL DEFAULT 1, data_json LONGTEXT NOT NULL, created_at DATETIME NOT NULL, KEY idx_label_job_item(job_id,line_no)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    try{$cnt=(int)$db->query('SELECT COUNT(*) FROM label_printers')->fetchColumn();if($cnt===0){
      $st=$db->prepare("INSERT INTO label_printers(id,name,manufacturer,model,connection_type,output_mode,dpi,default_width_mm,default_height_mm,media_code,orientation,copies,status,is_default,settings_json,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,1,'active',1,?,?,NOW(),NOW())");
      $st->execute(['LP-QL800','Brother QL-800','Brother','QL-800','usb/system','system_print',300,62,29,'DK-11209 / DK-Rolle','landscape',rh24_json_encode(['supports_red_black'=>true,'recommended_driver'=>'Brother macOS/Windows Treiber','direct_mode_note'=>'Universell über Systemdruck/PDF; optionale lokale Bridge für Direktdruck.']),'V96 Startprofil passend zum vorhandenen Brother QL-800.']);
    }}catch(Throwable){}
    try{rh24_seed_v965_printer_profiles($db);}catch(Throwable){}
    try{rh24_seed_v965_media($db);}catch(Throwable){}
    $templateSetReady=false;
    try{
      $st=$db->prepare("INSERT INTO label_templates(id,name,category,width_mm,height_mm,orientation,layout_json,is_system,is_favorite,status,created_by,created_at,updated_at)
        VALUES(?,?,?,?,?,?,?,1,?,'active',NULL,NOW(),NOW())
        ON DUPLICATE KEY UPDATE name=VALUES(name),category=VALUES(category),width_mm=VALUES(width_mm),height_mm=VALUES(height_mm),orientation=VALUES(orientation),layout_json=VALUES(layout_json),is_system=1,status='active',updated_at=NOW()");
      foreach(rh24_label_system_templates_v964() as $t){
        $st->execute([$t['id'],$t['name'],$t['category'],$t['width_mm'],$t['height_mm'],$t['orientation'],rh24_json_encode($t['layout']),$t['favorite']]);
      }
      $q=$db->query("SELECT COUNT(*) FROM label_templates WHERE is_system=1 AND status='active'");
      $templateSetReady=((int)$q->fetchColumn()>=100);
    }catch(Throwable){}
    $mediaReady=false;try{$mediaReady=((int)$db->query("SELECT COUNT(*) FROM label_media WHERE status='active'")->fetchColumn()>=20);}catch(Throwable){}
    rh24_setting_set('label_schema_version',($templateSetReady&&$mediaReady)?'965':'96');
}
function rh24_label_ensure_ready(): array {$db=rh24_db();$h=rh24_label_schema_health($db);$tplCount=0;$mediaCount=0;try{$tplCount=(int)$db->query("SELECT COUNT(*) FROM label_templates WHERE is_system=1 AND status='active'")->fetchColumn();}catch(Throwable){}try{$mediaCount=(int)$db->query("SELECT COUNT(*) FROM label_media WHERE status='active'")->fetchColumn();}catch(Throwable){}if(!$h['ready']||((int)($h['version']??0)<965)||$tplCount<100||$mediaCount<20){rh24_ensure_v96_label_schema($db);$h=rh24_label_schema_health($db);}return $h;}
function rh24_label_printers(): array {$rows=rh24_db()->query('SELECT * FROM label_printers ORDER BY is_default DESC,status DESC,name')->fetchAll();foreach($rows as &$r){$r['dpi']=(int)$r['dpi'];$r['default_width_mm']=(float)$r['default_width_mm'];$r['default_height_mm']=(float)$r['default_height_mm'];$r['copies']=(int)$r['copies'];$r['is_default']=(bool)$r['is_default'];$r['settings']=rh24_json_decode((string)($r['settings_json']??''),[]);unset($r['settings_json'],$r['bridge_token']);}unset($r);return $rows;}
function rh24_label_templates(): array {$rows=rh24_db()->query("SELECT * FROM label_templates WHERE status<>'deleted' ORDER BY is_favorite DESC,is_system DESC,name")->fetchAll();foreach($rows as &$r){$r['width_mm']=(float)$r['width_mm'];$r['height_mm']=(float)$r['height_mm'];$r['is_system']=(bool)$r['is_system'];$r['is_favorite']=(bool)$r['is_favorite'];$r['layout']=rh24_json_decode((string)$r['layout_json'],[]);unset($r['layout_json']);}unset($r);return $rows;}
function rh24_label_jobs(int $limit=100): array {$limit=max(1,min(300,$limit));$rows=rh24_db()->query("SELECT j.*,t.name template_name,p.name printer_name,u.display_name created_by_name FROM label_jobs j LEFT JOIN label_templates t ON t.id=j.template_id LEFT JOIN label_printers p ON p.id=j.printer_id LEFT JOIN users u ON u.id=j.created_by ORDER BY j.created_at DESC LIMIT {$limit}")->fetchAll();foreach($rows as &$r){$r['label_count']=(int)$r['label_count'];$r['copy_count']=(int)$r['copy_count'];$r['payload']=rh24_json_decode((string)($r['payload_json']??''),[]);unset($r['payload_json']);$r['created_at']=rh24_iso($r['created_at']);$r['printed_at']=rh24_iso($r['printed_at']);}unset($r);return $rows;}
function rh24_label_job_detail(string $id): array {$q=rh24_db()->prepare('SELECT * FROM label_jobs WHERE id=?');$q->execute([$id]);$job=$q->fetch();if(!$job)throw new RuntimeException('Druckauftrag nicht gefunden.');$q=rh24_db()->prepare('SELECT * FROM label_job_items WHERE job_id=? ORDER BY line_no');$q->execute([$id]);$items=$q->fetchAll();foreach($items as &$i){$i['copies']=(int)$i['copies'];$i['data']=rh24_json_decode((string)$i['data_json'],[]);unset($i['data_json']);}unset($i);$job['payload']=rh24_json_decode((string)($job['payload_json']??''),[]);unset($job['payload_json']);$job['items']=$items;return $job;}
function rh24_label_next_job_no(): string {$db=rh24_db();$key='label_next_job_no';$n=(int)rh24_setting_get($key,'1');rh24_setting_set($key,(string)($n+1));return 'LBL-'.date('Ymd').'-'.str_pad((string)$n,5,'0',STR_PAD_LEFT);}
function rh24_label_data(): array {
    rh24_label_ensure_ready();
    // V105.4: Produktdaten vor der Übergabe an das Etikettenstudio härten.
    // Alte/teilweise Datensätze dürfen keine leeren Auswahlkarten mehr erzeugen.
    $catalog=[];$defaults=rh24_default_catalog();
    foreach(rh24_catalog() as $id=>$p){
        $fb=$defaults[(string)$id]??[];
        $name=trim((string)($p['name']??$fb['name']??''));
        $sku=trim((string)($p['sku']??$fb['sku']??''));
        $article=trim((string)($p['article_no']??$fb['article_no']??''));
        $barcode=trim((string)($p['barcode']??$fb['barcode']??''));
        $pid=trim((string)$id);
        if($name==='')$name=trim((string)($fb['name']??''));
        if($name==='')$name=$article!==''?'Artikel '.$article:($sku!==''?'Artikel '.$sku:($pid!==''?'Artikel '.$pid:''));
        if($pid===''&&$name===''&&$sku===''&&$article===''&&$barcode==='')continue;
        $catalog[]=[
          'id'=>$pid!==''?$pid:($sku!==''?$sku:($article!==''?$article:$barcode)),
          'name'=>$name!==''?$name:'Unbenannter Artikel',
          'sku'=>$sku,'article_no'=>$article,'barcode'=>$barcode,
          'category'=>(string)($p['category']??$fb['category']??''),
          'price'=>(float)($p['effective_price']??$p['base']??$fb['base']??0),
          'unit'=>(string)($p['unit']??$fb['unit']??''),
          'stock'=>(int)($p['stock']??$fb['stock']??0),
          'minimum'=>(int)($p['minimum']??$fb['minimum']??0),
          'image'=>(string)($p['image']??$fb['image']??'')
        ];
    }
    usort($catalog,static fn(array $a,array $b)=>strnatcasecmp(($a['category']??'').' '.($a['name']??''),($b['category']??'').' '.($b['name']??'')));
    $customers=[];try{$rows=rh24_db()->query("SELECT id,name,company,street,zip,city,country,email,phone FROM customers ORDER BY updated_at DESC LIMIT 1000")->fetchAll();foreach($rows as $c)$customers[]=['id'=>$c['id'],'name'=>$c['name'],'company'=>$c['company'],'street'=>$c['street'],'zip'=>$c['zip'],'city'=>$c['city'],'country'=>$c['country']?:'Deutschland','email'=>$c['email'],'phone'=>$c['phone']];}catch(Throwable){}
    $orders=[];try{$rows=rh24_db()->query("SELECT order_no,customer_json,carrier,tracking,status FROM orders ORDER BY created_at DESC LIMIT 250")->fetchAll();foreach($rows as $o)$orders[]=['order_no'=>$o['order_no'],'customer'=>rh24_json_decode((string)$o['customer_json'],[]),'carrier'=>$o['carrier'],'tracking'=>$o['tracking'],'status'=>$o['status']];}catch(Throwable){}
    return ['schema'=>rh24_label_schema_health(rh24_db()),'printers'=>rh24_label_printers(),'media'=>rh24_label_media(),'templates'=>rh24_label_templates(),'jobs'=>rh24_label_jobs(),'products'=>$catalog,'customers'=>$customers,'orders'=>$orders,'settings'=>['default_printer'=>(string)rh24_setting_get('label_default_printer',''),'default_template'=>(string)rh24_setting_get('label_default_template','LT-PROD'),'auto_price_decimals'=>(int)rh24_setting_get('label_price_decimals','2'),'company_name'=>(string)rh24_setting_get('invoice_company_name','Räucherhaken24')]];
}
