<?php
declare(strict_types=1);
require __DIR__ . '/bootstrap.php';
rh24_require_login();
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
function lbl_out(array $d,int $status=200): never {http_response_code($status);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function lbl_body(): array {$d=json_decode(file_get_contents('php://input')?:'{}',true);return is_array($d)?$d:[];}
function lbl_require(string $p): void {if(!rh24_can($p))lbl_out(['ok'=>false,'error'=>'Für diese Etikettenfunktion fehlt die Berechtigung: '.$p],403);}
function lbl_num(mixed $v,float $min,float $max,float $def): float {$n=(float)str_replace(',','.',trim((string)$v));return ($n<$min||$n>$max)?$def:$n;}
$d=lbl_body();rh24_verify_csrf($_SERVER['HTTP_X_CSRF_TOKEN']??($d['csrf']??null));$action=(string)($d['action']??'data');
try{
  rh24_label_ensure_ready();$db=rh24_db();
  if($action==='data'){lbl_require('view_labels');lbl_out(['ok'=>true,'data'=>rh24_label_data(),'csrf'=>rh24_csrf()]);}
  if($action==='template_save'){
    lbl_require('edit_labels');$id=trim((string)($d['id']??''))?:rh24_random_id('LT-');$name=substr(trim((string)($d['name']??'')),0,160);if($name==='')throw new InvalidArgumentException('Vorlagenname ist erforderlich.');$cat=(string)($d['category']??'product');if(!in_array($cat,['product','price','warehouse','shipping','address','batch','custom'],true))$cat='custom';$w=lbl_num($d['width_mm']??62,12,220,62);$h=lbl_num($d['height_mm']??29,12,320,29);$ori=in_array(($d['orientation']??'landscape'),['landscape','portrait'],true)?$d['orientation']:'landscape';$layout=is_array($d['layout']??null)?$d['layout']:[];$fav=!empty($d['is_favorite'])?1:0;
    $q=$db->prepare('SELECT id,is_system FROM label_templates WHERE id=?');$q->execute([$id]);$row=$q->fetch();if($row){$db->prepare("UPDATE label_templates SET name=?,category=?,width_mm=?,height_mm=?,orientation=?,layout_json=?,is_favorite=?,status='active',updated_at=NOW() WHERE id=?")->execute([$name,$cat,$w,$h,$ori,rh24_json_encode($layout),$fav,$id]);}else{$db->prepare("INSERT INTO label_templates(id,name,category,width_mm,height_mm,orientation,layout_json,is_system,is_favorite,status,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,0,?,'active',?,NOW(),NOW())")->execute([$id,$name,$cat,$w,$h,$ori,rh24_json_encode($layout),$fav,rh24_user_id()]);}
    rh24_audit('label_template_save','label_template',$id,['name'=>$name,'category'=>$cat,'size'=>$w.'x'.$h]);lbl_out(['ok'=>true,'data'=>rh24_label_data()]);
  }
  if($action==='template_delete'){
    lbl_require('edit_labels');$id=trim((string)($d['id']??''));$q=$db->prepare('SELECT is_system FROM label_templates WHERE id=?');$q->execute([$id]);$system=(int)$q->fetchColumn();if($system)throw new RuntimeException('Systemvorlagen können nicht gelöscht werden. Bitte duplizieren und eine eigene Vorlage bearbeiten.');$db->prepare("UPDATE label_templates SET status='deleted',updated_at=NOW() WHERE id=?")->execute([$id]);rh24_audit('label_template_delete','label_template',$id,[]);lbl_out(['ok'=>true,'data'=>rh24_label_data()]);
  }
  if($action==='printer_save'){
    lbl_require('manage_labels');$id=trim((string)($d['id']??''))?:rh24_random_id('LP-');$name=substr(trim((string)($d['name']??'')),0,160);if($name==='')throw new InvalidArgumentException('Druckername ist erforderlich.');$manufacturer=substr(trim((string)($d['manufacturer']??'Generic')),0,80);$model=substr(trim((string)($d['model']??'')),0,160);$conn=(string)($d['connection_type']??'system');$mode=(string)($d['output_mode']??'system_print');if(!in_array($conn,['system','usb/system','network','bluetooth/system','local_bridge','webserial'],true))$conn='system';if(!in_array($mode,['system_print','pdf','bridge_zpl','bridge_tspl','bridge_brother','bridge_raw'],true))$mode='system_print';$url=substr(trim((string)($d['bridge_url']??'')),0,500);if(str_starts_with($mode,'bridge_')&&$url!==''&&!preg_match('#^https?://#i',$url))throw new InvalidArgumentException('Bridge-Adresse muss mit http:// oder https:// beginnen.');$dpi=(int)lbl_num($d['dpi']??300,150,1200,300);$w=lbl_num($d['default_width_mm']??62,12,220,62);$h=lbl_num($d['default_height_mm']??29,12,320,29);$media=substr(trim((string)($d['media_code']??'')),0,80);$ori=in_array(($d['orientation']??'landscape'),['landscape','portrait'],true)?$d['orientation']:'landscape';$status=in_array(($d['status']??'active'),['active','inactive'],true)?$d['status']:'active';$isDefault=!empty($d['is_default'])?1:0;$settings=is_array($d['settings']??null)?$d['settings']:[];$notes=substr(trim((string)($d['notes']??'')),0,500);$token=trim((string)($d['bridge_token']??''));
    if($isDefault)$db->exec('UPDATE label_printers SET is_default=0');$q=$db->prepare('SELECT id,bridge_token FROM label_printers WHERE id=?');$q->execute([$id]);$old=$q->fetch();if($old){$token=$token!==''?$token:(string)$old['bridge_token'];$db->prepare("UPDATE label_printers SET name=?,manufacturer=?,model=?,connection_type=?,output_mode=?,bridge_url=?,bridge_token=?,dpi=?,default_width_mm=?,default_height_mm=?,media_code=?,orientation=?,status=?,is_default=?,settings_json=?,notes=?,updated_at=NOW() WHERE id=?")->execute([$name,$manufacturer,$model,$conn,$mode,$url,$token,$dpi,$w,$h,$media,$ori,$status,$isDefault,rh24_json_encode($settings),$notes,$id]);}else{$db->prepare("INSERT INTO label_printers(id,name,manufacturer,model,connection_type,output_mode,bridge_url,bridge_token,dpi,default_width_mm,default_height_mm,media_code,orientation,copies,status,is_default,settings_json,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,1,?,?,?, ?,NOW(),NOW())")->execute([$id,$name,$manufacturer,$model,$conn,$mode,$url,$token,$dpi,$w,$h,$media,$ori,$status,$isDefault,rh24_json_encode($settings),$notes]);}
    if($isDefault)rh24_setting_set('label_default_printer',$id);rh24_audit('label_printer_save','label_printer',$id,['manufacturer'=>$manufacturer,'model'=>$model,'mode'=>$mode]);lbl_out(['ok'=>true,'data'=>rh24_label_data()]);
  }
  if($action==='printer_delete'){
    lbl_require('manage_labels');$id=trim((string)($d['id']??''));$db->prepare("UPDATE label_printers SET status='inactive',is_default=0,updated_at=NOW() WHERE id=?")->execute([$id]);rh24_audit('label_printer_disable','label_printer',$id,[]);lbl_out(['ok'=>true,'data'=>rh24_label_data()]);
  }
  if($action==='media_save'){
    lbl_require('manage_labels');$id=trim((string)($d['id']??''))?:rh24_random_id('LM-');$name=substr(trim((string)($d['name']??'')),0,180);if($name==='')throw new InvalidArgumentException('Medienname ist erforderlich.');$maker=substr(trim((string)($d['manufacturer']??'Generic')),0,80);$code=substr(trim((string)($d['media_code']??'')),0,80);$kind=(string)($d['media_kind']??'diecut_roll');if(!in_array($kind,['diecut_roll','continuous_roll','diecut_sheet','plain_sheet'],true))$kind='diecut_roll';$w=lbl_num($d['width_mm']??62,5,320,62);$h=lbl_num($d['height_mm']??29,5,500,29);$paper=substr(trim((string)($d['paper_size']??'')),0,30);$cols=max(0,min(20,(int)($d['cols']??0)));$rows=max(0,min(40,(int)($d['rows']??0)));$tech=substr(trim((string)($d['technology']??'universal')),0,40);$unit=substr(trim((string)($d['unit_name']??'Stück')),0,30);$stock=lbl_num($d['stock_units']??0,0,999999,0);$min=lbl_num($d['min_stock_units']??0,0,999999,0);$settings=is_array($d['settings']??null)?$d['settings']:[];$status=in_array(($d['status']??'active'),['active','inactive'],true)?$d['status']:'active';
    $q=$db->prepare('SELECT id,is_system FROM label_media WHERE id=?');$q->execute([$id]);$old=$q->fetch();if($old){$db->prepare("UPDATE label_media SET name=?,manufacturer=?,media_code=?,media_kind=?,width_mm=?,height_mm=?,paper_size=?,`cols`=?,`rows`=?,technology=?,unit_name=?,stock_units=?,min_stock_units=?,settings_json=?,status=?,updated_at=NOW() WHERE id=?")->execute([$name,$maker,$code,$kind,$w,$h,$paper,$cols,$rows,$tech,$unit,$stock,$min,rh24_json_encode($settings),$status,$id]);}else{$db->prepare("INSERT INTO label_media(id,name,manufacturer,media_code,media_kind,width_mm,height_mm,paper_size,`cols`,`rows`,technology,unit_name,stock_units,min_stock_units,settings_json,is_system,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0,?,NOW(),NOW())")->execute([$id,$name,$maker,$code,$kind,$w,$h,$paper,$cols,$rows,$tech,$unit,$stock,$min,rh24_json_encode($settings),$status]);}
    rh24_audit('label_media_save','label_media',$id,['name'=>$name,'kind'=>$kind,'size'=>$w.'x'.$h]);lbl_out(['ok'=>true,'data'=>rh24_label_data()]);
  }
  if($action==='media_stock'){
    lbl_require('manage_labels');$id=trim((string)($d['id']??''));$stock=lbl_num($d['stock_units']??0,0,999999,0);$min=lbl_num($d['min_stock_units']??0,0,999999,0);$q=$db->prepare("UPDATE label_media SET stock_units=?,min_stock_units=?,updated_at=NOW() WHERE id=?");$q->execute([$stock,$min,$id]);if(!$q->rowCount())throw new InvalidArgumentException('Medium nicht gefunden.');rh24_audit('label_media_stock','label_media',$id,['stock'=>$stock,'minimum'=>$min]);lbl_out(['ok'=>true,'data'=>rh24_label_data()]);
  }
  if($action==='media_delete'){
    lbl_require('manage_labels');$id=trim((string)($d['id']??''));$q=$db->prepare('SELECT is_system FROM label_media WHERE id=?');$q->execute([$id]);$isSystem=(int)$q->fetchColumn();if($isSystem){$db->prepare("UPDATE label_media SET status='inactive',updated_at=NOW() WHERE id=?")->execute([$id]);}else{$db->prepare("UPDATE label_media SET status='deleted',updated_at=NOW() WHERE id=?")->execute([$id]);}rh24_audit('label_media_disable','label_media',$id,[]);lbl_out(['ok'=>true,'data'=>rh24_label_data()]);
  }
  if($action==='job_create'){
    lbl_require('print_labels');$templateId=trim((string)($d['template_id']??''));$printerId=trim((string)($d['printer_id']??''));$items=is_array($d['items']??null)?$d['items']:[];if(!$items)throw new InvalidArgumentException('Mindestens ein Etikett ist erforderlich.');if(count($items)>1000)throw new InvalidArgumentException('Maximal 1000 Etikettenpositionen pro Auftrag.');$q=$db->prepare("SELECT id FROM label_templates WHERE id=? AND status='active'");$q->execute([$templateId]);if(!$q->fetchColumn())throw new InvalidArgumentException('Vorlage nicht gefunden.');if($printerId!==''){$q=$db->prepare("SELECT id FROM label_printers WHERE id=? AND status='active'");$q->execute([$printerId]);if(!$q->fetchColumn())throw new InvalidArgumentException('Druckerprofil ist nicht aktiv.');}$id=rh24_random_id('LJOB-');$no=rh24_label_next_job_no();$sourceType=substr(trim((string)($d['source_type']??'manual')),0,40);$sourceRef=substr(trim((string)($d['source_ref']??'')),0,100);$payload=is_array($d['payload']??null)?$d['payload']:[];$mediaId=trim((string)($payload['media_id']??''));if($mediaId!==''){$q=$db->prepare("SELECT * FROM label_media WHERE id=? AND status='active'");$q->execute([$mediaId]);$mediaRow=$q->fetch();if(!$mediaRow)throw new InvalidArgumentException('Gewähltes Druckmedium ist nicht aktiv.');if($printerId!==''){$q=$db->prepare("SELECT * FROM label_printers WHERE id=? AND status='active'");$q->execute([$printerId]);$printerRow=$q->fetch();if(!$printerRow||!rh24_label_media_compatible($mediaRow,$printerRow))throw new InvalidArgumentException('Das gewählte Druckmedium passt nicht zum ausgewählten Druckerprofil.');}$payload['media_id']=$mediaId;}$total=0;foreach($items as $it)$total+=max(1,min(999,(int)($it['copies']??1)));$db->beginTransaction();try{$db->prepare("INSERT INTO label_jobs(id,job_no,template_id,printer_id,job_type,status,source_type,source_ref,label_count,copy_count,payload_json,created_by,created_at,updated_at) VALUES(?,?,?,?,'batch','ready',?,?,?,1,?,?,NOW(),NOW())")->execute([$id,$no,$templateId,$printerId?:null,$sourceType,$sourceRef,$total,rh24_json_encode($payload),rh24_user_id()]);$st=$db->prepare('INSERT INTO label_job_items(job_id,line_no,copies,data_json,created_at) VALUES(?,?,?,?,NOW())');$ln=0;foreach($items as $it){$ln++;$copies=max(1,min(999,(int)($it['copies']??1)));$data=is_array($it['data']??null)?$it['data']:[];$st->execute([$id,$ln,$copies,rh24_json_encode($data)]);} $db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}rh24_audit('label_job_create','label_job',$id,['job_no'=>$no,'labels'=>$total]);lbl_out(['ok'=>true,'job'=>rh24_label_job_detail($id),'print_url'=>'label-print.php?id='.rawurlencode($id)]);
  }
  if($action==='job_mark_printed'){
    lbl_require('print_labels');$id=trim((string)($d['id']??''));$db->prepare("UPDATE label_jobs SET status='printed',printed_by=?,printed_at=NOW(),updated_at=NOW() WHERE id=?")->execute([rh24_user_id(),$id]);rh24_audit('label_job_printed','label_job',$id,[]);lbl_out(['ok'=>true,'data'=>rh24_label_data()]);
  }
  if($action==='job_reprint'){
    lbl_require('print_labels');$id=trim((string)($d['id']??''));$job=rh24_label_job_detail($id);rh24_audit('label_job_reprint','label_job',$id,['job_no'=>$job['job_no']]);lbl_out(['ok'=>true,'job'=>$job,'print_url'=>'label-print.php?id='.rawurlencode($id).'&reprint=1']);
  }
  if($action==='settings_save'){
    lbl_require('manage_labels');$p=trim((string)($d['default_printer']??''));$t=trim((string)($d['default_template']??''));if($p!=='')rh24_setting_set('label_default_printer',$p);if($t!=='')rh24_setting_set('label_default_template',$t);rh24_setting_set('label_price_decimals',(string)max(0,min(4,(int)($d['price_decimals']??2))));rh24_audit('label_settings_save','label_settings','global',['printer'=>$p,'template'=>$t]);lbl_out(['ok'=>true,'data'=>rh24_label_data()]);
  }
  throw new RuntimeException('Unbekannte Etikettenaktion.');
}catch(InvalidArgumentException $e){lbl_out(['ok'=>false,'error'=>$e->getMessage()],422);}catch(Throwable $e){error_log('RH24 LABEL API: '.$e->getMessage());lbl_out(['ok'=>false,'error'=>$e->getMessage()],500);}
