<?php
declare(strict_types=1);require __DIR__.'/bootstrap.php';rh24_require_login();if(!rh24_can('view_pos')){http_response_code(403);exit('Kein Zugriff.');}$id=trim((string)($_GET['id']??''));$d=rh24_pos_sale_detail($id);$s=$d['sale'];$cfg=rh24_config();$money=fn($v)=>number_format((float)$v,2,',','.').' €';$when=$s['completed_at']?:$s['created_at'];$training=$s['fiscal_mode']==='training';
?><!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bon <?=htmlspecialchars((string)($s['receipt_no']??$id))?></title><style>
:root{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;color:#111}.page{max-width:76mm;margin:18px auto;background:#fff;padding:4mm}.c{text-align:center}.r{display:flex;justify-content:space-between;gap:8px}.dash{border-top:1px dashed #555;margin:8px 0}.item{margin:8px 0}.muted{font-size:10px}.sum{font-size:18px;font-weight:800}.training{border:2px solid #b84a13;padding:6px;text-align:center;font-weight:900;margin:8px 0}.actions{max-width:76mm;margin:12px auto;display:flex;gap:8px;flex-wrap:wrap}.actions button,.actions a{padding:9px 12px;border:1px solid #aaa;border-radius:8px;background:#fff;color:#111;text-decoration:none;cursor:pointer}@media print{.actions{display:none}.page{margin:0;padding:2mm;max-width:none}@page{size:80mm auto;margin:2mm}}
</style></head><body><div class="actions"><button onclick="print()">Drucken</button><button onclick="window.close()">Schließen</button><a href="index.php?view=pos">Zur Kasse</a></div><main class="page">
<div class="c"><strong><?=htmlspecialchars((string)($cfg['invoice_company_name']??'Räucherhaken24'))?></strong><br><span><?=htmlspecialchars(trim((string)($cfg['invoice_street']??'')))?></span><br><span><?=htmlspecialchars(trim((string)($cfg['invoice_zip']??'').' '.(string)($cfg['invoice_city']??'')))?></span></div>
<?php if($training):?><div class="training">TRAININGSBELEG · KEIN LIVE-TSE-BELEG</div><?php endif;?><div class="dash"></div><div class="r"><b>Beleg</b><span><?=htmlspecialchars((string)($s['receipt_no']??$id))?></span></div><div class="r"><span>Datum</span><span><?=date('d.m.Y H:i:s',strtotime((string)$when))?></span></div><div class="r"><span>Kasse</span><span><?=htmlspecialchars((string)$s['register_code'])?></span></div><div class="r"><span>Mitarbeiter</span><span><?=htmlspecialchars((string)$s['user_name'])?></span></div><?php if(!empty($s['customer_name'])):?><div class="r"><span>Kunde</span><span><?=htmlspecialchars((string)$s['customer_name'])?></span></div><?php endif;?><div class="dash"></div>
<?php foreach($d['items'] as $i):?><div class="item"><b><?=htmlspecialchars((string)$i['name'])?></b><div class="r"><span><?=number_format(abs((float)$i['qty']),2,',','.')?> × <?=$money($i['unit_price'])?> · <?=number_format((float)$i['tax_rate'],0)?>% USt</span><span><?=$money($i['gross_amount'])?></span></div></div><?php endforeach;?><div class="dash"></div>
<div class="r sum"><span><?=$s['sale_type']==='refund'?'ERSTATTUNG':'SUMME'?></span><span><?=$money($s['gross_amount'])?></span></div><div class="r"><span>Netto</span><span><?=$money($s['net_amount'])?></span></div><div class="r"><span>USt.</span><span><?=$money($s['tax_amount'])?></span></div><div class="dash"></div>
<?php foreach($d['payments'] as $p):?><div class="r"><span><?=htmlspecialchars(strtoupper((string)$p['payment_method']))?></span><span><?=$money($p['amount'])?></span></div><?php endforeach;?><?php if((float)$s['change_amount']>0):?><div class="r"><b>Rückgeld</b><b><?=$money($s['change_amount'])?></b></div><?php endif;?><div class="dash"></div>
<div class="muted"><div>TSE-Seriennummer: <?=htmlspecialchars((string)($s['fiscal_tse_serial']?:'–'))?></div><div>Transaktion: <?=htmlspecialchars((string)($s['fiscal_transaction_no']?:'–'))?></div><div>Signaturzähler: <?=htmlspecialchars((string)($s['fiscal_signature_counter']?:'–'))?></div><div>Prüfwert/Signatur: <?=htmlspecialchars((string)($s['fiscal_signature']?:'–'))?></div><div>Vorgangstyp: <?=htmlspecialchars((string)$s['sale_type'])?></div><div>Start: <?=htmlspecialchars((string)($s['fiscal_start_at']?:'–'))?></div><div>Ende: <?=htmlspecialchars((string)($s['fiscal_end_at']?:'–'))?></div><div>System: <?=htmlspecialchars((string)($s['software_serial']?:'RH24-POS'))?></div></div><div class="dash"></div><div class="c"><?=nl2br(htmlspecialchars((string)rh24_pos_config()['receipt_footer']))?></div></main><?php if(!empty($_GET['autoprint'])):?><script>addEventListener('load',()=>setTimeout(()=>print(),180));</script><?php endif;?></body></html>
