<?php
declare(strict_types=1);
require __DIR__ . '/bootstrap.php';
rh24_require_login();
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
function pos_out(array $d,int $status=200): never {http_response_code($status);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function pos_body(): array {$d=json_decode(file_get_contents('php://input')?:'{}',true);return is_array($d)?$d:[];}
function pos_require(string $perm): void {if(!rh24_can($perm)){pos_out(['ok'=>false,'error'=>'Für diese Kassenfunktion fehlt die Berechtigung: '.$perm],403);}}
function pos_float(mixed $v): float {return round((float)str_replace(',','.',trim((string)$v)),2);}
function pos_method_label(string $m): string {return ['cash'=>'Bar','girocard'=>'Girocard','credit_card'=>'Kreditkarte','paypal'=>'PayPal','bank_transfer'=>'Überweisung','voucher'=>'Gutschein','other'=>'Sonstige'][$m]??$m;}

$d=pos_body();rh24_verify_csrf($_SERVER['HTTP_X_CSRF_TOKEN']??($d['csrf']??null));$action=(string)($d['action']??'data');
try{
  rh24_pos_ensure_ready();$db=rh24_db();
  if($action==='data'){pos_require('view_pos');pos_out(['ok'=>true,'data'=>rh24_pos_data(),'csrf'=>rh24_csrf()]);}
  if($action==='sale_detail'){pos_require('view_pos');pos_out(['ok'=>true,'sale'=>rh24_pos_sale_detail(trim((string)($d['id']??'')))]);}
  if($action==='price_quote'){pos_require('operate_pos');$pid=trim((string)($d['product_id']??''));$meta=is_array($d['meta']??null)?$d['meta']:[];pos_out(['ok'=>true,'price'=>rh24_resolve_price($pid,$meta)]);}
  if($action==='receipt_text'){pos_require('view_pos');$id=trim((string)($d['id']??''));pos_out(['ok'=>true,'text'=>rh24_pos_receipt_text($id),'sale'=>rh24_pos_sale_detail($id)]);}
  if($action==='shift_open'){
    pos_require('operate_pos');$register=trim((string)($d['register_id']??''));$opening=max(0,pos_float($d['opening_cash']??0));$note=substr(trim((string)($d['note']??'')),0,500);
    if($register==='')throw new InvalidArgumentException('Bitte einen Kassenplatz wählen.');
    $q=$db->prepare("SELECT status FROM pos_registers WHERE id=?");$q->execute([$register]);if($q->fetchColumn()!=='active')throw new RuntimeException('Dieser Kassenplatz ist nicht aktiv.');
    if(rh24_pos_open_shift($register,''))throw new RuntimeException('An diesem Kassenplatz ist bereits eine Schicht geöffnet.');
    if(rh24_pos_open_shift('',rh24_user_id()))throw new RuntimeException('Sie haben bereits eine offene Kassenschicht.');
    $id=rh24_random_id('SHIFT-');$db->prepare("INSERT INTO pos_shifts(id,register_id,user_id,status,opened_at,opening_cash,opening_note,created_at,updated_at) VALUES(?,?,?,'open',NOW(),?,?,NOW(),NOW())")->execute([$id,$register,rh24_user_id(),$opening,$note]);
    $mid=rh24_random_id('CM-');$db->prepare("INSERT INTO pos_cash_movements(id,register_id,shift_id,user_id,sale_id,movement_type,amount,reason,created_at) VALUES(?,?,?,?,NULL,'opening',?,'Kassenanfangsbestand',NOW())")->execute([$mid,$register,$id,rh24_user_id(),0]);
    rh24_audit('pos_shift_open','pos_shift',$id,['register_id'=>$register,'opening_cash'=>$opening]);pos_out(['ok'=>true,'data'=>rh24_pos_data()]);
  }
  if($action==='sale_create'){
    pos_require('operate_pos');$shift=rh24_pos_open_shift('',rh24_user_id());if(!$shift)throw new RuntimeException('Bitte zuerst eine Kassenschicht öffnen.');$customerId=trim((string)($d['customer_id']??''));$customer=$customerId!==''?rh24_pos_customer_snapshot($customerId):rh24_pos_customer_snapshot(null);$id=rh24_random_id('SALE-');$cfg=rh24_pos_config();
    $db->prepare("INSERT INTO pos_sales(id,register_id,shift_id,user_id,customer_id,sale_type,status,fiscal_mode,currency,customer_json,note,fiscal_status,created_at,updated_at) VALUES(?,?,?,?,?,'sale','draft',?,'EUR',?,?,'pending',NOW(),NOW())")->execute([$id,$shift['register_id'],$shift['id'],rh24_user_id(),$customerId?:null,$cfg['fiscal_mode'],rh24_json_encode($customer),substr(trim((string)($d['note']??'')),0,700)]);
    try{rh24_pos_apply_fiscal_start($id);}catch(Throwable $e){$db->prepare("UPDATE pos_sales SET status='void',cancellation_reason=?,fiscal_status='failed',updated_at=NOW() WHERE id=?")->execute([substr($e->getMessage(),0,500),$id]);throw $e;}
    rh24_audit('pos_sale_open','pos_sale',$id,['shift_id'=>$shift['id']]);pos_out(['ok'=>true,'sale'=>rh24_pos_sale_detail($id)]);
  }
  if($action==='sale_save'){
    pos_require('operate_pos');$id=trim((string)($d['id']??''));$customerId=trim((string)($d['customer_id']??''));$note=substr(trim((string)($d['note']??'')),0,700);$q=$db->prepare("SELECT user_id,status FROM pos_sales WHERE id=?");$q->execute([$id]);$s=$q->fetch();if(!$s||$s['status']!=='draft')throw new RuntimeException('Der Kassenbon ist nicht mehr bearbeitbar.');if($s['user_id']!==rh24_user_id()&&!rh24_is_admin())throw new RuntimeException('Dieser Kassenbon gehört zu einem anderen Mitarbeiter.');$customer=$customerId!==''?rh24_pos_customer_snapshot($customerId):rh24_pos_customer_snapshot(null);$db->prepare("UPDATE pos_sales SET customer_id=?,customer_json=?,note=?,updated_at=NOW() WHERE id=?")->execute([$customerId?:null,rh24_json_encode($customer),$note,$id]);$sale=rh24_pos_save_items($id,is_array($d['items']??null)?$d['items']:[],max(0,pos_float($d['cart_discount']??0)));pos_out(['ok'=>true,'sale'=>$sale]);
  }
  if($action==='sale_abandon'){
    pos_require('operate_pos');$id=trim((string)($d['id']??''));$reason=substr(trim((string)($d['reason']??'Vorgang abgebrochen')),0,500);$detail=rh24_pos_sale_detail($id);$s=$detail['sale'];if($s['status']!=='draft')throw new RuntimeException('Nur offene Vorgänge können abgebrochen werden.');if($s['user_id']!==rh24_user_id()&&!rh24_is_admin())throw new RuntimeException('Dieser Vorgang gehört zu einem anderen Mitarbeiter.');
    try{$resp=rh24_pos_gateway_call('cancel',$s,$detail['items']);$db->prepare("UPDATE pos_sales SET status='void',cancellation_reason=?,fiscal_end_at=NOW(),fiscal_signature=?,fiscal_signature_counter=?,fiscal_status=?,updated_at=NOW() WHERE id=?")->execute([$reason,(string)($resp['signature']??''),(string)($resp['signature_counter']??''),rh24_pos_config()['fiscal_mode']==='training'?'training':'cancelled',$id]);}catch(Throwable $e){throw new RuntimeException('Der Kassen-Vorgang konnte fiskalisch nicht sauber abgebrochen werden: '.$e->getMessage());}
    rh24_audit('pos_sale_void','pos_sale',$id,['reason'=>$reason]);pos_out(['ok'=>true,'data'=>rh24_pos_data()]);
  }
  if($action==='sale_complete'){
    pos_require('operate_pos');$id=trim((string)($d['id']??''));$detail=rh24_pos_sale_detail($id);$s=$detail['sale'];if($s['status']!=='draft'||$s['sale_type']!=='sale')throw new RuntimeException('Der Vorgang ist nicht kassierbar.');if($s['user_id']!==rh24_user_id()&&!rh24_is_admin())throw new RuntimeException('Dieser Vorgang gehört zu einem anderen Mitarbeiter.');if(!$detail['items'])throw new RuntimeException('Der Warenkorb ist leer.');$gross=round((float)$s['gross_amount'],2);if($gross<=0)throw new RuntimeException('Der Zahlbetrag muss größer als 0 sein.');
    $allowed=['cash','girocard','credit_card','paypal','bank_transfer','voucher','other'];$payments=[];$sum=0;$cash=0;foreach((array)($d['payments']??[]) as $p){$m=(string)($p['method']??'');$amt=pos_float($p['amount']??0);if(!in_array($m,$allowed,true)||$amt<=0)continue;$payments[]=['method'=>$m,'amount'=>$amt,'provider'=>substr(trim((string)($p['provider']??'')),0,60),'ref'=>substr(trim((string)($p['reference']??'')),0,180)];$sum+=$amt;if($m==='cash')$cash+=$amt;}$sum=round($sum,2);if($sum+0.001<$gross)throw new RuntimeException('Zahlung unvollständig. Offen: '.number_format($gross-$sum,2,',','.').' €');$change=round($sum-$gross,2);if($change>0.001&&$cash+0.001<$change)throw new RuntimeException('Überzahlung ist nur als Bargeld mit Rückgeld zulässig.');
    $db->beginTransaction();try{
      $q=$db->prepare("SELECT * FROM pos_sales WHERE id=? AND status='draft' FOR UPDATE");$q->execute([$id]);$locked=$q->fetch();if(!$locked)throw new RuntimeException('Kassenbon wurde zwischenzeitlich abgeschlossen.');$receipt=rh24_pos_next_receipt_no($db,(string)$locked['register_id']);$db->prepare("UPDATE pos_sales SET receipt_no=?,tendered_amount=?,change_amount=?,completed_at=NOW(),updated_at=NOW() WHERE id=?")->execute([$receipt,$sum,$change,$id]);
      $ins=$db->prepare("INSERT INTO pos_payments(sale_id,payment_method,provider,amount,transaction_ref,status,created_at) VALUES(?,?,?,?,?,'captured',NOW())");foreach($payments as $p)$ins->execute([$id,$p['method'],$p['provider'],$p['amount'],$p['ref']]);
      foreach($detail['items'] as $i){if(!$i['product_id'])continue;$qty=(int)ceil((float)$i['qty']);$q=$db->prepare('UPDATE inventory SET stock=stock-?,updated_at=NOW() WHERE id=?'.(rh24_pos_config()['allow_negative_stock']?'':' AND stock>=?'));$args=rh24_pos_config()['allow_negative_stock']?[$qty,$i['product_id']]:[$qty,$i['product_id'],$qty];$q->execute($args);if(!rh24_pos_config()['allow_negative_stock']&&$q->rowCount()===0)throw new RuntimeException('Lagerbestand reicht für '.$i['name'].' nicht mehr aus.');}
      $cashNet=round($cash-$change,2);if($cashNet>0){$mid=rh24_random_id('CM-');$db->prepare("INSERT INTO pos_cash_movements(id,register_id,shift_id,user_id,sale_id,movement_type,amount,reason,created_at) VALUES(?,?,?,?,?,'sale',?,'Barverkauf',NOW())")->execute([$mid,$locked['register_id'],$locked['shift_id'],$locked['user_id'],$id,$cashNet]);}
      $orderNo=rh24_pos_create_order_from_sale($id);rh24_pos_apply_fiscal_finish($id);$db->prepare("UPDATE pos_sales SET status='completed',updated_at=NOW() WHERE id=?")->execute([$id]);$db->commit();
    }catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
    if(isset($cashNet)&&$cashNet>0){$fid=rh24_pos_finance_cash_entry($id,$cashNet,'income');if($fid){$db->prepare('UPDATE pos_cash_movements SET finance_entry_id=? WHERE sale_id=? AND movement_type=\'sale\'')->execute([$fid,$id]);}}
    rh24_audit('pos_sale_complete','pos_sale',$id,['receipt_no'=>$receipt??'','gross'=>$gross,'payments'=>$payments,'order_no'=>$orderNo??'']);pos_out(['ok'=>true,'sale'=>rh24_pos_sale_detail($id),'receipt_url'=>'pos-receipt.php?id='.rawurlencode($id)]);
  }
  if($action==='sale_refund'){
    pos_require('pos_refund');$originalId=trim((string)($d['id']??''));$original=rh24_pos_sale_detail($originalId);$os=$original['sale'];if($os['status']!=='completed'||$os['sale_type']!=='sale')throw new RuntimeException('Nur abgeschlossene Verkäufe können erstattet werden.');$shift=rh24_pos_open_shift('',rh24_user_id());if(!$shift)throw new RuntimeException('Für eine Erstattung muss eine Kassenschicht geöffnet sein.');$reason=substr(trim((string)($d['reason']??'')),0,500);if($reason==='')throw new InvalidArgumentException('Bitte einen Retouren-/Erstattungsgrund angeben.');
    $requested=[];foreach((array)($d['items']??[]) as $r){$line=(int)($r['item_id']??0);$qty=max(0,(float)str_replace(',','.',(string)($r['qty']??0)));if($line&&$qty>0)$requested[$line]=$qty;}if(!$requested)throw new InvalidArgumentException('Bitte mindestens einen Artikel für die Erstattung wählen.');
    $q=$db->prepare("SELECT oi.id,oi.qty,COALESCE(SUM(ABS(ri.qty)),0) refunded FROM pos_sale_items oi LEFT JOIN pos_sales rs ON rs.original_sale_id=? AND rs.status='completed' AND rs.sale_type='refund' LEFT JOIN pos_sale_items ri ON ri.sale_id=rs.id AND ri.original_item_id=oi.id WHERE oi.sale_id=? GROUP BY oi.id,oi.qty");$q->execute([$originalId,$originalId]);$already=[];foreach($q->fetchAll() as $r)$already[(int)$r['id']]=(float)$r['refunded'];
    $method=(string)($d['method']??'cash');if(!in_array($method,['cash','girocard','credit_card','paypal','bank_transfer','voucher','other'],true))throw new InvalidArgumentException('Ungültige Erstattungsart.');$id=rh24_random_id('REF-');$cfg=rh24_pos_config();$customer=$os['customer']?:rh24_pos_customer_snapshot($os['customer_id']?:null);$db->prepare("INSERT INTO pos_sales(id,register_id,shift_id,user_id,customer_id,original_sale_id,sale_type,status,fiscal_mode,currency,customer_json,note,cancellation_reason,fiscal_status,created_at,updated_at) VALUES(?,?,?,?,?,?,'refund','draft',?,'EUR',?,?,?,'pending',NOW(),NOW())")->execute([$id,$shift['register_id'],$shift['id'],rh24_user_id(),$os['customer_id']?:null,$originalId,$cfg['fiscal_mode'],rh24_json_encode($customer),'Retoure zu '.$os['receipt_no'],$reason]);rh24_pos_apply_fiscal_start($id);
    $line=0;$subtotal=$net=$tax=$gross=0.0;$refundItems=[];foreach($original['items'] as $i){$iid=(int)$i['id'];if(!isset($requested[$iid]))continue;$max=max(0,(float)$i['qty']-($already[$iid]??0));$qty=min($requested[$iid],$max);if($qty<=0)continue;$ratio=$qty/max(0.0001,(float)$i['qty']);$ig=round(-abs((float)$i['gross_amount']*$ratio),2);$in=round(-abs((float)$i['net_amount']*$ratio),2);$it=round($ig-$in,2);$line++;$refundItems[]=['orig'=>$i,'qty'=>$qty,'gross'=>$ig,'net'=>$in,'tax'=>$it];$subtotal+=round(-abs((float)$i['unit_price']*$qty),2);$gross+=$ig;$net+=$in;$tax+=$it;}if(!$refundItems){$db->prepare("UPDATE pos_sales SET status='void',cancellation_reason='Keine erstattungsfähige Menge',updated_at=NOW() WHERE id=?")->execute([$id]);throw new RuntimeException('Für diese Auswahl ist keine erstattungsfähige Menge mehr vorhanden.');}
    $db->beginTransaction();try{$receipt=rh24_pos_next_receipt_no($db,(string)$shift['register_id']);$ins=$db->prepare("INSERT INTO pos_sale_items(sale_id,original_item_id,line_no,product_id,sku,article_no,barcode,name,qty,unit,unit_price,discount_percent,discount_amount,tax_rate,net_amount,tax_amount,gross_amount,meta_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW())");$ln=0;foreach($refundItems as $ri){$i=$ri['orig'];$ln++;$ins->execute([$id,$i['id'],$ln,$i['product_id'],$i['sku'],$i['article_no'],$i['barcode'],$i['name'],-$ri['qty'],$i['unit'],$i['unit_price'],$i['discount_percent'],0,$i['tax_rate'],$ri['net'],$ri['tax'],$ri['gross'],rh24_json_encode($i['meta']??[])]);if($i['product_id']){$add=(int)ceil($ri['qty']);$db->prepare('UPDATE inventory SET stock=stock+?,updated_at=NOW() WHERE id=?')->execute([$add,$i['product_id']]);}}$refundAmount=round(abs($gross),2);$db->prepare("UPDATE pos_sales SET receipt_no=?,subtotal=?,net_amount=?,tax_amount=?,gross_amount=?,tendered_amount=?,completed_at=NOW(),updated_at=NOW() WHERE id=?")->execute([$receipt,$subtotal,$net,$tax,$gross,$refundAmount,$id]);$db->prepare("INSERT INTO pos_payments(sale_id,payment_method,provider,amount,transaction_ref,status,created_at) VALUES(?,?, '',?,?,'refunded',NOW())")->execute([$id,$method,-$refundAmount,substr(trim((string)($d['reference']??'')),0,180)]);if($method==='cash'){$mid=rh24_random_id('CM-');$db->prepare("INSERT INTO pos_cash_movements(id,register_id,shift_id,user_id,sale_id,movement_type,amount,reason,created_at) VALUES(?,?,?,?,?,'refund',?,?,NOW())")->execute([$mid,$shift['register_id'],$shift['id'],rh24_user_id(),$id,-$refundAmount,$reason]);}$orderNo=rh24_pos_create_order_from_sale($id);rh24_pos_apply_fiscal_finish($id);$db->prepare("UPDATE pos_sales SET status='completed',updated_at=NOW() WHERE id=?")->execute([$id]);$db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
    if($method==='cash'){$fid=rh24_pos_finance_cash_entry($id,$refundAmount,'withdrawal');if($fid)$db->prepare("UPDATE pos_cash_movements SET finance_entry_id=? WHERE sale_id=? AND movement_type='refund'")->execute([$fid,$id]);}rh24_audit('pos_refund_complete','pos_sale',$id,['original_sale_id'=>$originalId,'amount'=>$refundAmount,'reason'=>$reason]);pos_out(['ok'=>true,'sale'=>rh24_pos_sale_detail($id),'receipt_url'=>'pos-receipt.php?id='.rawurlencode($id)]);
  }
  if($action==='cash_move'){
    pos_require('pos_cash_manage');$shift=rh24_pos_open_shift('',rh24_user_id());if(!$shift)throw new RuntimeException('Keine offene Kassenschicht.');$kind=(string)($d['kind']??'cash_in');if(!in_array($kind,['cash_in','cash_out'],true))throw new InvalidArgumentException('Ungültige Kassenbewegung.');$amount=abs(pos_float($d['amount']??0));$reason=substr(trim((string)($d['reason']??'')),0,300);if($amount<=0||$reason==='')throw new InvalidArgumentException('Betrag und Begründung sind erforderlich.');$signed=$kind==='cash_out'?-$amount:$amount;$id=rh24_random_id('CM-');$db->prepare("INSERT INTO pos_cash_movements(id,register_id,shift_id,user_id,movement_type,amount,reason,created_at) VALUES(?,?,?,?,?,?,?,NOW())")->execute([$id,$shift['register_id'],$shift['id'],rh24_user_id(),$kind,$signed,$reason]);$fid=null;try{$fakeSaleId='';$date=date('Y-m-d');if(function_exists('rh24_finance_assert_period_open'))rh24_finance_assert_period_open($date);$fid=rh24_random_id('CASH-');$no=rh24_finance_next_no('finance_next_cash_no','KA');$db->prepare("INSERT INTO finance_cash_entries(id,entry_no,entry_date,entry_type,amount,description,receipt_no,account_code,tax_rate,tax_amount,cost_center_id,created_by,locked_at,created_at) VALUES(?,?,?,?,?,?, '', '',0,0,NULL,?,NULL,NOW())")->execute([$fid,$no,$date,$kind==='cash_in'?'deposit':'withdrawal',$amount,'POS '.($kind==='cash_in'?'Bareinlage: ':'Barentnahme: ').$reason,rh24_user_id()]);$db->prepare('UPDATE pos_cash_movements SET finance_entry_id=? WHERE id=?')->execute([$fid,$id]);}catch(Throwable $e){error_log('POS cash movement finance link: '.$e->getMessage());}rh24_audit('pos_cash_move','pos_cash',$id,['kind'=>$kind,'amount'=>$amount,'reason'=>$reason]);pos_out(['ok'=>true,'data'=>rh24_pos_data()]);
  }
  if($action==='shift_close'){
    pos_require('pos_close_shift');$shift=rh24_pos_open_shift('',rh24_user_id());if(!$shift)throw new RuntimeException('Keine offene Kassenschicht.');$q=$db->prepare("SELECT COUNT(*) FROM pos_sales WHERE shift_id=? AND status='draft'");$q->execute([$shift['id']]);if((int)$q->fetchColumn()>0)throw new RuntimeException('Es gibt noch offene/parkende Kassenbons. Bitte abschließen oder abbrechen.');$stats=rh24_pos_shift_stats((string)$shift['id']);$counted=max(0,pos_float($d['counted_cash']??0));$diff=round($counted-$stats['expected_cash'],2);$note=substr(trim((string)($d['note']??'')),0,500);$z='Z-'.date('Ymd').'-'.strtoupper(substr((string)$shift['register_code'],0,10)).'-'.date('His');$cid=rh24_random_id('Z-');$pay=rh24_json_encode($stats['payments']);
    $db->beginTransaction();try{$db->prepare("UPDATE pos_shifts SET status='closed',closed_at=NOW(),expected_cash=?,counted_cash=?,cash_difference=?,closing_note=?,closed_by=?,updated_at=NOW() WHERE id=? AND status='open'")->execute([$stats['expected_cash'],$counted,$diff,$note,rh24_user_id(),$shift['id']]);$db->prepare("INSERT INTO pos_daily_closings(id,register_id,shift_id,business_date,user_id,gross_sales,refunds,net_sales,tax_total,cash_expected,cash_counted,cash_difference,payments_json,z_report_no,closed_at,created_at) VALUES(?,?,?,CURDATE(),?,?,?,?,?,?,?,?,?,?,NOW(),NOW())")->execute([$cid,$shift['register_id'],$shift['id'],rh24_user_id(),$stats['gross_sales'],$stats['refunds'],$stats['net_sales'],$stats['tax_total'],$stats['expected_cash'],$counted,$diff,$pay,$z]);$db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}rh24_audit('pos_shift_close','pos_shift',$shift['id'],['z_report_no'=>$z,'expected'=>$stats['expected_cash'],'counted'=>$counted,'difference'=>$diff]);pos_out(['ok'=>true,'closing_id'=>$cid,'z_report_url'=>'pos-zreport.php?id='.rawurlencode($cid),'data'=>rh24_pos_data()]);
  }
  if($action==='register_save'){
    pos_require('pos_manage');$id=trim((string)($d['id']??''))?:rh24_random_id('REG-');$code=strtoupper(substr(preg_replace('/[^A-Za-z0-9_-]+/','-',trim((string)($d['code']??''))),0,30));$name=substr(trim((string)($d['name']??'')),0,160);if($code===''||$name==='')throw new InvalidArgumentException('Kassen-Code und Name sind erforderlich.');$location=substr(trim((string)($d['location']??'')),0,220);$status=in_array(($d['status']??'active'),['active','inactive'],true)?$d['status']:'active';$prefix=strtoupper(substr(preg_replace('/[^A-Za-z0-9_-]+/','',trim((string)($d['receipt_prefix']??'KASSE'))),0,20))?:'KASSE';$printer=is_array($d['printer_profile']??null)?$d['printer_profile']:[];$scanner=is_array($d['scanner_profile']??null)?$d['scanner_profile']:[];$drawer=is_array($d['cash_drawer_profile']??null)?$d['cash_drawer_profile']:[];
    $q=$db->prepare('SELECT id FROM pos_registers WHERE id=?');$q->execute([$id]);if($q->fetchColumn())$db->prepare("UPDATE pos_registers SET code=?,name=?,location=?,status=?,receipt_prefix=?,tse_serial=?,tse_client_id=?,printer_profile_json=?,scanner_profile_json=?,cash_drawer_profile_json=?,notes=?,updated_at=NOW() WHERE id=?")->execute([$code,$name,$location,$status,$prefix,substr(trim((string)($d['tse_serial']??'')),0,180),substr(trim((string)($d['tse_client_id']??'')),0,180),rh24_json_encode($printer),rh24_json_encode($scanner),rh24_json_encode($drawer),substr(trim((string)($d['notes']??'')),0,500),$id]);else $db->prepare("INSERT INTO pos_registers(id,code,name,location,status,currency,software_serial,receipt_prefix,next_receipt_no,tse_provider,tse_serial,tse_client_id,printer_profile_json,scanner_profile_json,cash_drawer_profile_json,notes,created_at,updated_at) VALUES(?,?,?,?,?,'EUR',?,?,1,'gateway',?,?,?,?,?,?,NOW(),NOW())")->execute([$id,$code,$name,$location,$status,'RH24-POS-'.strtoupper(bin2hex(random_bytes(6))),$prefix,substr(trim((string)($d['tse_serial']??'')),0,180),substr(trim((string)($d['tse_client_id']??'')),0,180),rh24_json_encode($printer),rh24_json_encode($scanner),rh24_json_encode($drawer),substr(trim((string)($d['notes']??'')),0,500)]);rh24_audit('pos_register_save','pos_register',$id,['code'=>$code]);pos_out(['ok'=>true,'data'=>rh24_pos_data()]);
  }
  if($action==='settings_save'){
    pos_require('pos_tse_manage');$mode=(string)($d['fiscal_mode']??'training');if(!in_array($mode,['training','live'],true))$mode='training';$url=trim((string)($d['tse_gateway_url']??''));if($mode==='live'){if(!filter_var($url,FILTER_VALIDATE_URL)||!preg_match('#^https://#i',$url))throw new InvalidArgumentException('Für Live-Betrieb ist eine HTTPS-Adresse des zertifizierten TSE-Gateways erforderlich.');}rh24_setting_set('pos_fiscal_mode',$mode);rh24_setting_set('pos_tse_gateway_url',$url);if(array_key_exists('tse_gateway_token',$d)&&trim((string)$d['tse_gateway_token'])!=='')rh24_setting_set('pos_tse_gateway_token',trim((string)$d['tse_gateway_token']));rh24_setting_set('pos_allow_negative_stock',!empty($d['allow_negative_stock'])?'1':'0');rh24_setting_set('pos_receipt_footer',substr(trim((string)($d['receipt_footer']??'')),0,500));rh24_audit('pos_settings_save','pos_settings','global',['fiscal_mode'=>$mode,'gateway_configured'=>$url!=='']);pos_out(['ok'=>true,'data'=>rh24_pos_data()]);
  }
  throw new RuntimeException('Unbekannte Kassenaktion.');
}catch(InvalidArgumentException $e){pos_out(['ok'=>false,'error'=>$e->getMessage()],422);}catch(Throwable $e){error_log('RH24 POS API: '.$e->getMessage());pos_out(['ok'=>false,'error'=>$e->getMessage()],500);}
