<?php
declare(strict_types=1);require __DIR__.'/bootstrap.php';rh24_require_login();if(!rh24_can('pos_reports')&&!rh24_is_admin()){http_response_code(403);exit('Kein Zugriff.');}rh24_pos_ensure_ready();$db=rh24_db();$from=preg_match('/^\d{4}-\d{2}-\d{2}$/',(string)($_GET['from']??''))?$_GET['from']:date('Y-m-01');$to=preg_match('/^\d{4}-\d{2}-\d{2}$/',(string)($_GET['to']??''))?$_GET['to']:date('Y-m-d');$format=(string)($_GET['format']??'sales');
function p_csv(array $rows): string {$f=fopen('php://temp','r+');fwrite($f,"\xEF\xBB\xBF");if($rows){fputcsv($f,array_keys($rows[0]),';','"','\\');foreach($rows as $r)fputcsv($f,array_values($r),';','"','\\');}rewind($f);return stream_get_contents($f)?:'';}
$q=$db->prepare("SELECT s.id,s.receipt_no,s.sale_type,s.status,s.created_at,s.completed_at,s.gross_amount,s.net_amount,s.tax_amount,s.discount_amount,s.change_amount,s.fiscal_mode,s.fiscal_transaction_no,s.fiscal_signature_counter,s.fiscal_tse_serial,s.order_no,r.code register_code,u.display_name cashier,c.name customer FROM pos_sales s JOIN pos_registers r ON r.id=s.register_id LEFT JOIN users u ON u.id=s.user_id LEFT JOIN customers c ON c.id=s.customer_id WHERE DATE(COALESCE(s.completed_at,s.created_at)) BETWEEN ? AND ? ORDER BY s.created_at");$q->execute([$from,$to]);$sales=$q->fetchAll();
if($format==='sales'){header('Content-Type:text/csv; charset=utf-8');header('Content-Disposition:attachment; filename="POS-Verkaeufe-'.$from.'-'.$to.'.csv"');echo p_csv($sales);exit;}
if($format!=='audit'){http_response_code(400);exit('Unbekanntes Exportformat.');}
$ids=array_column($sales,'id');$items=[];$payments=[];$moves=[];$tse=[];if($ids){$ph=implode(',',array_fill(0,count($ids),'?'));$q=$db->prepare("SELECT sale_id,line_no,product_id,sku,article_no,barcode,name,qty,unit,unit_price,discount_amount,tax_rate,net_amount,tax_amount,gross_amount FROM pos_sale_items WHERE sale_id IN ($ph) ORDER BY sale_id,line_no");$q->execute($ids);$items=$q->fetchAll();$q=$db->prepare("SELECT sale_id,payment_method,provider,amount,transaction_ref,status,created_at FROM pos_payments WHERE sale_id IN ($ph) ORDER BY sale_id,id");$q->execute($ids);$payments=$q->fetchAll();$q=$db->prepare("SELECT sale_id,register_id,shift_id,user_id,movement_type,amount,reason,finance_entry_id,created_at FROM pos_cash_movements WHERE sale_id IN ($ph) ORDER BY created_at");$q->execute($ids);$moves=$q->fetchAll();$q=$db->prepare("SELECT sale_id,register_id,event_type,provider,success,message,created_at FROM pos_tse_events WHERE sale_id IN ($ph) ORDER BY created_at");$q->execute($ids);$tse=$q->fetchAll();}
$readme="Räucherhaken24 Orgaboard POS V94\nPrüf-/Rohdatenexport: $from bis $to\n\nEnthalten: Verkäufe, Positionen, Zahlarten, Bargeldbewegungen und TSE-Ereignisse.\nDieser Export stellt die internen Kassendaten vollständig bereit. Er wird bewusst NICHT als zertifizierter DSFinV-K-Endexport bezeichnet. Für den produktiven Livebetrieb muss der angebundene zertifizierte TSE-/Kassenanbieter den finalen DSFinV-K-2.4-Export gemäß seiner Implementierung und den geltenden Vorgaben bereitstellen bzw. validieren.\n";
if(class_exists('ZipArchive')){$tmp=tempnam(sys_get_temp_dir(),'rh24-pos-');$zip=new ZipArchive();$zip->open($tmp,ZipArchive::CREATE|ZipArchive::OVERWRITE);$zip->addFromString('README.txt',$readme);$zip->addFromString('transactions.csv',p_csv($sales));$zip->addFromString('lines.csv',p_csv($items));$zip->addFromString('payments.csv',p_csv($payments));$zip->addFromString('cash_movements.csv',p_csv($moves));$zip->addFromString('tse_events.csv',p_csv($tse));$zip->close();header('Content-Type:application/zip');header('Content-Disposition:attachment; filename="POS-Pruefpaket-'.$from.'-'.$to.'.zip"');readfile($tmp);@unlink($tmp);exit;}
header('Content-Type:text/plain; charset=utf-8');header('Content-Disposition:attachment; filename="POS-Pruefpaket-'.$from.'-'.$to.'.txt"');echo $readme."\n--- transactions.csv ---\n".p_csv($sales)."\n--- lines.csv ---\n".p_csv($items)."\n--- payments.csv ---\n".p_csv($payments)."\n--- cash_movements.csv ---\n".p_csv($moves)."\n--- tse_events.csv ---\n".p_csv($tse);
