<?php
declare(strict_types=1);
require_once __DIR__.'/bootstrap.php';
rh24_require_login();
if(!rh24_can('view_appointments')){http_response_code(403);exit('Keine Berechtigung.');}
header('Content-Type: text/html; charset=utf-8');header('Cache-Control: no-store');
$checks=[];$add=function(string $name,bool $ok,string $detail='')use(&$checks){$checks[]=['name'=>$name,'ok'=>$ok,'detail'=>$detail];};
try{$db=rh24_db();$add('Datenbankverbindung',true,'MariaDB erreichbar');}catch(Throwable $e){$add('Datenbankverbindung',false,$e->getMessage());$db=null;}
$requiredCols=['all_day','meeting_url','buffer_before_minutes','buffer_after_minutes','reminder_2_minutes','reminder_channel','series_id','recurrence_rule','recurrence_until','color','tags_json','outcome','next_action','follow_up_at','confirmed_at','confirmation_source','last_reminded_at','reminder_1_sent_at','reminder_2_sent_at'];
if($db){
  try{$cols=[];foreach($db->query('SHOW COLUMNS FROM advisor_appointments')->fetchAll() as $r)$cols[]=(string)$r['Field'];foreach($requiredCols as $c)$add('Spalte advisor_appointments.'.$c,in_array($c,$cols,true),in_array($c,$cols,true)?'vorhanden':'fehlt');}catch(Throwable $e){$add('Termin-Haupttabelle',false,$e->getMessage());}
  foreach(['advisor_appointment_attendees','advisor_appointment_tasks','advisor_appointment_templates'] as $t){try{$q=$db->query('SHOW TABLES LIKE '.$db->quote($t));$ok=(bool)$q->fetchColumn();$add('Tabelle '.$t,$ok,$ok?'vorhanden':'fehlt');}catch(Throwable $e){$add('Tabelle '.$t,false,$e->getMessage());}}
  try{$q=$db->prepare("SELECT setting_value FROM settings WHERE setting_key='appointment_schema_version'");$q->execute();$v=(int)($q->fetchColumn()?:0);$add('Termin-Schema-Version ≥ 92',$v>=92,'Wert: '.$v);}catch(Throwable $e){$add('Termin-Schema-Version',false,$e->getMessage());}
}
foreach(['rh24_appointment_data','rh24_appointment_recurrence_dates','rh24_appointment_save_related','rh24_appointment_expand_series','rh24_appointment_ics_content','rh24_v92_appointments_ready','rh24_appointment_send_due_reminders'] as $f)$add('PHP-Funktion '.$f,function_exists($f),function_exists($f)?'geladen':'fehlt');
foreach(['admin-v9911.js','assets/appointments-v92.css','termin-ics.php','terminplaner-print.php','appointment-reminders.php','termin-erinnerungen-einrichten.php'] as $f)$add('Datei '.$f,is_file(__DIR__.'/'.$f),is_file(__DIR__.'/'.$f)?'vorhanden':'fehlt');
$ok=count(array_filter($checks,fn($x)=>!$x['ok']))===0;
?><!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Terminmanagement V92 Diagnose</title><style>body{font-family:system-ui;background:#f5f2ed;color:#2e2721;margin:0;padding:28px}main{max-width:1000px;margin:auto}.hero{padding:24px;border-radius:20px;background:#2c2018;color:white}.hero h1{margin:4px 0}.ok{color:#178548}.bad{color:#b52f2f}.card{margin-top:16px;background:#fff;border:1px solid #e5ddd4;border-radius:16px;overflow:hidden}.row{display:grid;grid-template-columns:1fr auto;gap:15px;padding:12px 16px;border-bottom:1px solid #eee8e1}.row:last-child{border:0}.row small{display:block;color:#756a61;margin-top:3px}.badge{font-weight:800}.actions{margin-top:18px;display:flex;gap:10px}.actions a{padding:10px 14px;border-radius:10px;background:#35271e;color:#fff;text-decoration:none}</style></head><body><main><section class="hero"><small>ORGABOARD · V92</small><h1>Terminmanagement Diagnose</h1><p><?= $ok?'Alle Termin-Komponenten sind vollständig geladen.':'Mindestens eine Termin-Komponente fehlt oder konnte nicht initialisiert werden.' ?></p></section><section class="card"><?php foreach($checks as $c):?><div class="row"><div><b><?=htmlspecialchars($c['name'])?></b><small><?=htmlspecialchars($c['detail'])?></small></div><span class="badge <?=$c['ok']?'ok':'bad'?>"><?=$c['ok']?'OK':'FEHLER'?></span></div><?php endforeach;?></section><div class="actions"><a href="index.php?v=92">Orgaboard öffnen</a><a href="version.php?v=92">Versionscheck</a><?php if(rh24_is_admin()):?><a href="termin-erinnerungen-einrichten.php?v=92">E-Mail-Erinnerungen</a><?php endif;?></div></main></body></html>
