<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';rh24_require_login();if(!rh24_can('view_appointments')){http_response_code(403);exit('Keine Berechtigung.');}
$period=trim((string)($_GET['period']??date('Y-m')));$requested=trim((string)($_GET['sales_rep_id']??''));$data=rh24_appointment_data($period,$requested);$rep=$data['rep']??[];$rows=$data['rows']??[];$rows=array_values(array_filter($rows,fn($r)=>substr((string)$r['starts_at'],0,7)===$period));
function h2x($v){return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function dt2($v){return $v?date('d.m.Y H:i',strtotime((string)$v)):'–';}
?><!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Terminplan <?=h2x($period)?></title><style>
body{margin:0;background:#eef0f1;font-family:Arial,Helvetica,sans-serif;color:#27221e}.bar{position:sticky;top:0;z-index:2;background:#302116;color:#fff;padding:12px 18px;display:flex;justify-content:space-between;align-items:center}.bar button{border:0;border-radius:8px;padding:10px 14px;font-weight:800}.sheet{max-width:1120px;margin:22px auto;background:#fff;padding:28px;box-shadow:0 10px 34px #0002}.head{display:flex;justify-content:space-between;gap:20px;border-bottom:3px solid #5b3a1e;padding-bottom:16px}.head small{letter-spacing:.14em;color:#a25f26;font-weight:900}.head h1{margin:5px 0}.stats{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin:16px 0}.stats div{border:1px solid #ddd4cc;border-radius:10px;padding:12px}.stats b{font-size:21px;display:block}.tbl{width:100%;border-collapse:collapse;font-size:9px}.tbl th{background:#f5f1ec;text-align:left;padding:8px;border-bottom:1px solid #cec5bc}.tbl td{padding:8px;border-bottom:1px solid #e8e1da;vertical-align:top}.status{font-weight:bold}.foot{margin-top:18px;border-top:1px solid #ddd;padding-top:10px;font-size:8px;color:#777}@media print{body{background:#fff}.bar{display:none}.sheet{max-width:none;margin:0;box-shadow:none;padding:0}@page{size:A4 landscape;margin:9mm}}
</style></head><body><div class="bar"><b>Räucherhaken24 · Terminmanagement V92</b><button onclick="window.print()">Drucken / als PDF speichern</button></div><main class="sheet"><header class="head"><div><small>KUNDENBERATER · TERMINMANAGEMENT V92</small><?php $months=[1=>'Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember'];$py=(int)substr($period,0,4);$pm=(int)substr($period,5,2);?><h1><?=h2x(($months[$pm]??$period).' '.$py)?> · <?=h2x($rep['name']??'')?></h1><div><?=h2x($rep['employee_no']??'')?> · erstellt <?=h2x(date('d.m.Y H:i'))?></div></div><div><b><?=count($rows)?> Termine</b><br>Zeitraum <?=h2x($period)?></div></header><?php $s=$data['stats']??[];?><section class="stats"><div><b><?=h2x($s['today']??0)?></b>heute</div><div><b><?=h2x($s['next7']??0)?></b>nächste 7 Tage</div><div><b><?=h2x($s['open']??0)?></b>offen</div><div><b><?=h2x($s['confirmed']??0)?></b>bestätigt</div><div><b><?=h2x($s['followups_due']??0)?></b>Wiedervorlagen</div><div><b><?=h2x($s['no_show']??0)?></b>No-Show</div></section><table class="tbl"><thead><tr><th>Datum / Zeit</th><th>Termin</th><th>Art</th><th>Kunde / Kontakt</th><th>Adresse</th><th>Telefon / E-Mail</th><th>Status</th><th>Notiz / Ergebnis</th><th>Nächste Aktion</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><b><?=h2x(dt2($r['starts_at']))?></b><br>bis <?=h2x(date('H:i',strtotime((string)$r['ends_at'])))?> Uhr</td><td><b><?=h2x($r['title'])?></b></td><td><?=h2x($r['type_label']??$r['appointment_type'])?></td><td><?=h2x($r['contact_name']??$r['customer_name']??'–')?><br><small><?=h2x($r['customer_company']??'')?></small></td><td><?=h2x($r['address']??'–')?></td><td><?=h2x($r['phone']??'')?> <br><?=h2x($r['email']??'')?></td><td class="status"><?=h2x($r['status_label']??$r['status'])?></td><td><?=h2x($r['notes']??'')?><?php if(!empty($r['outcome'])):?><br><b>Ergebnis:</b> <?=h2x($r['outcome'])?><?php endif;?></td><td><?=h2x($r['next_action']??'–')?><?php if(!empty($r['follow_up_at'])):?><br>WV <?=h2x(dt2($r['follow_up_at']))?><?php endif;?></td></tr><?php endforeach;?></tbody></table><footer class="foot">Interner Terminplan Räucherhaken24 · Termine bleiben im Orgaboard dem jeweiligen Kundenberater zugeordnet.</footer></main></body></html>
