<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
rh24_require_login();
$requested=trim((string)($_GET['state_code']??''));$scope=rh24_territory_book_scope($requested);$code=(string)($scope['state_code']??'');
if($code===''){http_response_code(403);exit('Kein Gebietsbuch zugeordnet.');}
$rows=rh24_territory_directory_rows($code,false);$cats=rh24_territory_directory_categories();$active=array_values(array_filter($rows,fn($r)=>($r['status']??'')==='active'));$groups=[];foreach($active as $r)$groups[$r['category']][]=$r;
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
?><!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h($scope['territory_book_no'])?> Gebietsbuch</title><style>
:root{font-family:Arial,Helvetica,sans-serif;color:#172026}body{margin:0;background:#eef1f3}.bar{position:sticky;top:0;background:#17251d;color:#fff;padding:12px 18px;display:flex;justify-content:space-between;align-items:center}.bar button{border:0;border-radius:8px;padding:10px 14px;font-weight:800;cursor:pointer}.sheet{max-width:1120px;margin:22px auto;background:#fff;padding:28px;box-shadow:0 8px 35px #0002}.head{display:flex;justify-content:space-between;gap:20px;border-bottom:3px solid #17251d;padding-bottom:16px}.head small{letter-spacing:.13em;font-weight:800;color:#65736b}.head h1{margin:5px 0}.meta{text-align:right}.summary{display:flex;gap:16px;margin:16px 0;font-size:12px}.summary b{font-size:20px;display:block}.group{page-break-inside:auto;margin-top:24px}.group h2{font-size:16px;border-bottom:1px solid #ccd4cf;padding-bottom:7px}.row{display:grid;grid-template-columns:1.6fr 1.2fr 1fr 1.2fr;gap:12px;padding:9px 0;border-bottom:1px solid #e4e8e5;font-size:10px;page-break-inside:avoid}.row b{font-size:11px}.muted{color:#66736c}.foot{margin-top:25px;font-size:9px;color:#6b756f;border-top:1px solid #ddd;padding-top:10px}@media print{body{background:#fff}.bar{display:none}.sheet{margin:0;max-width:none;box-shadow:none;padding:0}.row{font-size:9px}@page{size:A4 landscape;margin:10mm}}
</style></head><body><div class="bar"><b>Gebietsbuch · PDF / Druckansicht</b><button onclick="window.print()">Drucken / als PDF speichern</button></div><main class="sheet"><div class="head"><div><small>RÄUCHERHAKEN24 · FESTGEBIET</small><h1><?=h($scope['territory_book_no'])?> · <?=h($scope['state_name'])?></h1><div class="muted">Aktive Geschäfte, Vereine und Branchenkontakte</div></div><div class="meta"><b><?=count($active)?> aktive Adressen</b><br><?=h(date('d.m.Y H:i'))?></div></div><div class="summary"><div><b><?=count($active)?></b>Aktiv</div><div><b><?=count($groups)?></b>Branchen</div><div><b><?=h($scope['sales_rep_name']?:'nicht vergeben')?></b>Gebietsinhaber</div></div><?php foreach($groups as $cat=>$list):?><section class="group"><h2><?=h($cats[$cat]??$cat)?> · <?=count($list)?></h2><?php foreach($list as $r):?><div class="row"><div><b><?=h($r['company'])?></b><br><?=h($r['contact_person']??'')?></div><div><?=h($r['street']??'')?><br><b><?=h(($r['zip']??'').' '.($r['city']??''))?></b></div><div><?=h($r['phone']??'–')?><?=!empty($r['mobile'])?'<br>Mobil: '.h($r['mobile']):''?><br><?=h($r['email']??'–')?></div><div>Letzter Kontakt: <?=h($r['last_contacted_at']?date('d.m.Y H:i',strtotime($r['last_contacted_at'])):'–')?><br>Wiedervorlage: <?=h($r['next_follow_up_at']?date('d.m.Y H:i',strtotime($r['next_follow_up_at'])):'–')?></div></div><?php endforeach;?></section><?php endforeach;?><div class="foot">Interne Vertriebsunterlage · Räucherhaken24. Automatisch importierte Daten werden erst nach Prüfung als aktiv geführt. OSM-basierte Recherchedaten: © OpenStreetMap-Mitwirkende.</div></main></body></html>