<?php
declare(strict_types=1);
require __DIR__.'/orgaboard/bootstrap.php';
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');header('X-Content-Type-Options: nosniff');header('Referrer-Policy: no-referrer');
function od_out(int $code,string $msg):never{http_response_code($code);header('Content-Type: application/json; charset=utf-8');echo json_encode(['ok'=>false,'error'=>$msg],JSON_UNESCAPED_UNICODE);exit;}
if(($_SERVER['REQUEST_METHOD']??'GET')!=='POST')od_out(405,'Nur POST-Anfragen sind erlaubt.');
$now=time();$attempts=is_array($_SESSION['rh24_order_doc_attempts']??null)?$_SESSION['rh24_order_doc_attempts']:[];$attempts=array_values(array_filter($attempts,fn($ts)=>is_int($ts)&&$ts>$now-300));if(count($attempts)>=30)od_out(429,'Zu viele Dokumentabfragen. Bitte später erneut versuchen.');$attempts[]=$now;$_SESSION['rh24_order_doc_attempts']=$attempts;
$data=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($data))$data=[];$orderNo=strtoupper(trim((string)($data['order_no']??'')));$email=strtolower(trim((string)($data['email']??'')));$type=(string)($data['type']??'invoice');if(!preg_match('/^[A-Z0-9-]{10,60}$/',$orderNo)||!filter_var($email,FILTER_VALIDATE_EMAIL)||!in_array($type,['invoice','delivery_note'],true))od_out(422,'Ungültige Dokumentanfrage.');
try{$db=rh24_db();$q=$db->prepare('SELECT customer_json FROM orders WHERE order_no=? LIMIT 1');$q->execute([$orderNo]);$raw=$q->fetchColumn();if($raw===false)od_out(404,'Dokument nicht gefunden.');$customer=rh24_json_decode((string)$raw,[]);$stored=strtolower(trim((string)($customer['email']??'')));if($stored===''||!hash_equals($stored,$email))od_out(404,'Dokument nicht gefunden.');$q=$db->prepare("SELECT id FROM documents WHERE order_no=? AND document_type=? AND status='issued' LIMIT 1");$q->execute([$orderNo,$type]);$id=$q->fetchColumn();if(!$id)od_out(404,'Dieses Dokument ist noch nicht freigegeben.');$doc=rh24_document_row((string)$id);if(!$doc)od_out(404,'Dokument nicht gefunden.');$pdf=rh24_document_pdf_content($doc);$filename=rh24_document_pdf_filename($doc);header('Content-Type: application/pdf');header('Content-Length: '.strlen($pdf));header('Content-Disposition: attachment; filename="'.$filename.'"');echo $pdf;exit;}catch(Throwable $e){od_out(503,'Dokument momentan nicht verfügbar.');}
