<?php
declare(strict_types=1);
require __DIR__.'/orgaboard/bootstrap.php';
header('Content-Type: application/json; charset=utf-8');
$recipient='service@raeucherhaken24.com';$maxTotal=15*1024*1024;$allowed=['image/jpeg','image/png','application/pdf'];$uploadDir=__DIR__.'/prototype-uploads';if(!is_dir($uploadDir))@mkdir($uploadDir,0775,true);
function fail($m,$c=400){http_response_code($c);echo json_encode(['ok'=>false,'error'=>$m],JSON_UNESCAPED_UNICODE);exit;}
if(!rh24_db_configured())fail('Shop-Datenbank ist noch nicht eingerichtet.',503);if($_SERVER['REQUEST_METHOD']!=='POST')fail('Methode nicht erlaubt',405);foreach(['project_name','customer_name','email','street','zip','city','accept_price','confirm_specs','rights_files','accept_terms'] as $f){if(empty($_POST[$f]))fail('Pflichtangabe fehlt: '.$f);}if(!filter_var($_POST['email'],FILTER_VALIDATE_EMAIL))fail('Ungültige E-Mail-Adresse');
$total=0;$saved=[];if(isset($_FILES['files'])){foreach($_FILES['files']['tmp_name'] as $i=>$tmp){if($_FILES['files']['error'][$i]===UPLOAD_ERR_NO_FILE)continue;if($_FILES['files']['error'][$i]!==UPLOAD_ERR_OK)fail('Dateiupload fehlgeschlagen');$size=(int)$_FILES['files']['size'][$i];$total+=$size;if($total>$maxTotal)fail('Dateien insgesamt zu groß');$mime=(new finfo(FILEINFO_MIME_TYPE))->file($tmp);if(!in_array($mime,$allowed,true))fail('Nicht erlaubter Dateityp');$ext=$mime==='application/pdf'?'pdf':($mime==='image/png'?'png':'jpg');$name=bin2hex(random_bytes(8)).'.'.$ext;$dest=$uploadDir.'/'.$name;if(!move_uploaded_file($tmp,$dest))fail('Datei konnte nicht gespeichert werden',500);$saved[]=['stored'=>$name,'original'=>basename($_FILES['files']['name'][$i]),'mime'=>$mime,'size'=>$size];}}
$ref='RH24-P-'.date('Ymd').'-'.strtoupper(bin2hex(random_bytes(3)));$customer=['name'=>trim((string)($_POST['customer_name']??'')),'email'=>strtolower(trim((string)($_POST['email']??''))),'phone'=>trim((string)($_POST['phone']??'')),'street'=>trim((string)($_POST['street']??'')),'zip'=>trim((string)($_POST['zip']??'')),'city'=>trim((string)($_POST['city']??'')),'company'=>''];$created=rh24_now();
try{$db=rh24_db();$db->beginTransaction();$customerId=rh24_customer_upsert($customer);$history=[['at'=>date('c'),'type'=>'created','value'=>'Prototypenanfrage übermittelt']];$db->prepare('INSERT INTO prototypes(reference,order_no,source,project_name,summary,customer_id,customer_json,fields_json,files_json,status,status_label,payment_status,internal_note,tracking,history_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$ref,null,'prototype-form',(string)($_POST['project_name']??''),(string)($_POST['summary']??''),$customerId,rh24_json_encode($customer),rh24_json_encode($_POST),rh24_json_encode($saved),'new','Anfrage','pending','','',rh24_json_encode($history),$created,$created]);$db->commit();rh24_audit('prototype_created','prototype',$ref,[],'shop');}catch(Throwable $e){if(isset($db)&&$db->inTransaction())$db->rollBack();fail('Prototypenanfrage konnte nicht gespeichert werden: '.$e->getMessage(),500);}
$subject='Neue Prototypenanfrage '.$ref.' – '.($_POST['project_name']??'');$message="Neue Prototypenanfrage\n\nReferenz: $ref\n\n".($_POST['summary']??'')."\n\nKunde: ".($_POST['customer_name']??'')."\nE-Mail: ".($_POST['email']??'')."\nTelefon: ".($_POST['phone']??'')."\n\nGespeicherte Dateien:\n";foreach($saved as $f)$message.=$f['original'].' -> '.$f['stored']."\n";$headers="From: service@raeucherhaken24.com\r\nReply-To: ".($_POST['email']??$recipient)."\r\nContent-Type: text/plain; charset=UTF-8";@mail($recipient,'=?UTF-8?B?'.base64_encode($subject).'?=',$message,$headers);@mail($_POST['email'],'=?UTF-8?B?'.base64_encode('Ihre Prototypenanfrage '.$ref).'?=',"Vielen Dank für Ihre Prototypenanfrage.\n\nReferenz: $ref\n\n".($_POST['summary']??''),"From: $recipient\r\nContent-Type: text/plain; charset=UTF-8");echo json_encode(['ok'=>true,'reference'=>$ref],JSON_UNESCAPED_UNICODE);
