<?php
declare(strict_types=1);
require __DIR__ . '/orgaboard/bootstrap.php';
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');

function finish(array $d,int $code=200):never{http_response_code($code);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
if(!rh24_db_configured())finish(['ok'=>false,'error'=>'Shop-Datenbank ist noch nicht eingerichtet.'],503);
if($_SERVER['REQUEST_METHOD']!=='POST')finish(['ok'=>false,'error'=>'Methode nicht erlaubt'],405);
$data=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($data))finish(['ok'=>false,'error'=>'Ungültige Anfrage'],400);if(!empty($data['website']))finish(['ok'=>false,'error'=>'Anfrage abgelehnt'],400);
$customer=is_array($data['customer']??null)?$data['customer']:[];$name=trim((string)($customer['name']??''));$email=strtolower(trim((string)($customer['email']??'')));$street=trim((string)($customer['street']??''));$zip=trim((string)($customer['zip']??''));$city=trim((string)($customer['city']??''));
if($name===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||$street===''||$zip===''||$city==='')finish(['ok'=>false,'error'=>'Bitte vollständige Kundendaten angeben.'],422);
$items=$data['items']??[];if(!is_array($items)||count($items)<1||count($items)>50)finish(['ok'=>false,'error'=>'Warenkorb ist ungültig.'],422);
$catalog=rh24_catalog();$clean=[];$subtotal=0.0;$productWeightG=0;$shippingWeightG=0;
try{foreach($items as $row){if(!is_array($row))continue;$id=(string)($row['id']??'');$aliases=['mehlBuche'=>'mehl-buche','mehlErle'=>'mehl-erle','mehlBirke'=>'mehl-birke','mehlEiche'=>'mehl-eiche','mehlKirsche'=>'mehl-kirsche','lauForelle'=>'lauge-forelle-0','lauForelleChili'=>'lauge-forelle-2','lauForelleRed'=>'lauge-forelle-3','lauAal'=>'lauge-aal-0'];$id=$aliases[$id]??$id;$qty=max(1,min(99,(int)($row['qty']??1)));$meta=is_array($row['meta']??null)?$row['meta']:[];if(!isset($catalog[$id]))throw new InvalidArgumentException('Unbekannter Artikel im Warenkorb.');$price=rh24_resolve_price($id,$meta);if($price<=0)throw new InvalidArgumentException('Dieser Artikel ist noch nicht für den Verkauf freigegeben.');$line=round($price*$qty,2);$subtotal+=$line;$pw=max(0,(int)($catalog[$id]['product_weight_g']??0));$sw=max(0,(int)($catalog[$id]['shipping_weight_g']??0));$productWeightG+=$pw*$qty;$shippingWeightG+=$sw*$qty;$clean[]=['id'=>$id,'article_no'=>$catalog[$id]['article_no']??'','name'=>$catalog[$id]['name'],'unit'=>$catalog[$id]['unit'],'product_weight_g'=>$pw,'shipping_weight_g'=>$sw,'qty'=>$qty,'meta'=>$meta,'unit_price'=>$price,'line_total'=>$line];}}catch(Throwable $e){finish(['ok'=>false,'error'=>$e->getMessage()],422);}if(!$clean)finish(['ok'=>false,'error'=>'Warenkorb ist leer.'],422);
$cfg=rh24_config();$threshold=(float)($cfg['shipping_threshold']??39);$shipping=$subtotal>=$threshold?0.0:(float)($cfg['shipping_cost']??7);$gross=round($subtotal+$shipping,2);$vatRate=(float)($cfg['vat_rate']??19);$net=round($gross/(1+$vatRate/100),2);$vat=round($gross-$net,2);
$orderNo='RH24-'.date('Ymd').'-'.strtoupper(bin2hex(random_bytes(3)));$created=rh24_now();$cust=['name'=>$name,'email'=>$email,'phone'=>trim((string)($customer['phone']??'')),'street'=>$street,'zip'=>$zip,'city'=>$city,'company'=>trim((string)($customer['company']??''))];$totals=['subtotal'=>round($subtotal,2),'shipping'=>$shipping,'net'=>$net,'vat'=>$vat,'vat_rate'=>$vatRate,'gross'=>$gross,'product_weight_g'=>$productWeightG,'shipping_weight_g'=>$shippingWeightG];$history=[['at'=>date('c'),'type'=>'created','value'=>'Shopbestellung eingegangen'],['at'=>date('c'),'type'=>'payment','value'=>'pending']];
$db=rh24_db();
try{
  $db->beginTransaction();$customerId=rh24_customer_upsert($cust,$orderNo);
  $attr=rh24_resolve_sales_attribution($db,$customerId,'online','');
  $history[]=['at'=>date('c'),'type'=>'sales_attribution','channel'=>$attr['sales_channel'],'commission_sales_rep_id'=>$attr['commission_sales_rep_id'],'value'=>$attr['commission_note']];
  $st=$db->prepare('INSERT INTO orders(order_no,source,sales_channel,status,status_label,payment_status,payment_method,carrier,tracking,internal_note,customer_id,sales_rep_id,commission_sales_rep_id,commission_attribution,commission_note,commission_assigned_at,customer_json,items_json,totals_json,customer_note,history_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
  $st->execute([$orderNo,'shop',$attr['sales_channel'],'payment_pending','Zahlung offen','pending','Auftragsbestätigung / Zahlungsanweisung','DPD','', '',$customerId,$attr['sales_rep_id']===''?null:$attr['sales_rep_id'],$attr['commission_sales_rep_id'],$attr['commission_attribution'],$attr['commission_note'],$created,rh24_json_encode($cust),rh24_json_encode($clean),rh24_json_encode($totals),trim((string)($data['note']??'')),rh24_json_encode($history),$created,$created]);
  $inv=$db->prepare('UPDATE inventory SET stock=GREATEST(0,stock-?),updated_at=NOW() WHERE id=?');foreach($clean as $line){if($line['id']==='prototype-project')continue;$inv->execute([(int)$line['qty'],$line['id']]);}
  foreach($clean as $line){if($line['id']!=='prototype-project')continue;$pm=is_array($data['prototype_meta']??null)?$data['prototype_meta']:[];$projectName=(string)($pm['project_name']??'Prototypenentwicklung Räucherhaken');$find=$db->prepare("SELECT reference,history_json FROM prototypes WHERE customer_id=? AND project_name=? AND status IN ('new','payment_pending') AND created_at>=DATE_SUB(NOW(),INTERVAL 1 DAY) ORDER BY created_at DESC LIMIT 1 FOR UPDATE");$find->execute([$customerId,$projectName]);$found=$find->fetch();if($found){$ph=rh24_json_decode($found['history_json'],[]);$ph[]=['at'=>date('c'),'type'=>'order','value'=>$orderNo];$db->prepare("UPDATE prototypes SET order_no=?,status='payment_pending',status_label='Zahlung offen',payment_status='pending',history_json=?,updated_at=NOW() WHERE reference=?")->execute([$orderNo,rh24_json_encode($ph),$found['reference']]);}else{$ref='RH24-P-'.date('Ymd').'-'.strtoupper(bin2hex(random_bytes(3)));$ph=[['at'=>date('c'),'type'=>'created','value'=>'Projekt über Shop bestellt'],['at'=>date('c'),'type'=>'order','value'=>$orderNo]];$db->prepare('INSERT INTO prototypes(reference,order_no,source,project_name,summary,customer_id,customer_json,fields_json,files_json,status,status_label,payment_status,internal_note,tracking,history_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$ref,$orderNo,'checkout',$projectName,(string)($pm['summary']??''),$customerId,rh24_json_encode($cust),rh24_json_encode($pm),'[]','payment_pending','Zahlung offen','pending','','',rh24_json_encode($ph),$created,$created]);}break;}
  $db->commit();rh24_audit('shop_order_created','order',$orderNo,['gross'=>$gross,'sales_channel'=>$attr['sales_channel'],'commission_sales_rep_id'=>$attr['commission_sales_rep_id'],'commission_attribution'=>$attr['commission_attribution']],'shop');
}catch(Throwable $e){if($db->inTransaction())$db->rollBack();finish(['ok'=>false,'error'=>'Bestellung konnte nicht gespeichert werden: '.$e->getMessage()],500);}

$recipient='service@raeucherhaken24.com';$lines=[];foreach($clean as $x)$lines[]=$x['qty'].' × '.$x['name'].(!empty($x['article_no'])?' (Art.-Nr. '.$x['article_no'].')':'').' = '.number_format($x['line_total'],2,',','.').' €';$msg="Neue Shopbestellung\n\nBestellnummer: $orderNo\nHerkunft: Online-Shop\nProvisionsgutschrift: ".($attr['commission_sales_rep_name']?:'-')."\nZuordnung: ".$attr['commission_note']."\n\nKunde: $name\nE-Mail: $email\nTelefon: ".($cust['phone']?:'-')."\nAdresse: $street, $zip $city\n\n".implode("\n",$lines)."\n\nVersandgewicht: ".($shippingWeightG>0?number_format($shippingWeightG/1000,3,',','.').' kg':'noch nicht vollständig hinterlegt')."\nVersand: ".number_format($shipping,2,',','.')." €\nGesamt: ".number_format($gross,2,',','.')." €\n\nStatus: Zahlung offen\n";$headers="From: service@raeucherhaken24.com\r\nReply-To: $email\r\nContent-Type: text/plain; charset=UTF-8";@mail($recipient,'=?UTF-8?B?'.base64_encode('Neue Bestellung '.$orderNo).'?=',$msg,$headers);
$documentsSent=false;$documentsReady=false;$invoiceNo='';$documentError='';
try{$profile=rh24_invoice_profile();$bundle=rh24_order_document_bundle($orderNo,false);$documentsReady=(bool)($bundle['readiness']['ready']??false);$invoiceNo=(string)($bundle['documents']['invoice']['document_no']??'');if($documentsReady&&($profile['auto_email']??true)){$mailResult=rh24_email_order_documents($orderNo,$email);$documentsSent=!empty($mailResult['ok']);if(!$documentsSent)$documentError=(string)($mailResult['reason']??'mail_failed');}}catch(Throwable $e){$documentError=$e->getMessage();}
if(!$documentsSent){$customerMsg="Vielen Dank für Ihre Bestellung bei Räucherhaken24.\n\nBestellnummer: $orderNo\nGesamtbetrag: ".number_format($gross,2,',','.')." €\n\nIhre Bestellung wurde erfasst. Rechnung und Lieferschein werden im Rechnungstool bereitgestellt und können über den Bestellfortschritt abgerufen werden, sobald die Dokumente freigegeben sind.\n\nIhren Bestellfortschritt können Sie im Kundenlogin mit Ihrer Bestellnummer und dieser E-Mail-Adresse abrufen.\n\nRäucherhaken24";@mail($email,'=?UTF-8?B?'.base64_encode('Ihre Bestellung '.$orderNo).'?=',$customerMsg,"From: $recipient\r\nContent-Type: text/plain; charset=UTF-8");}
finish(['ok'=>true,'order_no'=>$orderNo,'gross'=>$gross,'documents_sent'=>$documentsSent,'documents_ready'=>$documentsReady,'invoice_no'=>$invoiceNo,'document_error'=>$documentError]);
